import Foundation

enum Localizer {
    static func text(_ key: String, language: AppLanguage) -> String {
        table(for: language)[key] ?? english[key] ?? key
    }

    /// Internal tables also let tests detect omissions before English fallback hides them.
    static func table(for language: AppLanguage) -> [String: String] {
        localizedTables[language.effectiveLanguage] ?? english
    }

    // Build each complete catalog once; looking up a label must not merge hundreds of keys.
    private static let localizedTables: [AppLanguage: [String: String]] = Dictionary(uniqueKeysWithValues:
        AppLanguage.supported.map { language in
            (language, baseTable(for: language).merging(MetricExplanationCatalog.table(for: language)) { _, explanation in explanation })
        })

    private static func baseTable(for language: AppLanguage) -> [String: String] {
        switch language.effectiveLanguage {
        case .system, .en: return baseEnglish
        case .ru: return russian
        case .de: return LocalizationDE.strings
        case .fr: return LocalizationFR.strings
        case .es: return LocalizationES.strings
        case .it: return LocalizationIT.strings
        case .ptBR: return LocalizationPTBR.strings
        case .nl: return LocalizationNL.strings
        case .pl: return LocalizationPL.strings
        case .ja: return LocalizationJA.strings
        case .ko: return LocalizationKO.strings
        case .zhHans: return LocalizationZHHans.strings
        }
    }

    static let english = baseEnglish.merging(MetricExplanationCatalog.table(for: .en)) { _, explanation in explanation }

    private static let baseEnglish: [String: String] = [
        "widget.summary.minimum": "Keep at least one measurement selected.",
        "widget.summary.hint": "Only selected measurements with available readings appear. Widget size limits how many fit.",
        "widget.summary.primary": "Preferred main measurement",
        "widget.summary.choose": "Choose measurements",
        "settings.widgets": "Widgets",
        "settings.widgetsSubtitle": "Five ready-made widgets for your desktop.",
        "widget.type": "Widget type",
        "widget.appearance": "Widget appearance",
        "widget.appearance.colorful": "Colorful",
        "widget.appearance.light": "Light",
        "widget.appearance.dark": "Dark",
        "widget.appearanceHint": "One appearance for all five desktop widgets.",
        "widget.automaticHint": "Available readings are selected automatically.",
        "widget.guide.fixedTypes": "Choose a widget type and size, then add it to your desktop.",
        "widget.slot.day": "Day",
        "widget.slot.day.description": "Body Battery, steps, stress and daily activity.",
        "onboarding.title": "Your Garmin data, on your Mac",
        "onboarding.privacy": "Your readings are stored on this Mac",
        "onboarding.detail": "Connect your Garmin account to see your measurements here and in desktop widgets.",
        "data.available": "Latest measurements",
        "data.nightEnding": "Night ending",
        "data.measured": "Measured",
        "data.received": "Received",
        "metric.short.spo2": "SpO₂ · daily avg",
        "data.waiting": "Waiting for your watch data",
        "data.waitingNew": "Waiting for new measurements",
        "data.unchanged": "No changes in your measurements",
        "data.checkFailed": "Could not refresh Garmin data",
        "data.unchangedHint": "Expecting newer readings? Open Garmin Connect on your phone and sync your watch. We will pick them up automatically.",
        "data.retainedAllHint": "Your last readings are shown below with their dates. Open Garmin Connect on your phone and sync your watch for newer measurements.",
        "data.previous": "Last available",
        "data.retainedHint": "Some readings have not arrived yet. We have kept your last values with their dates. Sync your watch in Garmin Connect on your phone.",
        "data.waitingHint": "Open Garmin Connect on your phone and sync your watch. Your readings will appear here automatically.",
        "widget.notice.connection": "Reconnect Garmin",
        "widget.notice.unavailable": "Could not update",
        "widget.notice.waiting": "Waiting for new data",
        "widget.waiting": "Waiting for data",
        "widget.waitingHint": "Sync your watch in Garmin Connect on your phone. Your readings will appear here automatically.",
        "widget.previous": "Last available",
        "widget.slot.overview.description": "Your selected measurements in one widget.",
        "widget.slot.sport.description": "Training readiness, recovery, load and VO₂ max.",
        "widget.slot.sleep.description": "Sleep duration, sleep score and overnight HRV.",
        "widget.slot.training.description": "A calendar of completed activities and scheduled workouts.",
        "widget.preview.easyRun": "Easy run", "widget.preview.intervals": "Running intervals",
        "profile.availableMetrics": "Use available readings",
        "profile.availableMetricsHint": "Skip missing readings and fill the widget with related metrics. Turn off to keep your exact selection.",
        "profile.content": "Content", "content.metrics": "Metrics", "content.training": "Training calendar", "content.mixed": "Both",
        "profile.previewMetricsOnly": "This preview shows the metrics section. Your workout cards also appear in the Overview section.",
        "status.signInRequired": "Sign-in required",
        "connection.retryAfter": "Try again after",
        "connection.reconnectDetail": "Open the Garmin window and finish signing in to resume updates.",
        "widget.guide.staticProfile": "Choose a widget type and size, then add it to your desktop.",
        "widget.guide.unavailable": "View your readings and widget previews in the app.",
        "widget.sharingDataUnavailable": "Widget data is not available yet. Your measurements can still be viewed in the app.",
        "widget.slot.overview": "Summary", "widget.slot.sport": "Sport", "widget.slot.sleep": "Sleep", "widget.slot.training": "Training calendar",
        "widget.slot.firstProfile": "First profile", "widget.slot.unassigned": "Choose a profile…",
        "profile.templates": "Start with a template", "profile.custom": "Custom profile",
        "profile.template.life": "Life", "profile.template.sport": "Sport", "profile.template.sleep": "Sleep",
        "profile.previewSize": "Widget size", "profile.preview.small": "Small", "profile.preview.medium": "Medium", "profile.preview.large": "Large",
        "profile.previewCount": "Shows %d of %d metrics. All selected metrics are available in the Overview section.",
        "widget.galleryTitle": "Garmin summary",
        "widget.galleryDescription": "Health, sleep, activity and training in five ready-made widgets.",
        "widget.galleryStaticDescription": "Choose a widget type and size. Available readings appear automatically.",
        "connection.webTitle": "Connect Garmin",
        "connection.webSubtitle": "Connect once. Your measurements refresh automatically.",
        "connection.webIntro": "Sign in to Garmin Connect",
        "connection.webDetail": "A secure Garmin window will open. Complete sign-in and any verification Garmin requests. The app then keeps this connection on your Mac.",
        "connection.webSignIn": "Sign in with Garmin",
        "connection.webPrivacy": "Measurements and the Garmin website session stay on this Mac. Your password goes directly to Garmin. There is no separate server or analytics.",
        "connection.automaticHint": "Your data updates in the background, including after waking your Mac. Keep Garmin Desk running for automatic updates.",
        "connection.reconnect": "Reconnect Garmin", "connection.nextSync": "Next update after",
        "error.partial": "Some measurements could not be refreshed. Saved data is still available.",

        "diagnostic.title": "Connection details", "diagnostic.stage": "Stage", "diagnostic.apiCode": "Garmin code", "diagnostic.requests": "Responses received",
        "menu.edit": "Edit", "menu.cut": "Cut", "menu.copy": "Copy", "menu.paste": "Paste", "menu.selectAll": "Select All",
        "app.subtitle": "Your day, at a glance", "app.device": "Garmin fēnix 8",
        "dashboard.title": "Overview", "dashboard.profile": "Profile", "dashboard.moreMetrics": "Larger widgets can show more metrics",
        "dashboard.configure": "Widget settings",
        "widget.setup": "Set up desktop widgets", "widget.customize": "Widget settings",
        "widget.guide.add": "Right-click the desktop and choose Edit Widgets. Find GarminDesk in the gallery.",
        "widget.guide.profile": "Choose a widget type and size, then add it to your desktop.",
        "widget.guide.refresh": "Garmin Desk fetches your measurements. macOS decides when the desktop widget refreshes.",
        "widget.sharingUnavailable": "Desktop widgets are not available in this build. You can still view your readings in the app.",
        "widget.openApp": "Open GarminDesk", "widget.openAppHint": "Connect your Garmin account in the app.",
        "widget.profileMissing": "Profile removed", "widget.profileMissingHint": "Choose another profile in this widget’s settings.",
        "widget.demo": "DEMO", "widget.connect": "Connect Garmin in the app",
        "dashboard.empty": "Choose the metrics you want to see in settings.", "dashboard.connect": "Connect Garmin",
        "action.settings": "Settings", "action.sync": "Refresh", "action.quit": "Quit Garmin Desk",
        "action.cancel": "Cancel", "action.save": "Save", "action.delete": "Delete", "action.duplicate": "Duplicate",
        "action.add": "Add profile", "action.up": "Move up", "action.down": "Move down", "action.show": "Show",
        "action.hide": "Hide", "action.done": "Done", "action.retry": "Try again",
        "data.demo": "Demo data", "data.updated": "Checked", "data.stale": "Data may be out of date",
        "data.day": "Data for", "data.partial": "Some measurements are unavailable",
        "data.emptyDay": "Garmin has no measurements for this date yet. Sync your watch with Garmin Connect to update them.",
        "data.empty": "No measurement yet", "data.demoDetail": "Example values. Connect your account to see your measurements.",
        "data.local": "Stored on this Mac", "data.source": "Latest Garmin Connect sync", "data.syncing": "Checking Garmin Connect…",
        "status.connected": "Garmin connected", "status.notConnected": "Garmin not connected", "status.connecting": "Connecting…",
        "settings.title": "Settings", "settings.profiles": "Widget profiles", "settings.connection": "Garmin account", "settings.general": "General",
        "settings.profilesSubtitle": "Create a view for each part of your day.", "settings.generalSubtitle": "Make Garmin Desk feel at home on your Mac.",
        "profile.name": "Profile name", "profile.primary": "Main metric", "profile.metrics": "Metrics",
        "profile.metricsHint": "Choose what to display. The main metric always appears first.", "profile.appearance": "Appearance",
        "profile.style": "Style", "profile.density": "Density", "profile.preview": "Preview",
        "profile.added": "New profile", "profile.new": "New profile", "profile.default": "My day", "profile.copy": "Copy", "profile.untitled": "Untitled profile",
        "profile.deleteTitle": "Delete this profile?", "profile.deleteMessage": "The profile will be removed. Your Garmin data will stay on this Mac.",
        "profile.oneRequired": "Keep at least one profile.", "profile.enabled": "Included", "profile.available": "Available metrics",
        "profile.count": "metrics", "profile.mainBadge": "Main",
        "style.calm": "Calm", "style.sport": "Sport", "style.monochrome": "Monochrome",
        "density.comfortable": "Comfortable", "density.compact": "Compact",
        "connection.title": "Your Garmin account", "connection.subtitle": "Your Mac connects directly to Garmin Connect.",
        "connection.localTitle": "Your data stays with you", "connection.localDetail": "Measurements are cached on this Mac. Session credentials are stored in macOS Keychain. The app has no separate server.",
        "connection.email": "Email", "connection.password": "Password", "connection.china": "Use Garmin China",
        "connection.signIn": "Connect account", "connection.disconnect": "Disconnect and clear local data",
        "connection.disconnectTitle": "Disconnect Garmin?", "connection.disconnectMessage": "This removes the saved Garmin session and cached measurements from this Mac. Your preferences are kept.",
        "connection.demo": "Explore with demo data", "connection.demoHint": "Demo values are always labeled.",
        "connection.syncHint": "Sync your watch with Garmin Connect to make new measurements available here.",
        "connection.secureHint": "Your password is only used to sign in and is not saved by this app.",
        "connection.mfaTitle": "Verification code", "connection.mfaHint": "Enter the code requested by Garmin to finish connecting.",
        "connection.mfaCode": "Code", "connection.verify": "Verify", "connection.cancelLogin": "Cancel sign-in",
        "general.language": "Language", "general.appearance": "Appearance", "general.refresh": "Refresh interval",
        "general.system": "Follow system", "general.light": "Light", "general.dark": "Dark",
        "general.minutes5": "Every 5 minutes", "general.minutes15": "Every 15 minutes", "general.minutes30": "Every 30 minutes",
        "general.minutes60": "Every hour", "general.refreshHint": "Updates use the latest measurements available in Garmin Connect.",
        "general.localNotice": "Your preferences are saved automatically on this Mac.",
        "general.launchAtLogin": "Open Garmin Desk at login",
        "general.backgroundHint": "Closing the window keeps automatic updates running. Choose Quit Garmin Desk or press ⌘Q to stop the app.",
        "menu.about": "About Garmin Desk", "menu.hideApp": "Hide Garmin Desk", "menu.hideOthers": "Hide Others", "menu.showAll": "Show All",
        "menu.file": "File", "menu.closeWindow": "Close Window", "menu.window": "Window", "menu.mainWindow": "Garmin Desk",
        "menu.minimize": "Minimize", "menu.zoom": "Zoom",
        "category.health": "Health & recovery", "category.sleep": "Sleep", "category.activity": "Daily activity", "category.training": "Training", "category.body": "Body & hydration",
        "metric.steps": "Steps", "metric.stepGoal": "Step goal", "metric.distance": "Distance", "metric.calories": "Total calories",
        "metric.activeCalories": "Active calories", "metric.floors": "Floors climbed", "metric.intensityMinutes": "Intensity minutes",
        "metric.restingHeartRate": "Resting heart rate", "metric.heartRate": "Latest heart rate", "metric.stress": "Average daily stress", "metric.bodyBattery": "Body Battery",
        "metric.sleepDuration": "Sleep duration", "metric.sleepScore": "Sleep score", "metric.deepSleep": "Deep sleep", "metric.remSleep": "REM sleep",
        "metric.lightSleep": "Light sleep", "metric.awakeSleep": "Awake time", "metric.hrv": "Overnight HRV", "metric.spo2": "Average daily SpO₂",
        "metric.respiration": "Average sleep respiration", "metric.trainingReadiness": "Training readiness", "metric.recoveryTime": "Recovery time",
        "metric.vo2Max": "Running VO₂ max", "metric.trainingLoad": "Acute training load", "metric.weight": "Weight", "metric.hydration": "Hydration",
        "metric.short.sleepDuration": "Sleep", "metric.short.stress": "Stress · day",
        "metric.short.restingHeartRate": "Resting HR", "metric.short.trainingReadiness": "Readiness",
        "metric.short.hrv": "HRV · night", "metric.short.respiration": "Breathing · sleep",
        "metric.short.intensityMinutes": "Intensity min", "metric.short.activeCalories": "Active calories",
        "metric.short.recoveryTime": "Recovery", "metric.short.trainingLoad": "Acute load",
        "metric.short.vo2Max": "Run VO₂ max", "metric.short.calories": "Total calories",
        "unit.minutes": "min", "unit.hours": "h", "unit.km": "km", "unit.kg": "kg", "unit.ml": "ml", "unit.bpm": "bpm",
        "unit.kcal": "kcal", "unit.ms": "ms", "unit.breaths": "br/min", "unit.vo2": "ml/kg/min",
        "error.auth": "Could not sign in. Check your details and try again.", "error.rate_limit": "Garmin has temporarily limited requests. Please try again later.",
        "error.session_unsupported": "This app cannot restore the saved session. Reconnect your Garmin account.",
        "error.access_denied": "Garmin denied access to the requested data.",
        "error.security_challenge": "A Garmin security check blocked the connection. Please try again later.",
        "error.network": "Could not reach Garmin. Check your internet connection.", "error.dependency": "The Garmin connection component is unavailable. Reinstall the latest version of Garmin Desk.",
        "error.unknown": "Could not complete the request. Please try again.", "error.timeout": "Garmin took too long to respond. Please try again.",
        "error.keychain": "Could not access macOS Keychain. Check that it is unlocked.", "error.protocol": "Garmin returned data the app could not read. Please try again later.",
        "error.storage": "Could not save data on this Mac. Check available disk space and permissions.",
        "error.login_item": "Allow Garmin Desk to open at login in macOS Settings → General → Login Items.",
        "training.title": "Training",
        "training.last": "Last completed",
        "training.next": "Next planned",
        "training.completed": "Completed",
        "training.planned": "Scheduled",
        "training.recent": "Recent activities",
        "training.upcoming": "Upcoming workouts",
        "training.workout": "Workout",
        "training.dateUnknown": "Date not provided",
        "training.timeUnknown": "Time not provided",
        "training.localTime": "recorded local time",
        "training.durationUnknown": "Duration not provided",
        "training.pastUnavailable": "History is not available yet",
        "training.pastUnavailableHint": "This section has not been successfully retrieved from Garmin yet.",
        "training.pastEmpty": "No activities in the latest response",
        "training.pastCoverage": "Up to 20 recent activities · not the full history",
        "training.futureUnavailable": "Schedule is not available yet",
        "training.futureUnavailableHint": "An unavailable calendar does not mean there are no workouts.",
        "training.futureEmpty": "No workouts in the retrieved portion",
        "training.calendar": "Published Garmin calendar",
        "training.adaptive": "Verified adaptive calendar",
        "training.partial": "Part of the calendar is unavailable",
        "training.expiredCoverage": "The checked period has ended",
        "training.refreshCalendar": "Refresh to check a new period.",
        "training.updated": "Updated",
        "training.updatedUnknown": "Update time is unknown",
        "training.cached": "Saved data",
        "training.refreshFailed": "This section could not be refreshed",
        "training.rateLimit": "Garmin is temporarily limiting requests",
        "training.signIn": "Sign in to Garmin Connect to refresh",
        "training.hour": "h",
        "training.minute": "min",
        "training.second": "s",
        "training.km": "km",
        "training.sport.running": "Running",
        "training.sport.trail_running": "Trail running",
        "training.sport.treadmill_running": "Treadmill running",
        "training.sport.track_running": "Track running",
        "training.sport.cycling": "Cycling",
        "training.sport.mountain_biking": "Off-road cycling",
        "training.sport.indoor_cycling": "Indoor cycling",
        "training.sport.swimming": "Swimming",
        "training.sport.open_water_swimming": "Open-water swimming",
        "training.sport.walking": "Walking",
        "training.sport.hiking": "Hiking",
        "training.sport.strength_training": "Strength training",
        "training.sport.cardio_training": "Cardio",
        "training.sport.elliptical": "Elliptical",
        "training.sport.stair_climbing": "Stair climbing",
        "training.sport.yoga": "Yoga",
        "training.sport.pilates": "Pilates",
        "training.sport.rowing": "Rowing",
        "training.sport.tennis": "Tennis",
        "training.sport.golf": "Golf",
        "training.sport.alpine_skiing": "Alpine skiing",
        "training.sport.cross_country_skiing": "Cross-country skiing",
        "training.sport.snowboarding": "Snowboarding",
        "training.sport.triathlon": "Multisport",
        "training.noPublishedThrough": "No published workouts through %@",
        "training.checkedThrough": "checked through %@",
    ]

    static let russian: [String: String] = [
        "widget.summary.minimum": "Должен быть выбран хотя бы один показатель.",
        "widget.summary.hint": "Показываются только выбранные показатели с доступными данными. Их количество зависит от размера виджета.",
        "widget.summary.primary": "Главный показатель",
        "widget.summary.choose": "Выбрать показатели",
        "settings.widgets": "Виджеты",
        "settings.widgetsSubtitle": "Пять готовых виджетов для рабочего стола.",
        "widget.type": "Тип виджета",
        "widget.appearance": "Оформление виджетов",
        "widget.appearance.colorful": "Цветное",
        "widget.appearance.light": "Светлое",
        "widget.appearance.dark": "Тёмное",
        "widget.appearanceHint": "Одно оформление для всех пяти виджетов.",
        "widget.automaticHint": "Доступные показатели подбираются автоматически.",
        "widget.guide.fixedTypes": "Выбери тип и размер виджета, затем добавь его на рабочий стол.",
        "widget.slot.day": "День",
        "widget.slot.day.description": "Body Battery, шаги, стресс и дневная активность.",
        "onboarding.title": "Твои данные Garmin — на Mac",
        "onboarding.privacy": "Показатели сохраняются на этом Mac",
        "onboarding.detail": "Подключи аккаунт Garmin, чтобы видеть свои показатели здесь и в виджетах рабочего стола.",
        "data.available": "Последние измерения",
        "data.nightEnding": "Ночь на",
        "data.measured": "Измерено",
        "data.received": "Получено",
        "metric.short.spo2": "SpO₂ · за день",
        "data.waiting": "Ждём данные с часов",
        "data.waitingNew": "Ждём новые измерения",
        "data.unchanged": "Показатели пока без изменений",
        "data.checkFailed": "Не удалось обновить данные Garmin",
        "data.unchangedHint": "Ожидаешь более свежие показатели? Открой Garmin Connect на телефоне и синхронизируй часы. Новые данные появятся здесь автоматически.",
        "data.retainedAllHint": "Ниже — последние показатели с их датами. Чтобы получить свежие, открой Garmin Connect на телефоне и синхронизируй часы.",
        "data.previous": "Последние данные",
        "data.retainedHint": "Часть показателей ещё не поступила. Сохранили последние значения с их датами. Синхронизируй часы в Garmin Connect на телефоне.",
        "data.waitingHint": "Открой Garmin Connect на телефоне и синхронизируй часы. Показатели появятся здесь автоматически.",
        "widget.notice.connection": "Подключи Garmin снова",
        "widget.notice.unavailable": "Не удалось обновить",
        "widget.notice.waiting": "Ждём свежие данные",
        "widget.waiting": "Ждём данные с часов",
        "widget.waitingHint": "Синхронизируй часы в Garmin Connect на телефоне. Показатели появятся здесь автоматически.",
        "widget.previous": "Последние данные",
        "widget.slot.overview.description": "Выбранные тобой показатели в одном виджете.",
        "widget.slot.sport.description": "Готовность к тренировке, восстановление, нагрузка и VO₂ max.",
        "widget.slot.sleep.description": "Длительность и оценка сна, ночная ВСР.",
        "widget.slot.training.description": "Календарь завершённых занятий и запланированных тренировок.",
        "widget.preview.easyRun": "Лёгкий бег", "widget.preview.intervals": "Беговые интервалы",
        "profile.availableMetrics": "Использовать доступные данные",
        "profile.availableMetricsHint": "Пропускать показатели без данных и дополнять виджет связанными показателями. Отключи, чтобы сохранить точный набор.",
        "profile.content": "Содержимое", "content.metrics": "Показатели", "content.training": "Календарь тренировок", "content.mixed": "Всё вместе",
        "profile.previewMetricsOnly": "Здесь показан раздел с измерениями. Карточки тренировок также доступны в разделе «Обзор».",
        "status.signInRequired": "Нужно войти в Garmin",
        "connection.retryAfter": "Повторная попытка после",
        "connection.reconnectDetail": "Открой окно Garmin и заверши вход, чтобы возобновить обновления.",
        "widget.guide.staticProfile": "Выбери тип и размер виджета, затем добавь его на рабочий стол.",
        "widget.guide.unavailable": "Смотри показатели и превью виджетов в приложении.",
        "widget.sharingDataUnavailable": "Данные виджета пока недоступны. Показатели можно смотреть в приложении.",
        "widget.slot.overview": "Сводка", "widget.slot.sport": "Спорт", "widget.slot.sleep": "Сон", "widget.slot.training": "Календарь тренировок",
        "widget.slot.firstProfile": "Первый профиль", "widget.slot.unassigned": "Выбери профиль…",
        "profile.templates": "Начать с шаблона", "profile.custom": "Свой набор",
        "profile.template.life": "Жизнь", "profile.template.sport": "Спорт", "profile.template.sleep": "Сон",
        "profile.previewSize": "Размер виджета", "profile.preview.small": "Малый", "profile.preview.medium": "Средний", "profile.preview.large": "Большой",
        "profile.previewCount": "Показано %d из %d. Все выбранные показатели доступны в разделе «Обзор».",
        "widget.galleryTitle": "Сводка Garmin",
        "widget.galleryDescription": "Здоровье, сон, активность и тренировки в пяти готовых виджетах.",
        "widget.galleryStaticDescription": "Выбери тип и размер виджета. Доступные показатели появятся автоматически.",
        "connection.webTitle": "Подключение Garmin",
        "connection.webSubtitle": "Подключи один раз — показатели будут обновляться автоматически.",
        "connection.webIntro": "Войди в Garmin Connect",
        "connection.webDetail": "Откроется защищённое окно Garmin. Заверши вход и проверку, если Garmin её запросит. Приложение сохранит это подключение на твоём Mac.",
        "connection.webSignIn": "Войти через Garmin",
        "connection.webPrivacy": "Показатели и сессия сайта Garmin остаются на этом Mac. Пароль передаётся непосредственно Garmin. Отдельного сервера и аналитики нет.",
        "connection.automaticHint": "Данные обновляются в фоне, в том числе после пробуждения Mac. Оставь Garmin Desk запущенным для автоматического обновления.",
        "connection.reconnect": "Восстановить подключение", "connection.nextSync": "Следующее обновление после",
        "error.partial": "Часть показателей не обновилась. Сохранённые данные остаются доступны.",

        "diagnostic.title": "Подробности подключения", "diagnostic.stage": "Этап", "diagnostic.apiCode": "Код Garmin", "diagnostic.requests": "Получено ответов",
        "menu.edit": "Правка", "menu.cut": "Вырезать", "menu.copy": "Копировать", "menu.paste": "Вставить", "menu.selectAll": "Выбрать всё",
        "app.subtitle": "Всё о твоём дне", "app.device": "Garmin fēnix 8",
        "dashboard.title": "Обзор", "dashboard.profile": "Профиль", "dashboard.moreMetrics": "Большие виджеты вмещают больше показателей",
        "dashboard.configure": "Настройки виджетов",
        "widget.setup": "Настроить виджеты на столе", "widget.customize": "Настройки виджетов",
        "widget.guide.add": "Нажми правой кнопкой на рабочий стол и выбери «Изменить виджеты». Найди GarminDesk в галерее.",
        "widget.guide.profile": "Выбери тип и размер виджета, затем добавь его на рабочий стол.",
        "widget.guide.refresh": "Garmin Desk загружает измерения. Время обновления виджета на столе определяет macOS.",
        "widget.sharingUnavailable": "В этой сборке системные виджеты недоступны. Показатели можно смотреть в приложении.",
        "widget.openApp": "Открой GarminDesk", "widget.openAppHint": "Подключи аккаунт Garmin в приложении.",
        "widget.profileMissing": "Профиль удалён", "widget.profileMissingHint": "Выбери другой профиль в настройках виджета.",
        "widget.demo": "ДЕМО", "widget.connect": "Подключи Garmin в приложении",
        "dashboard.empty": "Выбери нужные показатели в настройках.", "dashboard.connect": "Подключить Garmin",
        "action.settings": "Настройки", "action.sync": "Обновить", "action.quit": "Выйти из Garmin Desk",
        "action.cancel": "Отмена", "action.save": "Сохранить", "action.delete": "Удалить", "action.duplicate": "Дублировать",
        "action.add": "Добавить профиль", "action.up": "Выше", "action.down": "Ниже", "action.show": "Показать",
        "action.hide": "Скрыть", "action.done": "Готово", "action.retry": "Повторить",
        "data.demo": "Демоданные", "data.updated": "Проверено", "data.stale": "Данные могли устареть",
        "data.day": "Данные за", "data.partial": "Часть измерений недоступна",
        "data.emptyDay": "Garmin пока не передал измерения за эту дату. Синхронизируй часы с Garmin Connect, чтобы обновить их.",
        "data.empty": "Пока нет измерения", "data.demoDetail": "Пример значений. Подключи аккаунт, чтобы увидеть свои измерения.",
        "data.local": "Сохранено на этом Mac", "data.source": "Последняя синхронизация Garmin Connect", "data.syncing": "Проверяем Garmin Connect…",
        "status.connected": "Garmin подключён", "status.notConnected": "Garmin не подключён", "status.connecting": "Подключение…",
        "settings.title": "Настройки", "settings.profiles": "Профили виджетов", "settings.connection": "Аккаунт Garmin", "settings.general": "Основные",
        "settings.profilesSubtitle": "Свой набор для каждой части дня.", "settings.generalSubtitle": "Настрой Garmin Desk под свой Mac.",
        "profile.name": "Название профиля", "profile.primary": "Главный показатель", "profile.metrics": "Показатели",
        "profile.metricsHint": "Выбери, что показывать. Главный показатель всегда будет первым.", "profile.appearance": "Оформление",
        "profile.style": "Стиль", "profile.density": "Плотность", "profile.preview": "Предпросмотр",
        "profile.added": "Новый профиль", "profile.new": "Новый профиль", "profile.default": "Мой день", "profile.copy": "Копия", "profile.untitled": "Без названия",
        "profile.deleteTitle": "Удалить этот профиль?", "profile.deleteMessage": "Профиль будет удалён. Данные Garmin останутся на этом Mac.",
        "profile.oneRequired": "Нужен хотя бы один профиль.", "profile.enabled": "В виджете", "profile.available": "Доступные показатели",
        "profile.count": "показателей", "profile.mainBadge": "Главный",
        "style.calm": "Спокойный", "style.sport": "Спортивный", "style.monochrome": "Монохромный",
        "density.comfortable": "Свободно", "density.compact": "Компактно",
        "connection.title": "Твой аккаунт Garmin", "connection.subtitle": "Mac подключается напрямую к Garmin Connect.",
        "connection.localTitle": "Данные остаются у тебя", "connection.localDetail": "Измерения хранятся на этом Mac, данные сессии — в Связке ключей macOS. Отдельного сервера у приложения нет.",
        "connection.email": "Электронная почта", "connection.password": "Пароль", "connection.china": "Использовать Garmin China",
        "connection.signIn": "Подключить аккаунт", "connection.disconnect": "Отключить и удалить локальные данные",
        "connection.disconnectTitle": "Отключить Garmin?", "connection.disconnectMessage": "Сохранённая сессия Garmin и загруженные измерения будут удалены с этого Mac. Настройки сохранятся.",
        "connection.demo": "Посмотреть демоданные", "connection.demoHint": "Примеры значений всегда помечены.",
        "connection.syncHint": "Синхронизируй часы с Garmin Connect, чтобы новые измерения появились здесь.",
        "connection.secureHint": "Пароль используется только для входа и не сохраняется приложением.",
        "connection.mfaTitle": "Код подтверждения", "connection.mfaHint": "Введи код, который запросил Garmin для завершения подключения.",
        "connection.mfaCode": "Код", "connection.verify": "Подтвердить", "connection.cancelLogin": "Отменить вход",
        "general.language": "Язык", "general.appearance": "Тема", "general.refresh": "Частота обновления",
        "general.system": "Как в системе", "general.light": "Светлая", "general.dark": "Тёмная",
        "general.minutes5": "Каждые 5 минут", "general.minutes15": "Каждые 15 минут", "general.minutes30": "Каждые 30 минут",
        "general.minutes60": "Каждый час", "general.refreshHint": "При обновлении загружаются последние измерения из Garmin Connect.",
        "general.localNotice": "Настройки автоматически сохраняются на этом Mac.",
        "general.launchAtLogin": "Открывать Garmin Desk при входе в систему",
        "general.backgroundHint": "После закрытия окна данные продолжают обновляться. Чтобы завершить приложение, выбери «Завершить Garmin Desk» или нажми ⌘Q.",
        "menu.about": "О программе Garmin Desk", "menu.hideApp": "Скрыть Garmin Desk", "menu.hideOthers": "Скрыть остальные", "menu.showAll": "Показать все",
        "menu.file": "Файл", "menu.closeWindow": "Закрыть окно", "menu.window": "Окно", "menu.mainWindow": "Garmin Desk",
        "menu.minimize": "Свернуть", "menu.zoom": "Масштабировать",
        "category.health": "Здоровье и восстановление", "category.sleep": "Сон", "category.activity": "Активность за день", "category.training": "Тренировки", "category.body": "Тело и вода",
        "metric.steps": "Шаги", "metric.stepGoal": "Цель по шагам", "metric.distance": "Расстояние", "metric.calories": "Всего калорий",
        "metric.activeCalories": "Активные калории", "metric.floors": "Этажи", "metric.intensityMinutes": "Минуты интенсивности",
        "metric.restingHeartRate": "Пульс в покое", "metric.heartRate": "Последний пульс", "metric.stress": "Средний стресс за день", "metric.bodyBattery": "Body Battery",
        "metric.sleepDuration": "Продолжительность сна", "metric.sleepScore": "Оценка сна", "metric.deepSleep": "Глубокий сон", "metric.remSleep": "Быстрый сон",
        "metric.lightSleep": "Лёгкий сон", "metric.awakeSleep": "Бодрствование", "metric.hrv": "Средняя ВСР за ночь", "metric.spo2": "Средний SpO₂ за день",
        "metric.respiration": "Среднее дыхание во сне", "metric.trainingReadiness": "Готовность к тренировке", "metric.recoveryTime": "Время восстановления",
        "metric.vo2Max": "VO₂ max в беге", "metric.trainingLoad": "Острая нагрузка", "metric.weight": "Вес", "metric.hydration": "Вода",
        "metric.short.sleepDuration": "Сон", "metric.short.stress": "Стресс · день",
        "metric.short.restingHeartRate": "Пульс · покой", "metric.short.trainingReadiness": "Готовность",
        "metric.short.hrv": "ВСР · ночь", "metric.short.respiration": "Дыхание · сон",
        "metric.short.intensityMinutes": "Интенсивность", "metric.short.activeCalories": "Активные ккал",
        "metric.short.recoveryTime": "Восстановление", "metric.short.trainingLoad": "Острая нагрузка",
        "metric.short.vo2Max": "VO₂ max · бег", "metric.short.calories": "Всего калорий",
        "unit.minutes": "мин", "unit.hours": "ч", "unit.km": "км", "unit.kg": "кг", "unit.ml": "мл", "unit.bpm": "уд/мин",
        "unit.kcal": "ккал", "unit.ms": "мс", "unit.breaths": "вд/мин", "unit.vo2": "мл/кг/мин",
        "error.auth": "Не удалось войти. Проверь данные и попробуй снова.", "error.rate_limit": "Garmin временно ограничил запросы. Попробуй позже.",
        "error.session_unsupported": "Приложение не может восстановить сохранённую сессию. Подключи аккаунт Garmin заново.",
        "error.access_denied": "Garmin запретил доступ к запрошенным данным.",
        "error.security_challenge": "Защитная проверка Garmin остановила подключение. Попробуй позже.",
        "error.network": "Не удалось подключиться к Garmin. Проверь интернет.", "error.dependency": "Компонент подключения Garmin недоступен. Переустанови последнюю версию Garmin Desk.",
        "error.unknown": "Не удалось выполнить запрос. Попробуй снова.", "error.timeout": "Garmin не ответил вовремя. Попробуй снова.",
        "error.keychain": "Нет доступа к Связке ключей macOS. Проверь, что она разблокирована.", "error.protocol": "Не удалось прочитать ответ Garmin. Попробуй позже.",
        "error.storage": "Не удалось сохранить данные на Mac. Проверь свободное место и права доступа.",
        "error.login_item": "Разреши автозапуск в настройках macOS → Основные → Объекты входа.",
        "training.title": "Тренировки",
        "training.last": "Последняя завершённая",
        "training.next": "Ближайшая по плану",
        "training.completed": "Выполнена",
        "training.planned": "По плану",
        "training.recent": "Последние занятия",
        "training.upcoming": "Расписание",
        "training.workout": "Тренировка",
        "training.dateUnknown": "Дата не указана",
        "training.timeUnknown": "Время не указано",
        "training.localTime": "местное время записи",
        "training.durationUnknown": "Длительность не указана",
        "training.pastUnavailable": "История пока недоступна",
        "training.pastUnavailableHint": "Для этого раздела ещё нет подтверждённой загрузки Garmin.",
        "training.pastEmpty": "В последней выборке нет занятий",
        "training.pastCoverage": "До 20 последних занятий · не вся история",
        "training.futureUnavailable": "Расписание пока недоступно",
        "training.futureUnavailableHint": "Недоступный календарь не означает, что тренировок нет.",
        "training.futureEmpty": "В загруженной части нет тренировок",
        "training.calendar": "Опубликованный календарь Garmin",
        "training.adaptive": "Проверенный адаптивный календарь",
        "training.partial": "Часть календаря недоступна",
        "training.expiredCoverage": "Проверенный период закончился",
        "training.refreshCalendar": "Обновите данные, чтобы увидеть новый период.",
        "training.updated": "Обновлено",
        "training.updatedUnknown": "Время обновления неизвестно",
        "training.cached": "Сохранённые данные",
        "training.refreshFailed": "Не удалось обновить раздел",
        "training.rateLimit": "Garmin временно ограничил запросы",
        "training.signIn": "Для обновления войдите в Garmin Connect",
        "training.hour": "ч",
        "training.minute": "мин",
        "training.second": "с",
        "training.km": "км",
        "training.sport.running": "Бег",
        "training.sport.trail_running": "Трейл",
        "training.sport.treadmill_running": "Беговая дорожка",
        "training.sport.track_running": "Бег на стадионе",
        "training.sport.cycling": "Велосипед",
        "training.sport.mountain_biking": "Велосипед по бездорожью",
        "training.sport.indoor_cycling": "Велотренировка в помещении",
        "training.sport.swimming": "Плавание",
        "training.sport.open_water_swimming": "Открытая вода",
        "training.sport.walking": "Ходьба",
        "training.sport.hiking": "Поход",
        "training.sport.strength_training": "Силовая тренировка",
        "training.sport.cardio_training": "Кардио",
        "training.sport.elliptical": "Эллипс",
        "training.sport.stair_climbing": "Подъём по лестнице",
        "training.sport.yoga": "Йога",
        "training.sport.pilates": "Пилатес",
        "training.sport.rowing": "Гребля",
        "training.sport.tennis": "Теннис",
        "training.sport.golf": "Гольф",
        "training.sport.alpine_skiing": "Горные лыжи",
        "training.sport.cross_country_skiing": "Беговые лыжи",
        "training.sport.snowboarding": "Сноуборд",
        "training.sport.triathlon": "Мультиспорт",
        "training.noPublishedThrough": "Нет опубликованных тренировок по %@",
        "training.checkedThrough": "проверено по %@",
    ]
}
