import Foundation

/// Metric explanations in pt-BR. Garmin payload codes are never translated here.
enum LocalizationExplanationPTBR {
    static let strings: [String: String] = [
        "explanation.load.rangeUnavailable": "Faixa pessoal indisponível",
        "explanation.load.ratio.low": "Relação de carga baixa",
        "explanation.load.ratio.optimal": "Relação de carga ideal",
        "explanation.load.ratio.high": "Relação de carga alta",
        "explanation.load.ratio.veryHigh": "Relação de carga muito alta",
        "explanation.load.ratio.value": "Aguda / crônica: %@",
        "explanation.load.below": "Abaixo da faixa ideal",
        "explanation.load.above": "Acima da faixa ideal",
        "explanation.load.optimal": "Dentro da faixa ideal",
        "explanation.load.range": "Sua faixa: %1$@–%2$@",
        "explanation.load.detail": "A carga aguda estima o esforço dos treinos recentes. A Garmin dá mais peso às sessões recentes e compara o resultado a uma faixa baseada no condicionamento e no histórico. O número sozinho não mostra se o treino é produtivo.",
        "explanation.load.ratio.detail": "A relação compara a carga aguda recente à carga crônica de longo prazo. A Garmin fornece essa categoria separadamente do status de treinamento.",
        "explanation.load.garminStatus": "Status Garmin: %@",
        "explanation.load.noStatusDetail": "O status de treinamento também considera mudanças no condicionamento e recuperação. Carga baixa sozinha não significa destreinamento. A Garmin não forneceu um status reconhecido para esta leitura.",
        "explanation.hrv.compare": "Compare com sua referência",
        "explanation.hrv.balanced": "VFC semanal equilibrada",
        "explanation.hrv.unbalanced": "VFC semanal desequilibrada",
        "explanation.hrv.low": "VFC semanal baixa",
        "explanation.hrv.poor": "Status de VFC ruim",
        "explanation.hrv.insufficient": "Dados recentes de VFC insuficientes",
        "explanation.hrv.weekly": "Média de 7 dias: %1$@ %2$@",
        "explanation.hrv.baseline": "Sua referência: %1$@–%2$@ %3$@",
        "explanation.hrv.detail": "O valor mostra a variação média entre batimentos da última noite. O status de VFC Garmin compara a média de 7 dias à sua referência pessoal, que leva cerca de três semanas de sono para ser estabelecida. Uma noite não é o status semanal; maior nem sempre é melhor.",
        "explanation.readiness.prime": "Prontidão ideal",
        "explanation.readiness.high": "Prontidão alta",
        "explanation.readiness.moderate": "Prontidão moderada",
        "explanation.readiness.low": "Prontidão baixa",
        "explanation.readiness.poor": "Prontidão muito baixa",
        "explanation.readiness.detail": "A Garmin combina sono, recuperação, VFC, carga aguda e estresse recente. Escala: 1–24 muito baixa, 25–49 baixa, 50–74 moderada, 75–94 alta, 95–100 ideal. Uma pontuação baixa sugere priorizar a recuperação; uma alta indica mais recursos para uma sessão exigente.",
        "explanation.sleep.excellent": "Sono excelente",
        "explanation.sleep.good": "Sono bom",
        "explanation.sleep.fair": "Sono razoável",
        "explanation.sleep.poor": "Sono ruim",
        "explanation.sleep.detail": "Resumo da qualidade do sono e da recuperação, considerando duração, estágios e agitação. Escala Garmin: abaixo de 60 ruim, 60–79 razoável, 80–89 bom, 90–100 excelente. A duração sozinha não determina a pontuação.",
        "explanation.stress.resting": "Faixa de repouso",
        "explanation.stress.low": "Estresse baixo",
        "explanation.stress.medium": "Estresse médio",
        "explanation.stress.high": "Estresse alto",
        "explanation.stress.detail": "Estresse fisiológico médio do dia segundo a Garmin, não uma leitura instantânea das emoções. A escala usa a variabilidade cardíaca: 0–25 repouso, 26–50 baixo, 51–75 médio, 76–100 alto. A média pode ocultar picos breves e períodos de descanso.",
        "explanation.battery.veryLow": "Reserva de energia muito baixa",
        "explanation.battery.low": "Reserva de energia baixa",
        "explanation.battery.moderate": "Reserva de energia moderada",
        "explanation.battery.high": "Reserva de energia alta",
        "explanation.battery.detail": "A Garmin estima a energia disponível com estresse, variabilidade cardíaca, sono e atividade. O descanso pode recarregá-la; estresse e atividade podem consumi-la. É uma estimativa de energia, não uma porcentagem do condicionamento físico.",
        "explanation.recovery.complete": "Contagem de recuperação concluída",
        "explanation.recovery.remaining": "Até o próximo treino intenso",
        "explanation.recovery.detail": "A Garmin estima o tempo até você estar pronto para outro treino intenso. Isso não exige inatividade total. Sono, estresse e atividades seguintes podem alterar a estimativa. O valor é a última leitura recebida da Garmin.",
        "explanation.vo2.status": "Estimativa do condicionamento aeróbico",
        "explanation.vo2.detail": "Consumo máximo estimado de oxigênio por quilograma por minuto. As categorias Garmin dependem de idade e sexo; o app não recebe dados suficientes do perfil para escolher uma. Compare sua evolução em condições semelhantes, em vez de um único número.",
        "explanation.restingHR.status": "Acompanhe sua própria evolução",
        "explanation.restingHR.detail": "Frequência cardíaca diária de repouso segundo a Garmin. Compare vários dias com seu nível habitual. Condicionamento, sono, estresse e recuperação influenciam; menor nem sempre é melhor.",
        "explanation.oxygen.status": "Estimativa média de oxigênio",
        "explanation.oxygen.detail": "Saturação de oxigênio no sangue estimada pelo relógio. Condições de medição e altitude afetam o resultado. Uma média diária não avalia a saúde nem mostra alterações noturnas breves.",
        "explanation.respiration.status": "Média durante o sono",
        "explanation.respiration.detail": "Média de respirações por minuto durante o sono. Compare suas noites e a tendência de longo prazo; não é sua frequência respiratória atual.",
        "explanation.sleepDuration.status": "Tempo total de sono",
        "explanation.sleepDuration.detail": "Tempo classificado pela Garmin como sono na noite registrada: leve, profundo e REM. Considere também a pontuação do sono e o quanto se sente descansado.",
        "explanation.sleepStage.awake": "Vigília no período de sono",
        "explanation.sleepStage.status": "Parte da noite registrada",
        "explanation.sleepStage.detail": "A Garmin estima os estágios do sono pelos sensores. A duração varia entre noites; um valor isolado não tem limite universal bom ou ruim. Considere o sono total, a pontuação e o padrão de várias noites.",
        "explanation.steps.status": "Caminhada diária",
        "explanation.steps.reached": "Meta diária atingida",
        "explanation.steps.progress": "Progresso para sua meta diária",
        "explanation.steps.goalDetail": "Passos comparados à sua meta diária pessoal da Garmin. A meta é um objetivo, não uma medida universal de condicionamento.",
        "explanation.steps.goal": "Meta: %@",
        "explanation.steps.detail": "Passos registrados neste dia. É preciso uma meta pessoal para avaliar o progresso.",
        "explanation.stepsTarget.status": "Sua meta diária Garmin",
        "explanation.stepsTarget.detail": "Meta de passos definida manualmente ou ajustada pela Garmin. É pessoal e pode mudar a cada dia.",
        "explanation.intensity.status": "Minutos de atividade ponderados",
        "explanation.intensity.detail": "A Garmin conta minutos moderados e dá peso dobrado aos intensos. O total diário pode superar a duração do treino; não é o total semanal.",
        "explanation.calories.status": "Energia em repouso + atividade",
        "explanation.calories.detail": "Gasto total estimado de energia do dia, incluindo metabolismo em repouso e atividade. É gasto, não ingestão de alimentos nem déficit calórico.",
        "explanation.activeCalories.status": "Energia da atividade",
        "explanation.activeCalories.detail": "Gasto estimado com atividade além das necessidades em repouso. Já está incluído nas calorias totais; os dois não devem ser somados.",
        "explanation.distance.status": "Distância percorrida no dia",
        "explanation.distance.detail": "Distância do resumo diário Garmin. É o total de atividade do dia, não necessariamente a distância do último treino.",
        "explanation.floors.status": "Andares subidos",
        "explanation.floors.detail": "Estimativa Garmin dos andares subidos durante o dia. Representa subida, não lances de escada descidos.",
        "explanation.weight.status": "Última medição registrada",
        "explanation.weight.detail": "Medição de peso mais recente disponível para este registro. Mudanças isoladas podem refletir líquidos corporais e horário de medição. O peso sozinho não determina condicionamento nem saúde.",
        "explanation.hydration.status": "Líquidos registrados",
        "explanation.hydration.detail": "Líquidos anotados no Garmin Connect. São seus registros, não uma medição de hidratação por sensor nem sua necessidade diária pessoal.",
        "explanation.training.DETRAINING.title": "Destreinamento",
        "explanation.training.DETRAINING.detail": "A Garmin detecta perda de condicionamento após uma redução prolongada nos treinos.",
        "explanation.training.RECOVERY.title": "Recuperação",
        "explanation.training.RECOVERY.detail": "Treinos mais leves permitem a recuperação de esforços exigentes.",
        "explanation.training.MAINTAINING.title": "Manutenção",
        "explanation.training.MAINTAINING.detail": "O treino atual mantém o condicionamento sem melhora clara.",
        "explanation.training.PRODUCTIVE.title": "Produtivo",
        "explanation.training.PRODUCTIVE.detail": "A Garmin detecta melhora do condicionamento com os treinos atuais.",
        "explanation.training.PEAKING.title": "Pico de forma",
        "explanation.training.PEAKING.detail": "A carga reduzida favoreceu a recuperação e um pico breve de desempenho.",
        "explanation.training.OVERREACHING.title": "Excesso de esforço",
        "explanation.training.OVERREACHING.detail": "O treino supera a capacidade de recuperação e limita o progresso.",
        "explanation.training.UNPRODUCTIVE.title": "Não produtivo",
        "explanation.training.UNPRODUCTIVE.detail": "O condicionamento cai apesar da carga adequada; sono, alimentação e estresse também importam.",
        "explanation.training.STRAINED.title": "Sobrecarga",
        "explanation.training.STRAINED.detail": "A Garmin detecta desequilíbrio entre treino e recuperação.",
        "explanation.training.NO_STATUS.title": "Sem status",
        "explanation.training.NO_STATUS.detail": "A Garmin ainda não reuniu dados de treino suficientes e adequados.",
        "explanation.training.PAUSED.title": "Pausado",
        "explanation.training.PAUSED.detail": "A avaliação do status de treinamento está pausada na Garmin.",
        "explanation.help": "O que esta medida significa",
        "explanation.source": "Saiba mais com a Garmin",
        "explanation.forecast": "Estimativa linear da última tendência Garmin. %@",
        "explanation.labeledDetail": "%1$@: %2$@",
    ]
}
