// Full application and widget catalog. Keep keys aligned with the English catalog.
enum LocalizationPTBR {
    static let strings: [String: String] = [
        "widget.summary.minimum": "Mantenha pelo menos uma medição selecionada.",
        "widget.summary.hint": "Apenas as medições selecionadas com dados disponíveis são exibidas. A quantidade depende do tamanho do widget.",
        "widget.summary.primary": "Medição principal preferida",
        "widget.summary.choose": "Escolher medições",
        "settings.widgets": "Widgets",
        "settings.widgetsSubtitle": "Cinco widgets prontos para a sua mesa.",
        "widget.type": "Tipo de widget",
        "widget.appearance": "Aparência dos widgets",
        "widget.appearance.colorful": "Colorida",
        "widget.appearance.light": "Clara",
        "widget.appearance.dark": "Escura",
        "widget.appearanceHint": "Uma aparência para os cinco widgets da mesa.",
        "widget.automaticHint": "As medições disponíveis são selecionadas automaticamente.",
        "widget.guide.fixedTypes": "Escolha o tipo e o tamanho do widget e adicione-o à mesa.",
        "widget.slot.day": "Dia",
        "widget.slot.day.description": "Body Battery, passos, estresse e atividade diária.",
        "onboarding.title": "Seus dados Garmin no Mac",
        "onboarding.privacy": "Suas medições ficam armazenadas neste Mac",
        "onboarding.detail": "Conecte sua conta Garmin para ver suas medições aqui e nos widgets da mesa.",
        "data.available": "Medições mais recentes",
        "data.nightEnding": "Noite encerrada em",
        "data.measured": "Medido",
        "data.received": "Recebido",
        "metric.short.spo2": "SpO₂ · média diária",
        "data.waiting": "Aguardando dados do relógio",
        "data.waitingNew": "Aguardando novas medições",
        "data.unchanged": "Nenhuma alteração nas medições",
        "data.checkFailed": "Não foi possível atualizar os dados Garmin",
        "data.unchangedHint": "Esperava medições mais recentes? Abra o Garmin Connect no celular e sincronize o relógio. Elas serão recebidas automaticamente.",
        "data.retainedAllHint": "As últimas medições aparecem abaixo com suas datas. Abra o Garmin Connect no celular e sincronize o relógio para obter medições mais recentes.",
        "data.previous": "Últimos disponíveis",
        "data.retainedHint": "Algumas medições ainda não chegaram. Mantivemos os últimos valores com suas datas. Sincronize o relógio no Garmin Connect pelo celular.",
        "data.waitingHint": "Abra o Garmin Connect no celular e sincronize o relógio. Suas medições aparecerão aqui automaticamente.",
        "widget.notice.connection": "Reconectar Garmin",
        "widget.notice.unavailable": "Não foi possível atualizar",
        "widget.notice.waiting": "Aguardando novos dados",
        "widget.waiting": "Aguardando dados",
        "widget.waitingHint": "Sincronize o relógio no Garmin Connect pelo celular. Suas medições aparecerão aqui automaticamente.",
        "widget.previous": "Últimos disponíveis",
        "widget.slot.overview.description": "Suas medições selecionadas em um único widget.",
        "widget.slot.sport.description": "Prontidão para treinar, recuperação, carga e VO₂ máximo.",
        "widget.slot.sleep.description": "Duração e pontuação do sono, VFC noturna.",
        "widget.slot.training.description": "Um calendário de atividades concluídas e treinos programados.",
        "widget.preview.easyRun": "Corrida leve",
        "widget.preview.intervals": "Corrida intervalada",
        "profile.availableMetrics": "Usar medições disponíveis",
        "profile.availableMetricsHint": "Ignora as medições ausentes e preenche o widget com métricas relacionadas. Desative para manter sua seleção exata.",
        "profile.content": "Conteúdo",
        "content.metrics": "Métricas",
        "content.training": "Calendário de treinos",
        "content.mixed": "Ambos",
        "profile.previewMetricsOnly": "Esta prévia mostra as métricas. Seus cartões de treino também aparecem na seção Visão geral.",
        "status.signInRequired": "É necessário entrar",
        "connection.retryAfter": "Tente novamente após",
        "connection.reconnectDetail": "Abra a janela Garmin e conclua o login para retomar as atualizações.",
        "widget.guide.staticProfile": "Escolha o tipo e o tamanho do widget e adicione-o à mesa.",
        "widget.guide.unavailable": "Veja suas medições e as prévias dos widgets no app.",
        "widget.sharingDataUnavailable": "Os dados dos widgets ainda não estão disponíveis. Você pode continuar vendo suas medições no app.",
        "widget.slot.overview": "Resumo",
        "widget.slot.sport": "Esporte",
        "widget.slot.sleep": "Sono",
        "widget.slot.training": "Calendário de treinos",
        "widget.slot.firstProfile": "Primeiro perfil",
        "widget.slot.unassigned": "Escolher um perfil…",
        "profile.templates": "Começar com um modelo",
        "profile.custom": "Perfil personalizado",
        "profile.template.life": "Dia a dia",
        "profile.template.sport": "Esporte",
        "profile.template.sleep": "Sono",
        "profile.previewSize": "Tamanho do widget",
        "profile.preview.small": "Pequeno",
        "profile.preview.medium": "Médio",
        "profile.preview.large": "Grande",
        "profile.previewCount": "Exibe %d de %d métricas. Todas as métricas selecionadas estão disponíveis na seção Visão geral.",
        "widget.galleryTitle": "Resumo Garmin",
        "widget.galleryDescription": "Saúde, sono, atividade e treinamento em cinco widgets prontos para usar.",
        "widget.galleryStaticDescription": "Escolha o tipo e o tamanho do widget. As medições disponíveis aparecem automaticamente.",
        "connection.webTitle": "Conectar Garmin",
        "connection.webSubtitle": "Conecte uma vez. Suas medições são atualizadas automaticamente.",
        "connection.webIntro": "Entrar no Garmin Connect",
        "connection.webDetail": "Uma janela segura do Garmin será aberta. Conclua o login e as verificações solicitadas pelo Garmin. O app manterá essa conexão no Mac.",
        "connection.webSignIn": "Entrar com Garmin",
        "connection.webPrivacy": "As medições e a sessão do site Garmin ficam neste Mac. Sua senha vai diretamente para o Garmin. Não há servidor separado nem análise de uso.",
        "connection.automaticHint": "Seus dados são atualizados em segundo plano, inclusive quando o Mac sai do repouso. Mantenha o Garmin Desk em execução para as atualizações automáticas.",
        "connection.reconnect": "Reconectar Garmin",
        "connection.nextSync": "Próxima atualização após",
        "error.partial": "Não foi possível atualizar algumas medições. Os dados salvos continuam disponíveis.",
        "diagnostic.title": "Detalhes da conexão",
        "diagnostic.stage": "Etapa",
        "diagnostic.apiCode": "Código Garmin",
        "diagnostic.requests": "Respostas recebidas",
        "menu.edit": "Editar",
        "menu.cut": "Recortar",
        "menu.copy": "Copiar",
        "menu.paste": "Colar",
        "menu.selectAll": "Selecionar Tudo",
        "app.subtitle": "Seu dia em um olhar",
        "app.device": "Garmin fēnix 8",
        "dashboard.title": "Visão geral",
        "dashboard.profile": "Perfil",
        "dashboard.moreMetrics": "Widgets maiores podem mostrar mais métricas",
        "dashboard.configure": "Ajustes dos widgets",
        "widget.setup": "Configurar widgets da mesa",
        "widget.customize": "Ajustes dos widgets",
        "widget.guide.add": "Clique com o botão direito na mesa e escolha Editar Widgets. Encontre GarminDesk na galeria.",
        "widget.guide.profile": "Escolha o tipo e o tamanho do widget e adicione-o à mesa.",
        "widget.guide.refresh": "O Garmin Desk busca suas medições. O macOS decide quando o widget da mesa é atualizado.",
        "widget.sharingUnavailable": "Os widgets de mesa não estão disponíveis nesta versão. Você ainda pode ver suas medições no app.",
        "widget.openApp": "Abrir GarminDesk",
        "widget.openAppHint": "Conecte sua conta Garmin no app.",
        "widget.profileMissing": "Perfil removido",
        "widget.profileMissingHint": "Escolha outro perfil nos ajustes deste widget.",
        "widget.demo": "DEMO",
        "widget.connect": "Conecte Garmin no app",
        "dashboard.empty": "Escolha as métricas que deseja ver nos ajustes.",
        "dashboard.connect": "Conectar Garmin",
        "action.settings": "Ajustes",
        "action.sync": "Atualizar",
        "action.quit": "Encerrar Garmin Desk",
        "action.cancel": "Cancelar",
        "action.save": "Salvar",
        "action.delete": "Apagar",
        "action.duplicate": "Duplicar",
        "action.add": "Adicionar perfil",
        "action.up": "Mover para cima",
        "action.down": "Mover para baixo",
        "action.show": "Mostrar",
        "action.hide": "Ocultar",
        "action.done": "OK",
        "action.retry": "Tentar novamente",
        "data.demo": "Dados de demonstração",
        "data.updated": "Verificado",
        "data.stale": "Os dados podem estar desatualizados",
        "data.day": "Dados de",
        "data.partial": "Algumas medições estão indisponíveis",
        "data.emptyDay": "O Garmin ainda não tem medições para esta data. Sincronize o relógio com o Garmin Connect para atualizá-las.",
        "data.empty": "Ainda não há medições",
        "data.demoDetail": "Valores de exemplo. Conecte sua conta para ver suas medições.",
        "data.local": "Armazenado neste Mac",
        "data.source": "Última sincronização do Garmin Connect",
        "data.syncing": "Verificando Garmin Connect…",
        "status.connected": "Garmin conectado",
        "status.notConnected": "Garmin não conectado",
        "status.connecting": "Conectando…",
        "settings.title": "Ajustes",
        "settings.profiles": "Perfis de widgets",
        "settings.connection": "Conta Garmin",
        "settings.general": "Geral",
        "settings.profilesSubtitle": "Crie uma visualização para cada momento do dia.",
        "settings.generalSubtitle": "Deixe o Garmin Desk do seu jeito no Mac.",
        "profile.name": "Nome do perfil",
        "profile.primary": "Métrica principal",
        "profile.metrics": "Métricas",
        "profile.metricsHint": "Escolha o que mostrar. A métrica principal sempre aparece primeiro.",
        "profile.appearance": "Aparência",
        "profile.style": "Estilo",
        "profile.density": "Densidade",
        "profile.preview": "Prévia",
        "profile.added": "Novo perfil",
        "profile.new": "Novo perfil",
        "profile.default": "Meu dia",
        "profile.copy": "Cópia",
        "profile.untitled": "Perfil sem título",
        "profile.deleteTitle": "Apagar este perfil?",
        "profile.deleteMessage": "O perfil será removido. Seus dados Garmin permanecerão neste Mac.",
        "profile.oneRequired": "Mantenha pelo menos um perfil.",
        "profile.enabled": "Incluídas",
        "profile.available": "Métricas disponíveis",
        "profile.count": "métricas",
        "profile.mainBadge": "Principal",
        "style.calm": "Suave",
        "style.sport": "Esportivo",
        "style.monochrome": "Monocromático",
        "density.comfortable": "Confortável",
        "density.compact": "Compacta",
        "connection.title": "Sua conta Garmin",
        "connection.subtitle": "Seu Mac se conecta diretamente ao Garmin Connect.",
        "connection.localTitle": "Seus dados ficam com você",
        "connection.localDetail": "As medições são armazenadas no cache deste Mac. As credenciais de sessão ficam nas Chaves do macOS. O app não tem servidor separado.",
        "connection.email": "E-mail",
        "connection.password": "Senha",
        "connection.china": "Usar Garmin China",
        "connection.signIn": "Conectar conta",
        "connection.disconnect": "Desconectar e apagar dados locais",
        "connection.disconnectTitle": "Desconectar Garmin?",
        "connection.disconnectMessage": "A sessão Garmin salva e as medições em cache serão removidas deste Mac. Suas preferências serão mantidas.",
        "connection.demo": "Explorar com dados de demonstração",
        "connection.demoHint": "Os valores de demonstração sempre são identificados.",
        "connection.syncHint": "Sincronize o relógio com o Garmin Connect para disponibilizar novas medições aqui.",
        "connection.secureHint": "Sua senha é usada apenas para entrar e não é salva por este app.",
        "connection.mfaTitle": "Código de verificação",
        "connection.mfaHint": "Digite o código solicitado pelo Garmin para concluir a conexão.",
        "connection.mfaCode": "Código",
        "connection.verify": "Verificar",
        "connection.cancelLogin": "Cancelar login",
        "general.language": "Idioma",
        "general.appearance": "Aparência",
        "general.refresh": "Intervalo de atualização",
        "general.system": "Seguir o sistema",
        "general.light": "Clara",
        "general.dark": "Escura",
        "general.minutes5": "A cada 5 minutos",
        "general.minutes15": "A cada 15 minutos",
        "general.minutes30": "A cada 30 minutos",
        "general.minutes60": "A cada hora",
        "general.refreshHint": "As atualizações usam as medições mais recentes disponíveis no Garmin Connect.",
        "general.localNotice": "Suas preferências são salvas automaticamente neste Mac.",
        "general.launchAtLogin": "Abrir Garmin Desk ao iniciar sessão",
        "general.backgroundHint": "As atualizações automáticas continuam ao fechar a janela. Escolha “Encerrar Garmin Desk” ou pressione ⌘Q para encerrar o app.",
        "menu.about": "Sobre Garmin Desk",
        "menu.hideApp": "Ocultar Garmin Desk",
        "menu.hideOthers": "Ocultar Outros",
        "menu.showAll": "Mostrar Tudo",
        "menu.file": "Arquivo",
        "menu.closeWindow": "Fechar Janela",
        "menu.window": "Janela",
        "menu.mainWindow": "Garmin Desk",
        "menu.minimize": "Minimizar",
        "menu.zoom": "Zoom",
        "category.health": "Saúde e recuperação",
        "category.sleep": "Sono",
        "category.activity": "Atividade diária",
        "category.training": "Treinamento",
        "category.body": "Corpo e hidratação",
        "metric.steps": "Passos",
        "metric.stepGoal": "Meta de passos",
        "metric.distance": "Distância",
        "metric.calories": "Calorias totais",
        "metric.activeCalories": "Calorias ativas",
        "metric.floors": "Andares subidos",
        "metric.intensityMinutes": "Minutos de intensidade",
        "metric.restingHeartRate": "Frequência cardíaca em repouso",
        "metric.heartRate": "Última frequência cardíaca",
        "metric.stress": "Estresse médio diário",
        "metric.bodyBattery": "Body Battery",
        "metric.sleepDuration": "Duração do sono",
        "metric.sleepScore": "Pontuação do sono",
        "metric.deepSleep": "Sono profundo",
        "metric.remSleep": "Sono REM",
        "metric.lightSleep": "Sono leve",
        "metric.awakeSleep": "Tempo acordado",
        "metric.hrv": "VFC noturna",
        "metric.spo2": "SpO₂ média diária",
        "metric.respiration": "Respiração média durante o sono",
        "metric.trainingReadiness": "Prontidão para treinar",
        "metric.recoveryTime": "Tempo de recuperação",
        "metric.vo2Max": "VO₂ máx. de corrida",
        "metric.trainingLoad": "Carga aguda de treinamento",
        "metric.weight": "Peso",
        "metric.hydration": "Hidratação",
        "metric.short.sleepDuration": "Sono",
        "metric.short.stress": "Estresse · dia",
        "metric.short.restingHeartRate": "FC em repouso",
        "metric.short.trainingReadiness": "Prontidão",
        "metric.short.hrv": "VFC · noite",
        "metric.short.respiration": "Respir. · sono",
        "metric.short.intensityMinutes": "Min. de intensidade",
        "metric.short.activeCalories": "Calorias ativas",
        "metric.short.recoveryTime": "Recuperação",
        "metric.short.trainingLoad": "Carga aguda",
        "metric.short.vo2Max": "VO₂ máx. corrida",
        "metric.short.calories": "Calorias totais",
        "unit.minutes": "min",
        "unit.hours": "h",
        "unit.km": "km",
        "unit.kg": "kg",
        "unit.ml": "ml",
        "unit.bpm": "bpm",
        "unit.kcal": "kcal",
        "unit.ms": "ms",
        "unit.breaths": "resp/min",
        "unit.vo2": "ml/kg/min",
        "error.auth": "Não foi possível entrar. Confira seus dados e tente novamente.",
        "error.rate_limit": "O Garmin limitou temporariamente as solicitações. Tente novamente mais tarde.",
        "error.session_unsupported": "Este app não pode restaurar a sessão salva. Reconecte sua conta Garmin.",
        "error.access_denied": "O Garmin negou acesso aos dados solicitados.",
        "error.security_challenge": "Uma verificação de segurança do Garmin bloqueou a conexão. Tente novamente mais tarde.",
        "error.network": "Não foi possível acessar o Garmin. Confira sua conexão com a internet.",
        "error.dependency": "O componente de conexão Garmin está indisponível. Reinstale a versão mais recente do Garmin Desk.",
        "error.unknown": "Não foi possível concluir a solicitação. Tente novamente.",
        "error.timeout": "O Garmin demorou muito para responder. Tente novamente.",
        "error.keychain": "Não foi possível acessar as Chaves do macOS. Confira se estão desbloqueadas.",
        "error.protocol": "O Garmin retornou dados que o app não conseguiu ler. Tente novamente mais tarde.",
        "error.storage": "Não foi possível salvar os dados neste Mac. Confira o espaço disponível e as permissões.",
        "error.login_item": "Permita que o Garmin Desk abra ao iniciar sessão em Ajustes do macOS → Geral → Itens de Início.",
        "training.title": "Treinamento",
        "training.last": "Último concluído",
        "training.next": "Próximo planejado",
        "training.completed": "Concluído",
        "training.planned": "Agendado",
        "training.recent": "Atividades recentes",
        "training.upcoming": "Próximos treinos",
        "training.workout": "Treino",
        "training.dateUnknown": "Data não informada",
        "training.timeUnknown": "Horário não informado",
        "training.localTime": "horário local registrado",
        "training.durationUnknown": "Duração não informada",
        "training.pastUnavailable": "O histórico ainda não está disponível",
        "training.pastUnavailableHint": "Esta seção ainda não foi obtida do Garmin com sucesso.",
        "training.pastEmpty": "Nenhuma atividade na última resposta",
        "training.pastCoverage": "Até 20 atividades recentes · histórico parcial",
        "training.futureUnavailable": "A programação ainda não está disponível",
        "training.futureUnavailableHint": "Um calendário indisponível não significa que não haja treinos.",
        "training.futureEmpty": "Nenhum treino na parte obtida",
        "training.calendar": "Calendário Garmin publicado",
        "training.adaptive": "Calendário adaptativo verificado",
        "training.partial": "Parte do calendário está indisponível",
        "training.expiredCoverage": "O período verificado terminou",
        "training.refreshCalendar": "Atualize para verificar um novo período.",
        "training.updated": "Atualizado",
        "training.updatedUnknown": "Horário de atualização desconhecido",
        "training.cached": "Dados salvos",
        "training.refreshFailed": "Não foi possível atualizar esta seção",
        "training.rateLimit": "O Garmin está limitando temporariamente as solicitações",
        "training.signIn": "Entre no Garmin Connect para atualizar",
        "training.hour": "h",
        "training.minute": "min",
        "training.second": "s",
        "training.km": "km",
        "training.sport.running": "Corrida",
        "training.sport.trail_running": "Corrida em trilha",
        "training.sport.treadmill_running": "Corrida na esteira",
        "training.sport.track_running": "Corrida em pista",
        "training.sport.cycling": "Ciclismo",
        "training.sport.mountain_biking": "Mountain bike",
        "training.sport.indoor_cycling": "Ciclismo indoor",
        "training.sport.swimming": "Natação",
        "training.sport.open_water_swimming": "Natação em águas abertas",
        "training.sport.walking": "Caminhada",
        "training.sport.hiking": "Trilha",
        "training.sport.strength_training": "Treino de força",
        "training.sport.cardio_training": "Cardio",
        "training.sport.elliptical": "Elíptico",
        "training.sport.stair_climbing": "Subida de escadas",
        "training.sport.yoga": "Yoga",
        "training.sport.pilates": "Pilates",
        "training.sport.rowing": "Remo",
        "training.sport.tennis": "Tênis",
        "training.sport.golf": "Golfe",
        "training.sport.alpine_skiing": "Esqui alpino",
        "training.sport.cross_country_skiing": "Esqui cross-country",
        "training.sport.snowboarding": "Snowboard",
        "training.sport.triathlon": "Multiesporte",
        "training.noPublishedThrough": "Nenhum treino publicado até %@",
        "training.checkedThrough": "verificado até %@",
    ]
}
