import Foundation

/// Metric explanations in pl. Garmin payload codes are never translated here.
enum LocalizationExplanationPL {
    static let strings: [String: String] = [
        "explanation.load.rangeUnavailable": "Brak osobistego zakresu",
        "explanation.load.ratio.low": "Niski stosunek obciążeń",
        "explanation.load.ratio.optimal": "Optymalny stosunek obciążeń",
        "explanation.load.ratio.high": "Wysoki stosunek obciążeń",
        "explanation.load.ratio.veryHigh": "Bardzo wysoki stosunek obciążeń",
        "explanation.load.ratio.value": "Krótkotrwałe / długotrwałe: %@",
        "explanation.load.below": "Poniżej optymalnego zakresu",
        "explanation.load.above": "Powyżej optymalnego zakresu",
        "explanation.load.optimal": "W optymalnym zakresie",
        "explanation.load.range": "Twój zakres: %1$@–%2$@",
        "explanation.load.detail": "Obciążenie krótkotrwałe szacuje wysiłek z ostatnich treningów. Garmin mocniej uwzględnia nowsze sesje i porównuje wynik z zakresem opartym na kondycji i historii treningów. Sama liczba nie określa produktywności treningu.",
        "explanation.load.ratio.detail": "Współczynnik porównuje ostatnie obciążenie krótkotrwałe z obciążeniem długotrwałym. Garmin podaje tę kategorię oddzielnie od stanu wytrenowania.",
        "explanation.load.garminStatus": "Stan Garmin: %@",
        "explanation.load.noStatusDetail": "Stan wytrenowania uwzględnia też zmiany kondycji i regenerację. Samo niskie obciążenie nie oznacza roztrenowania. Garmin nie podał rozpoznanego stanu dla tego odczytu.",
        "explanation.hrv.compare": "Porównaj ze swoją normą",
        "explanation.hrv.balanced": "Zrównoważona tygodniowa HRV",
        "explanation.hrv.unbalanced": "Niezrównoważona tygodniowa HRV",
        "explanation.hrv.low": "Niska tygodniowa HRV",
        "explanation.hrv.poor": "Słaby stan HRV",
        "explanation.hrv.insufficient": "Za mało najnowszych danych HRV",
        "explanation.hrv.weekly": "Średnia z 7 dni: %1$@ %2$@",
        "explanation.hrv.baseline": "Twoja norma: %1$@–%2$@ %3$@",
        "explanation.hrv.detail": "Wartość oznacza średnią zmienność odstępów między uderzeniami serca ostatniej nocy. Stan HRV Garmin porównuje średnią z 7 dni z osobistą normą, do której potrzeba około trzech tygodni danych snu. Jedna noc to nie stan tygodniowy; więcej nie zawsze znaczy lepiej.",
        "explanation.readiness.prime": "Najwyższa gotowość",
        "explanation.readiness.high": "Wysoka gotowość",
        "explanation.readiness.moderate": "Umiarkowana gotowość",
        "explanation.readiness.low": "Niska gotowość",
        "explanation.readiness.poor": "Bardzo niska gotowość",
        "explanation.readiness.detail": "Garmin łączy sen, czas regeneracji, HRV, obciążenie krótkotrwałe i ostatni stres. Skala: 1–24 bardzo niska, 25–49 niska, 50–74 umiarkowana, 75–94 wysoka, 95–100 najwyższa. Niski wynik wskazuje na potrzebę regeneracji, wysoki na większe zasoby do wymagającego treningu.",
        "explanation.sleep.excellent": "Doskonały sen",
        "explanation.sleep.good": "Dobry sen",
        "explanation.sleep.fair": "Przeciętny sen",
        "explanation.sleep.poor": "Słaby sen",
        "explanation.sleep.detail": "Ocena jakości snu i regeneracji z uwzględnieniem czasu, faz i niepokoju. Skala Garmin: poniżej 60 słabo, 60–79 przeciętnie, 80–89 dobrze, 90–100 doskonale. Sam czas snu nie określa wyniku.",
        "explanation.stress.resting": "Zakres odpoczynku",
        "explanation.stress.low": "Niski stres",
        "explanation.stress.medium": "Średni stres",
        "explanation.stress.high": "Wysoki stres",
        "explanation.stress.detail": "Średni stres fizjologiczny z dnia według Garmin, nie bieżący odczyt emocji. Skala opiera się na zmienności tętna: 0–25 odpoczynek, 26–50 niski, 51–75 średni, 76–100 wysoki. Średnia może ukrywać krótkie skoki i okresy odpoczynku.",
        "explanation.battery.veryLow": "Bardzo mały zapas energii",
        "explanation.battery.low": "Mały zapas energii",
        "explanation.battery.moderate": "Umiarkowany zapas energii",
        "explanation.battery.high": "Duży zapas energii",
        "explanation.battery.detail": "Garmin szacuje dostępną energię na podstawie stresu, zmienności tętna, snu i aktywności. Odpoczynek może ją uzupełniać, a stres i aktywność zużywać. To ocena energii, nie procent sprawności fizycznej.",
        "explanation.recovery.complete": "Odliczanie regeneracji zakończone",
        "explanation.recovery.remaining": "Do kolejnego ciężkiego treningu",
        "explanation.recovery.detail": "Garmin szacuje czas do gotowości na kolejny ciężki trening. Nie wymaga to pełnej bezczynności. Sen, stres i dalsza aktywność mogą zmienić ocenę. Pokazano ostatni odczyt Garmin.",
        "explanation.vo2.status": "Ocena wydolności tlenowej",
        "explanation.vo2.detail": "Szacowane maksymalne zużycie tlenu na kilogram na minutę. Kategorie Garmin zależą od wieku i płci; aplikacja nie otrzymuje dość danych profilu, by wybrać kategorię. Porównuj zmiany w podobnych warunkach, a nie pojedynczą liczbę.",
        "explanation.restingHR.status": "Obserwuj własne zmiany",
        "explanation.restingHR.detail": "Dzienne tętno spoczynkowe według Garmin. Porównuj kilka dni ze swoim typowym poziomem. Kondycja, sen, stres i regeneracja mają wpływ; niżej nie zawsze znaczy lepiej.",
        "explanation.oxygen.status": "Średnia ocena natlenienia",
        "explanation.oxygen.detail": "Nasycenie krwi tlenem szacowane przez zegarek. Warunki pomiaru i wysokość wpływają na wynik. Jedna średnia dobowa nie ocenia zdrowia ani nie pokazuje krótkich zmian w nocy.",
        "explanation.respiration.status": "Średnia podczas snu",
        "explanation.respiration.detail": "Średnia liczba oddechów na minutę podczas snu. Porównuj swoje noce i dłuższy trend; to nie bieżąca częstość oddychania.",
        "explanation.sleepDuration.status": "Łączny czas snu",
        "explanation.sleepDuration.detail": "Czas zaklasyfikowany przez Garmin jako sen w zapisanej nocy: lekki, głęboki i REM. Oprócz czasu uwzględnij ocenę snu i poczucie wypoczęcia.",
        "explanation.sleepStage.awake": "Czuwanie w okresie snu",
        "explanation.sleepStage.status": "Część zapisanej nocy",
        "explanation.sleepStage.detail": "Garmin szacuje fazy snu z danych czujników. Czas faz różni się między nocami; pojedynczy wynik nie ma uniwersalnego dobrego ani złego progu. Uwzględnij cały sen, jego ocenę i przebieg kilku nocy.",
        "explanation.steps.status": "Dzienne chodzenie",
        "explanation.steps.reached": "Cel dzienny osiągnięty",
        "explanation.steps.progress": "Postęp do celu dziennego",
        "explanation.steps.goalDetail": "Kroki w porównaniu z osobistym celem dziennym Garmin. Cel to punkt odniesienia, nie uniwersalna miara kondycji.",
        "explanation.steps.goal": "Cel: %@",
        "explanation.steps.detail": "Kroki zapisane dla tego dnia. Do oceny postępu potrzebny jest osobisty cel kroków.",
        "explanation.stepsTarget.status": "Twój dzienny cel Garmin",
        "explanation.stepsTarget.detail": "Cel kroków ustawiony ręcznie lub dostosowany przez Garmin. Jest osobisty i może zmieniać się codziennie.",
        "explanation.intensity.status": "Ważone minuty aktywności",
        "explanation.intensity.detail": "Garmin liczy minuty umiarkowanej aktywności, a intensywne podwójnie. Wynik dzienny może przekroczyć czas treningu; to nie suma tygodniowa.",
        "explanation.calories.status": "Energia spoczynkowa + aktywna",
        "explanation.calories.detail": "Szacowany całkowity wydatek energii w ciągu dnia, w tym metabolizm spoczynkowy i aktywność. To wydatek, nie spożyte jedzenie ani deficyt kalorii.",
        "explanation.activeCalories.status": "Energia z aktywności",
        "explanation.activeCalories.detail": "Szacowany wydatek energii z aktywności ponad potrzeby spoczynkowe. Już zawiera się w kaloriach całkowitych, więc nie należy ich dodawać.",
        "explanation.distance.status": "Dystans pokonany w ciągu dnia",
        "explanation.distance.detail": "Dystans z dziennego podsumowania Garmin. To suma aktywności dnia, niekoniecznie dystans ostatniego treningu.",
        "explanation.floors.status": "Pokonane piętra w górę",
        "explanation.floors.detail": "Szacowana przez Garmin liczba pięter pokonanych w górę w ciągu dnia. Dotyczy wchodzenia, nie schodzenia.",
        "explanation.weight.status": "Ostatni zapisany pomiar",
        "explanation.weight.detail": "Najnowszy dostępny pomiar masy ciała dla tego zapisu. Pojedyncze zmiany mogą zależeć od płynów i pory pomiaru. Sama masa nie określa kondycji ani zdrowia.",
        "explanation.hydration.status": "Zapisane spożycie płynów",
        "explanation.hydration.detail": "Płyny zapisane w Garmin Connect. To Twoje wpisy, nie pomiar nawodnienia czujnikiem ani osobiste dzienne zapotrzebowanie.",
        "explanation.training.DETRAINING.title": "Roztrenowanie",
        "explanation.training.DETRAINING.detail": "Garmin wykrywa spadek kondycji po dłuższym ograniczeniu treningów.",
        "explanation.training.RECOVERY.title": "Regeneracja",
        "explanation.training.RECOVERY.detail": "Lżejsze treningi pozwalają zregenerować się po wymagającym wysiłku.",
        "explanation.training.MAINTAINING.title": "Utrzymanie",
        "explanation.training.MAINTAINING.detail": "Obecne treningi utrzymują kondycję bez wyraźnej poprawy.",
        "explanation.training.PRODUCTIVE.title": "Produktywny",
        "explanation.training.PRODUCTIVE.detail": "Garmin wykrywa poprawę kondycji dzięki obecnym treningom.",
        "explanation.training.PEAKING.title": "Szczytowa forma",
        "explanation.training.PEAKING.detail": "Mniejsze obciążenie wspomogło regenerację i krótkotrwały szczyt formy.",
        "explanation.training.OVERREACHING.title": "Nadmierny wysiłek",
        "explanation.training.OVERREACHING.detail": "Trening przekracza zdolność regeneracji i ogranicza postępy.",
        "explanation.training.UNPRODUCTIVE.title": "Nieproduktywny",
        "explanation.training.UNPRODUCTIVE.detail": "Kondycja spada mimo odpowiedniego obciążenia; ważne są też sen, odżywianie i stres.",
        "explanation.training.STRAINED.title": "Przeciążenie",
        "explanation.training.STRAINED.detail": "Garmin wykrywa brak równowagi między treningiem a regeneracją.",
        "explanation.training.NO_STATUS.title": "Brak stanu",
        "explanation.training.NO_STATUS.detail": "Garmin nie zebrał jeszcze dość odpowiednich danych treningowych.",
        "explanation.training.PAUSED.title": "Wstrzymany",
        "explanation.training.PAUSED.detail": "Ocena stanu wytrenowania jest wstrzymana w Garmin.",
        "explanation.help": "Co oznacza ten pomiar",
        "explanation.source": "Więcej informacji od Garmin",
        "explanation.forecast": "Oszacowanie liniowe z ostatniego trendu Garmin. %@",
        "explanation.labeledDetail": "%1$@: %2$@",
    ]
}
