import Foundation

/// Metric explanations in en. Garmin payload codes are never translated here.
enum LocalizationExplanationEN {
    static let strings: [String: String] = [
        "explanation.load.rangeUnavailable": "Personal range unavailable",
        "explanation.load.ratio.low": "Low load ratio",
        "explanation.load.ratio.optimal": "Optimal load ratio",
        "explanation.load.ratio.high": "High load ratio",
        "explanation.load.ratio.veryHigh": "Very high load ratio",
        "explanation.load.ratio.value": "Acute / chronic: %@",
        "explanation.load.below": "Below optimal range",
        "explanation.load.above": "Above optimal range",
        "explanation.load.optimal": "In optimal range",
        "explanation.load.range": "Your range: %1$@–%2$@",
        "explanation.load.detail": "Acute load estimates the recent training strain on your body. Garmin weights recent sessions more heavily and compares the result with a range based on your fitness and training history. The number alone cannot show whether your training is productive.",
        "explanation.load.ratio.detail": "The load ratio compares recent acute load with longer-term chronic load. Garmin supplies its category separately from training status.",
        "explanation.load.garminStatus": "Garmin status: %@",
        "explanation.load.noStatusDetail": "Training status also considers fitness trends and recovery. Low load by itself does not mean detraining. Garmin has not supplied a recognized training status for this reading.",
        "explanation.hrv.compare": "Compare with your baseline",
        "explanation.hrv.balanced": "Balanced weekly HRV",
        "explanation.hrv.unbalanced": "Unbalanced weekly HRV",
        "explanation.hrv.low": "Low weekly HRV",
        "explanation.hrv.poor": "Poor HRV status",
        "explanation.hrv.insufficient": "Insufficient recent HRV data",
        "explanation.hrv.weekly": "7-day average: %1$@ %2$@",
        "explanation.hrv.baseline": "Your baseline: %1$@–%2$@ %3$@",
        "explanation.hrv.detail": "The value is average heartbeat-interval variation for the recorded night. Garmin compares the 7-day average with your personal baseline, built from about three weeks of sleep data. “%@” instead refers to HRV well below the age-based reference range. A night's value is not the weekly status; higher is not always better.",
        "explanation.readiness.prime": "Prime readiness",
        "explanation.readiness.high": "High readiness",
        "explanation.readiness.moderate": "Moderate readiness",
        "explanation.readiness.low": "Low readiness",
        "explanation.readiness.poor": "Poor readiness",
        "explanation.readiness.detail": "Garmin combines sleep, recovery time, HRV, acute load and recent stress. Scale: 1–24 poor, 25–49 low, 50–74 moderate, 75–94 high, 95–100 prime. Lower scores suggest prioritizing recovery; a high score indicates more capacity for a demanding session.",
        "explanation.sleep.excellent": "Excellent sleep",
        "explanation.sleep.good": "Good sleep",
        "explanation.sleep.fair": "Fair sleep",
        "explanation.sleep.poor": "Poor sleep",
        "explanation.sleep.detail": "A summary of sleep quality and recovery, including duration, sleep stages and restlessness. Garmin's scale: below 60 poor, 60–79 fair, 80–89 good, 90–100 excellent. Duration alone does not determine the score.",
        "explanation.stress.resting": "Resting range",
        "explanation.stress.low": "Low stress",
        "explanation.stress.medium": "Medium stress",
        "explanation.stress.high": "High stress",
        "explanation.stress.detail": "This is the day's average physiological stress reported by Garmin, not a live emotion reading. The 0–100 scale uses heart-rate variability: 0–25 resting, 26–50 low, 51–75 medium, 76–100 high. A daily average can hide short peaks and periods of rest.",
        "explanation.battery.veryLow": "Very low energy reserve",
        "explanation.battery.low": "Low energy reserve",
        "explanation.battery.moderate": "Moderate energy reserve",
        "explanation.battery.high": "High energy reserve",
        "explanation.battery.detail": "Garmin estimates your available energy using stress, heart-rate variability, sleep and activity. Rest can recharge it; stress and activity can drain it. This is an energy estimate, not a percentage of physical fitness.",
        "explanation.recovery.complete": "Recovery countdown complete",
        "explanation.recovery.remaining": "Until the next hard workout",
        "explanation.recovery.detail": "Garmin estimates time until you are ready for another hard workout. It does not require complete inactivity. Sleep, stress and subsequent activity can change the estimate. The value reflects the last Garmin reading.",
        "explanation.vo2.status": "Aerobic fitness estimate",
        "explanation.vo2.detail": "Estimated maximum oxygen use per kilogram per minute. Garmin's fitness categories depend on age and sex; this app does not receive enough profile context to assign one. Compare your trend over time under similar conditions rather than judging a single number.",
        "explanation.restingHR.status": "Follow your personal trend",
        "explanation.restingHR.detail": "Garmin's daily resting heart rate. Compare several days with your own usual level. Fitness, sleep, stress and recovery can influence it; a lower number is not always better.",
        "explanation.oxygen.status": "Garmin average oxygen estimate",
        "explanation.oxygen.detail": "Estimated blood oxygen saturation from the watch. Measurement conditions and altitude affect the result. A single daily average cannot establish a health assessment or show short overnight changes.",
        "explanation.respiration.status": "Average during sleep",
        "explanation.respiration.detail": "Average breaths per minute during sleep. Compare your own nights and longer-term pattern; this is not your current breathing rate.",
        "explanation.sleepDuration.status": "Total time asleep",
        "explanation.sleepDuration.detail": "Time Garmin classified as sleep in the recorded night. It combines light, deep and REM sleep. Consider sleep score and how rested you feel as well as duration.",
        "explanation.sleepStage.awake": "Awake during the sleep period",
        "explanation.sleepStage.status": "Part of the recorded night",
        "explanation.sleepStage.detail": "Garmin estimates sleep stages from sensor data. Stage durations vary between nights, so an isolated value has no universal good/bad threshold. Read it alongside total sleep, sleep score and your pattern over several nights.",
        "explanation.steps.status": "Daily walking activity",
        "explanation.steps.reached": "Daily goal reached",
        "explanation.steps.progress": "Toward your daily goal",
        "explanation.steps.goalDetail": "Step count compared with your own Garmin daily goal. The goal is a target, not a universal measure of fitness.",
        "explanation.steps.goal": "Goal: %@",
        "explanation.steps.detail": "Steps recorded for this day. A personal step goal is needed to assess progress.",
        "explanation.stepsTarget.status": "Your Garmin daily target",
        "explanation.stepsTarget.detail": "The step target set manually or adjusted automatically by Garmin. It is personal and can change from day to day.",
        "explanation.intensity.status": "Weighted activity minutes",
        "explanation.intensity.detail": "Garmin credits moderate activity minutes and gives vigorous minutes double weight. This daily number can exceed the elapsed workout time; it is not your weekly total.",
        "explanation.calories.status": "Resting + active energy",
        "explanation.calories.detail": "Estimated total energy used during the day, including resting metabolism and activity. This is expenditure, not food intake or a calorie deficit.",
        "explanation.activeCalories.status": "Energy from activity",
        "explanation.activeCalories.detail": "Estimated energy used through activity beyond resting needs. It is already included in total calories, so the two should not be added together.",
        "explanation.distance.status": "Daily movement distance",
        "explanation.distance.detail": "Distance reported in Garmin's daily summary. It is a daily activity total, not necessarily the distance of your latest workout.",
        "explanation.floors.status": "Floors climbed",
        "explanation.floors.detail": "Garmin's estimate of floors climbed during the day. It reflects upward movement; it is not the number of flights descended.",
        "explanation.weight.status": "Latest recorded measurement",
        "explanation.weight.detail": "The most recent body-weight measurement available for this record. Single changes can reflect fluid balance and measurement timing. Weight alone does not determine fitness or health.",
        "explanation.hydration.status": "Logged fluid intake",
        "explanation.hydration.detail": "Fluid intake logged in Garmin Connect. This reflects your entries, not a sensor measurement of hydration or a personal daily requirement.",
        "explanation.training.DETRAINING.title": "Detraining",
        "explanation.training.DETRAINING.detail": "Garmin detects declining fitness after an extended reduction in training.",
        "explanation.training.RECOVERY.title": "Recovery",
        "explanation.training.RECOVERY.detail": "Lighter training is allowing recovery from demanding work.",
        "explanation.training.MAINTAINING.title": "Maintaining",
        "explanation.training.MAINTAINING.detail": "Current training maintains fitness without clear improvement.",
        "explanation.training.PRODUCTIVE.title": "Productive",
        "explanation.training.PRODUCTIVE.detail": "Garmin detects improving fitness with your current training.",
        "explanation.training.PEAKING.title": "Peaking",
        "explanation.training.PEAKING.detail": "Reduced load has supported recovery and a short-lived performance peak.",
        "explanation.training.OVERREACHING.title": "Overreaching",
        "explanation.training.OVERREACHING.detail": "Garmin classifies your training load as very high and counterproductive.",
        "explanation.training.UNPRODUCTIVE.title": "Unproductive",
        "explanation.training.UNPRODUCTIVE.detail": "Fitness is declining despite adequate load; sleep, nutrition and stress also matter.",
        "explanation.training.STRAINED.title": "Strained",
        "explanation.training.STRAINED.detail": "Garmin detects an imbalance between training and recovery.",
        "explanation.training.NO_STATUS.title": "No status",
        "explanation.training.NO_STATUS.detail": "Garmin has not yet collected enough qualifying training data.",
        "explanation.training.PAUSED.title": "Paused",
        "explanation.training.PAUSED.detail": "Training status evaluation is paused in Garmin.",
        "explanation.help": "What this means",
        "explanation.source": "Learn more from Garmin",
        "explanation.forecast": "Local linear estimate from recent Garmin readings. %@",
        "explanation.labeledDetail": "%1$@: %2$@",
    ]
}
