// Localized interface strings. Keep keys and format placeholders aligned with English.
enum LocalizationPL {
    static let strings: [String: String] = [
        "widget.summary.minimum": "Co najmniej jeden pomiar musi pozostać zaznaczony.",
        "widget.summary.hint": "Wyświetlane są tylko wybrane pomiary, dla których są dostępne dane. Ich liczba zależy od rozmiaru widżetu.",
        "widget.summary.primary": "Preferowany główny pomiar",
        "widget.summary.choose": "Wybierz pomiary",
        "settings.widgets": "Widżety",
        "settings.widgetsSubtitle": "Pięć gotowych widżetów na biurko.",
        "widget.type": "Typ widżetu",
        "widget.appearance": "Wygląd widżetów",
        "widget.appearance.colorful": "Kolorowy",
        "widget.appearance.light": "Jasny",
        "widget.appearance.dark": "Ciemny",
        "widget.appearanceHint": "Jeden wygląd dla wszystkich pięciu widżetów na biurku.",
        "widget.automaticHint": "Dostępne pomiary są wybierane automatycznie.",
        "widget.guide.fixedTypes": "Wybierz typ i rozmiar widżetu, a następnie dodaj go na biurko.",
        "widget.slot.day": "Dzień",
        "widget.slot.day.description": "Body Battery, kroki, stres i codzienna aktywność.",
        "onboarding.title": "Twoje dane Garmin na Macu",
        "onboarding.privacy": "Twoje pomiary są przechowywane na tym Macu",
        "onboarding.detail": "Połącz konto Garmin, aby wyświetlać pomiary tutaj i w widżetach na biurku.",
        "data.available": "Najnowsze pomiary",
        "data.nightEnding": "Noc zakończona",
        "data.measured": "Zmierzono",
        "data.received": "Otrzymano",
        "metric.short.spo2": "SpO₂ · śr. dzienna",
        "data.waiting": "Oczekiwanie na dane z zegarka",
        "data.waitingNew": "Oczekiwanie na nowe pomiary",
        "data.unchanged": "Brak zmian w pomiarach",
        "data.checkFailed": "Nie udało się odświeżyć danych Garmin",
        "data.unchangedHint": "Oczekujesz nowszych pomiarów? Otwórz Garmin Connect na telefonie i zsynchronizuj zegarek. Pobierzemy je automatycznie.",
        "data.retainedAllHint": "Poniżej znajdziesz ostatnie pomiary wraz z datami. Otwórz Garmin Connect na telefonie i zsynchronizuj zegarek, aby uzyskać nowsze dane.",
        "data.previous": "Ostatnie dostępne",
        "data.retainedHint": "Niektóre pomiary jeszcze nie dotarły. Zachowaliśmy ostatnie wartości wraz z datami. Zsynchronizuj zegarek w Garmin Connect na telefonie.",
        "data.waitingHint": "Otwórz Garmin Connect na telefonie i zsynchronizuj zegarek. Pomiary pojawią się tutaj automatycznie.",
        "widget.notice.connection": "Połącz Garmin ponownie",
        "widget.notice.unavailable": "Nie udało się zaktualizować",
        "widget.notice.waiting": "Oczekiwanie na nowe dane",
        "widget.waiting": "Oczekiwanie na dane",
        "widget.waitingHint": "Zsynchronizuj zegarek w Garmin Connect na telefonie. Pomiary pojawią się tutaj automatycznie.",
        "widget.previous": "Ostatnie dostępne",
        "widget.slot.overview.description": "Wybrane przez Ciebie pomiary w jednym widżecie.",
        "widget.slot.sport.description": "Gotowość do treningu, regeneracja, obciążenie i pułap tlenowy.",
        "widget.slot.sleep.description": "Czas i ocena snu oraz nocna HRV.",
        "widget.slot.training.description": "Kalendarz ukończonych aktywności i zaplanowanych treningów.",
        "widget.preview.easyRun": "Spokojny bieg",
        "widget.preview.intervals": "Interwały biegowe",
        "profile.availableMetrics": "Używaj dostępnych pomiarów",
        "profile.availableMetricsHint": "Pomijaj brakujące pomiary i uzupełniaj widżet powiązanymi wskaźnikami. Wyłącz, aby zachować dokładnie wybrany zestaw.",
        "profile.content": "Zawartość",
        "content.metrics": "Pomiary",
        "content.training": "Kalendarz treningów",
        "content.mixed": "Oba",
        "profile.previewMetricsOnly": "Ten podgląd pokazuje sekcję pomiarów. Karty treningów są również widoczne w sekcji Przegląd.",
        "status.signInRequired": "Wymagane logowanie",
        "connection.retryAfter": "Spróbuj ponownie po",
        "connection.reconnectDetail": "Otwórz okno Garmin i dokończ logowanie, aby wznowić aktualizacje.",
        "widget.guide.staticProfile": "Wybierz typ i rozmiar widżetu, a następnie dodaj go na biurko.",
        "widget.guide.unavailable": "Wyświetlaj pomiary i podglądy widżetów w aplikacji.",
        "widget.sharingDataUnavailable": "Dane widżetów nie są jeszcze dostępne. Pomiary nadal można wyświetlać w aplikacji.",
        "widget.slot.overview": "Podsumowanie",
        "widget.slot.sport": "Sport",
        "widget.slot.sleep": "Sen",
        "widget.slot.training": "Kalendarz treningów",
        "widget.slot.firstProfile": "Pierwszy profil",
        "widget.slot.unassigned": "Wybierz profil…",
        "profile.templates": "Zacznij od szablonu",
        "profile.custom": "Własny profil",
        "profile.template.life": "Na co dzień",
        "profile.template.sport": "Sport",
        "profile.template.sleep": "Sen",
        "profile.previewSize": "Rozmiar widżetu",
        "profile.preview.small": "Mały",
        "profile.preview.medium": "Średni",
        "profile.preview.large": "Duży",
        "profile.previewCount": "Wyświetlono %d z %d pomiarów. Wszystkie wybrane pomiary są dostępne w sekcji Przegląd.",
        "widget.galleryTitle": "Podsumowanie Garmin",
        "widget.galleryDescription": "Zdrowie, sen, aktywność i trening w pięciu gotowych widżetach.",
        "widget.galleryStaticDescription": "Wybierz typ i rozmiar widżetu. Dostępne pomiary pojawią się automatycznie.",
        "connection.webTitle": "Połącz Garmin",
        "connection.webSubtitle": "Połącz raz. Pomiary będą odświeżane automatycznie.",
        "connection.webIntro": "Zaloguj się do Garmin Connect",
        "connection.webDetail": "Otworzy się bezpieczne okno Garmin. Zaloguj się i przejdź weryfikację wymaganą przez Garmin. Aplikacja zachowa to połączenie na Macu.",
        "connection.webSignIn": "Zaloguj się przez Garmin",
        "connection.webPrivacy": "Pomiary i sesja witryny Garmin pozostają na tym Macu. Hasło trafia bezpośrednio do Garmin. Nie ma osobnego serwera ani analityki.",
        "connection.automaticHint": "Dane aktualizują się w tle, także po obudzeniu Maca. Pozostaw Garmin Desk uruchomiony, aby otrzymywać automatyczne aktualizacje.",
        "connection.reconnect": "Połącz Garmin ponownie",
        "connection.nextSync": "Następna aktualizacja po",
        "error.partial": "Nie udało się odświeżyć niektórych pomiarów. Zapisane dane są nadal dostępne.",
        "diagnostic.title": "Szczegóły połączenia",
        "diagnostic.stage": "Etap",
        "diagnostic.apiCode": "Kod Garmin",
        "diagnostic.requests": "Otrzymane odpowiedzi",
        "menu.edit": "Edycja",
        "menu.cut": "Wytnij",
        "menu.copy": "Kopiuj",
        "menu.paste": "Wklej",
        "menu.selectAll": "Zaznacz wszystko",
        "app.subtitle": "Twój dzień na pierwszy rzut oka",
        "app.device": "Garmin fēnix 8",
        "dashboard.title": "Przegląd",
        "dashboard.profile": "Profil",
        "dashboard.moreMetrics": "Większe widżety mogą pokazywać więcej pomiarów",
        "dashboard.configure": "Ustawienia widżetów",
        "widget.setup": "Skonfiguruj widżety na biurku",
        "widget.customize": "Ustawienia widżetów",
        "widget.guide.add": "Kliknij biurko prawym przyciskiem i wybierz Edytuj widżety. Znajdź GarminDesk w galerii.",
        "widget.guide.profile": "Wybierz typ i rozmiar widżetu, a następnie dodaj go na biurko.",
        "widget.guide.refresh": "Garmin Desk pobiera pomiary. macOS decyduje, kiedy widżet na biurku zostanie odświeżony.",
        "widget.sharingUnavailable": "Widżety na biurku nie są dostępne w tej kompilacji. Pomiary nadal można wyświetlać w aplikacji.",
        "widget.openApp": "Otwórz GarminDesk",
        "widget.openAppHint": "Połącz konto Garmin w aplikacji.",
        "widget.profileMissing": "Profil usunięty",
        "widget.profileMissingHint": "Wybierz inny profil w ustawieniach tego widżetu.",
        "widget.demo": "DEMO",
        "widget.connect": "Połącz Garmin w aplikacji",
        "dashboard.empty": "Wybierz w ustawieniach pomiary, które chcesz wyświetlać.",
        "dashboard.connect": "Połącz Garmin",
        "action.settings": "Ustawienia",
        "action.sync": "Odśwież",
        "action.quit": "Zakończ Garmin Desk",
        "action.cancel": "Anuluj",
        "action.save": "Zapisz",
        "action.delete": "Usuń",
        "action.duplicate": "Powiel",
        "action.add": "Dodaj profil",
        "action.up": "Przenieś w górę",
        "action.down": "Przenieś w dół",
        "action.show": "Pokaż",
        "action.hide": "Ukryj",
        "action.done": "Gotowe",
        "action.retry": "Spróbuj ponownie",
        "data.demo": "Dane demonstracyjne",
        "data.updated": "Sprawdzono",
        "data.stale": "Dane mogą być nieaktualne",
        "data.day": "Dane z dnia",
        "data.partial": "Niektóre pomiary są niedostępne",
        "data.emptyDay": "Garmin nie ma jeszcze pomiarów dla tej daty. Zsynchronizuj zegarek z Garmin Connect, aby je zaktualizować.",
        "data.empty": "Brak pomiaru",
        "data.demoDetail": "Przykładowe wartości. Połącz konto, aby zobaczyć własne pomiary.",
        "data.local": "Zapisano na tym Macu",
        "data.source": "Ostatnia synchronizacja Garmin Connect",
        "data.syncing": "Sprawdzanie Garmin Connect…",
        "status.connected": "Garmin połączony",
        "status.notConnected": "Garmin nie jest połączony",
        "status.connecting": "Łączenie…",
        "settings.title": "Ustawienia",
        "settings.profiles": "Profile widżetów",
        "settings.connection": "Konto Garmin",
        "settings.general": "Ogólne",
        "settings.profilesSubtitle": "Utwórz widok na każdą część dnia.",
        "settings.generalSubtitle": "Dostosuj Garmin Desk do swojego Maca.",
        "profile.name": "Nazwa profilu",
        "profile.primary": "Główny pomiar",
        "profile.metrics": "Pomiary",
        "profile.metricsHint": "Wybierz, co wyświetlać. Główny pomiar jest zawsze pierwszy.",
        "profile.appearance": "Wygląd",
        "profile.style": "Styl",
        "profile.density": "Gęstość",
        "profile.preview": "Podgląd",
        "profile.added": "Nowy profil",
        "profile.new": "Nowy profil",
        "profile.default": "Mój dzień",
        "profile.copy": "Kopia",
        "profile.untitled": "Profil bez nazwy",
        "profile.deleteTitle": "Usunąć ten profil?",
        "profile.deleteMessage": "Profil zostanie usunięty. Dane Garmin pozostaną na tym Macu.",
        "profile.oneRequired": "Zachowaj co najmniej jeden profil.",
        "profile.enabled": "Uwzględnione",
        "profile.available": "Dostępne pomiary",
        "profile.count": "pomiary",
        "profile.mainBadge": "Główny",
        "style.calm": "Spokojny",
        "style.sport": "Sportowy",
        "style.monochrome": "Monochromatyczny",
        "density.comfortable": "Przestronnie",
        "density.compact": "Kompaktowo",
        "connection.title": "Twoje konto Garmin",
        "connection.subtitle": "Mac łączy się bezpośrednio z Garmin Connect.",
        "connection.localTitle": "Twoje dane pozostają u Ciebie",
        "connection.localDetail": "Pomiary są przechowywane na tym Macu. Dane uwierzytelniające sesji są zapisane w pęku kluczy macOS. Aplikacja nie ma osobnego serwera.",
        "connection.email": "E-mail",
        "connection.password": "Hasło",
        "connection.china": "Użyj Garmin China",
        "connection.signIn": "Połącz konto",
        "connection.disconnect": "Rozłącz i usuń dane lokalne",
        "connection.disconnectTitle": "Rozłączyć Garmin?",
        "connection.disconnectMessage": "Zapisana sesja Garmin i pomiary zostaną usunięte z tego Maca. Preferencje zostaną zachowane.",
        "connection.demo": "Wypróbuj dane demonstracyjne",
        "connection.demoHint": "Wartości demonstracyjne są zawsze oznaczone.",
        "connection.syncHint": "Zsynchronizuj zegarek z Garmin Connect, aby zobaczyć tutaj nowe pomiary.",
        "connection.secureHint": "Hasło służy tylko do logowania i nie jest zapisywane przez aplikację.",
        "connection.mfaTitle": "Kod weryfikacyjny",
        "connection.mfaHint": "Wpisz kod wymagany przez Garmin, aby dokończyć łączenie.",
        "connection.mfaCode": "Kod",
        "connection.verify": "Zweryfikuj",
        "connection.cancelLogin": "Anuluj logowanie",
        "general.language": "Język",
        "general.appearance": "Wygląd",
        "general.refresh": "Częstotliwość odświeżania",
        "general.system": "Zgodnie z systemem",
        "general.light": "Jasny",
        "general.dark": "Ciemny",
        "general.minutes5": "Co 5 minut",
        "general.minutes15": "Co 15 minut",
        "general.minutes30": "Co 30 minut",
        "general.minutes60": "Co godzinę",
        "general.refreshHint": "Aktualizacje korzystają z najnowszych pomiarów dostępnych w Garmin Connect.",
        "general.localNotice": "Preferencje są zapisywane automatycznie na tym Macu.",
        "general.launchAtLogin": "Otwórz Garmin Desk po zalogowaniu",
        "general.backgroundHint": "Zamknięcie okna nie przerywa automatycznych aktualizacji. Wybierz Zakończ Garmin Desk lub naciśnij ⌘Q, aby zamknąć aplikację.",
        "menu.about": "Garmin Desk — informacje",
        "menu.hideApp": "Ukryj Garmin Desk",
        "menu.hideOthers": "Ukryj pozostałe",
        "menu.showAll": "Pokaż wszystkie",
        "menu.file": "Plik",
        "menu.closeWindow": "Zamknij okno",
        "menu.window": "Okno",
        "menu.mainWindow": "Garmin Desk",
        "menu.minimize": "Minimalizuj",
        "menu.zoom": "Zoom",
        "category.health": "Zdrowie i regeneracja",
        "category.sleep": "Sen",
        "category.activity": "Codzienna aktywność",
        "category.training": "Trening",
        "category.body": "Ciało i nawodnienie",
        "metric.steps": "Kroki",
        "metric.stepGoal": "Cel kroków",
        "metric.distance": "Dystans",
        "metric.calories": "Kalorie łącznie",
        "metric.activeCalories": "Aktywne kalorie",
        "metric.floors": "Pokonane piętra",
        "metric.intensityMinutes": "Minuty intensywnej aktywności",
        "metric.restingHeartRate": "Tętno spoczynkowe",
        "metric.heartRate": "Ostatnie tętno",
        "metric.stress": "Średni dzienny stres",
        "metric.bodyBattery": "Body Battery",
        "metric.sleepDuration": "Czas snu",
        "metric.sleepScore": "Ocena snu",
        "metric.deepSleep": "Sen głęboki",
        "metric.remSleep": "Sen REM",
        "metric.lightSleep": "Sen płytki",
        "metric.awakeSleep": "Czas czuwania",
        "metric.hrv": "Nocna HRV",
        "metric.spo2": "Średnia dzienna SpO₂",
        "metric.respiration": "Średnia częstość oddechów we śnie",
        "metric.trainingReadiness": "Gotowość do treningu",
        "metric.recoveryTime": "Czas regeneracji",
        "metric.vo2Max": "Pułap tlenowy — bieg",
        "metric.trainingLoad": "Bieżące obciążenie treningowe",
        "metric.weight": "Masa ciała",
        "metric.hydration": "Nawodnienie",
        "metric.short.sleepDuration": "Sen",
        "metric.short.stress": "Stres · dzień",
        "metric.short.restingHeartRate": "Tętno spocz.",
        "metric.short.trainingReadiness": "Gotowość",
        "metric.short.hrv": "HRV · noc",
        "metric.short.respiration": "Oddech · sen",
        "metric.short.intensityMinutes": "Min. intensywne",
        "metric.short.activeCalories": "Aktywne kalorie",
        "metric.short.recoveryTime": "Regeneracja",
        "metric.short.trainingLoad": "Bieżące obciążenie",
        "metric.short.vo2Max": "VO₂ max — bieg",
        "metric.short.calories": "Kalorie łącznie",
        "unit.minutes": "min",
        "unit.hours": "godz.",
        "unit.km": "km",
        "unit.kg": "kg",
        "unit.ml": "ml",
        "unit.bpm": "ud./min",
        "unit.kcal": "kcal",
        "unit.ms": "ms",
        "unit.breaths": "odd./min",
        "unit.vo2": "ml/kg/min",
        "error.auth": "Nie udało się zalogować. Sprawdź dane i spróbuj ponownie.",
        "error.rate_limit": "Garmin tymczasowo ograniczył żądania. Spróbuj ponownie później.",
        "error.session_unsupported": "Aplikacja nie może przywrócić zapisanej sesji. Połącz konto Garmin ponownie.",
        "error.access_denied": "Garmin odmówił dostępu do żądanych danych.",
        "error.security_challenge": "Kontrola bezpieczeństwa Garmin zablokowała połączenie. Spróbuj ponownie później.",
        "error.network": "Nie można połączyć się z Garmin. Sprawdź połączenie z internetem.",
        "error.dependency": "Moduł połączenia Garmin jest niedostępny. Zainstaluj ponownie najnowszą wersję Garmin Desk.",
        "error.unknown": "Nie udało się wykonać żądania. Spróbuj ponownie.",
        "error.timeout": "Garmin nie odpowiedział na czas. Spróbuj ponownie.",
        "error.keychain": "Nie można uzyskać dostępu do pęku kluczy macOS. Sprawdź, czy jest odblokowany.",
        "error.protocol": "Garmin zwrócił dane, których aplikacja nie mogła odczytać. Spróbuj ponownie później.",
        "error.storage": "Nie udało się zapisać danych na tym Macu. Sprawdź wolne miejsce na dysku i uprawnienia.",
        "error.login_item": "Zezwól na otwieranie Garmin Desk po zalogowaniu w Ustawieniach systemowych → Ogólne → Rzeczy do otwarcia.",
        "training.title": "Trening",
        "training.last": "Ostatni ukończony",
        "training.next": "Następny zaplanowany",
        "training.completed": "Ukończone",
        "training.planned": "Zaplanowane",
        "training.recent": "Ostatnie aktywności",
        "training.upcoming": "Nadchodzące treningi",
        "training.workout": "Trening",
        "training.dateUnknown": "Nie podano daty",
        "training.timeUnknown": "Nie podano godziny",
        "training.localTime": "zapisany czas lokalny",
        "training.durationUnknown": "Nie podano czasu trwania",
        "training.pastUnavailable": "Historia nie jest jeszcze dostępna",
        "training.pastUnavailableHint": "Ta sekcja nie została jeszcze pobrana z Garmin.",
        "training.pastEmpty": "Brak aktywności w ostatniej odpowiedzi",
        "training.pastCoverage": "Do 20 ostatnich aktywności · niepełna historia",
        "training.futureUnavailable": "Harmonogram nie jest jeszcze dostępny",
        "training.futureUnavailableHint": "Niedostępny kalendarz nie oznacza braku treningów.",
        "training.futureEmpty": "Brak treningów w pobranym fragmencie",
        "training.calendar": "Opublikowany kalendarz Garmin",
        "training.adaptive": "Zweryfikowany kalendarz adaptacyjny",
        "training.partial": "Część kalendarza jest niedostępna",
        "training.expiredCoverage": "Sprawdzony okres się zakończył",
        "training.refreshCalendar": "Odśwież, aby sprawdzić nowy okres.",
        "training.updated": "Zaktualizowano",
        "training.updatedUnknown": "Czas aktualizacji jest nieznany",
        "training.cached": "Zapisane dane",
        "training.refreshFailed": "Nie udało się odświeżyć tej sekcji",
        "training.rateLimit": "Garmin tymczasowo ogranicza żądania",
        "training.signIn": "Zaloguj się do Garmin Connect, aby odświeżyć",
        "training.hour": "godz.",
        "training.minute": "min",
        "training.second": "s",
        "training.km": "km",
        "training.sport.running": "Bieganie",
        "training.sport.trail_running": "Biegi terenowe",
        "training.sport.treadmill_running": "Bieg na bieżni mechanicznej",
        "training.sport.track_running": "Bieg na bieżni lekkoatletycznej",
        "training.sport.cycling": "Kolarstwo",
        "training.sport.mountain_biking": "Kolarstwo terenowe",
        "training.sport.indoor_cycling": "Kolarstwo stacjonarne",
        "training.sport.swimming": "Pływanie",
        "training.sport.open_water_swimming": "Pływanie na wodach otwartych",
        "training.sport.walking": "Chodzenie",
        "training.sport.hiking": "Wędrówki",
        "training.sport.strength_training": "Trening siłowy",
        "training.sport.cardio_training": "Kardio",
        "training.sport.elliptical": "Orbitrek",
        "training.sport.stair_climbing": "Wchodzenie po schodach",
        "training.sport.yoga": "Joga",
        "training.sport.pilates": "Pilates",
        "training.sport.rowing": "Wioślarstwo",
        "training.sport.tennis": "Tenis",
        "training.sport.golf": "Golf",
        "training.sport.alpine_skiing": "Narciarstwo zjazdowe",
        "training.sport.cross_country_skiing": "Narciarstwo biegowe",
        "training.sport.snowboarding": "Snowboard",
        "training.sport.triathlon": "Multisport",
        "training.noPublishedThrough": "Brak opublikowanych treningów do %@",
        "training.checkedThrough": "sprawdzono do %@",
    ]
}
