import Foundation

/// Metric explanations in es. Garmin payload codes are never translated here.
enum LocalizationExplanationES {
    static let strings: [String: String] = [
        "explanation.load.rangeUnavailable": "Rango personal no disponible",
        "explanation.load.ratio.low": "Ratio de carga bajo",
        "explanation.load.ratio.optimal": "Ratio de carga óptimo",
        "explanation.load.ratio.high": "Ratio de carga alto",
        "explanation.load.ratio.veryHigh": "Ratio de carga muy alto",
        "explanation.load.ratio.value": "Aguda / crónica: %@",
        "explanation.load.below": "Por debajo del rango óptimo",
        "explanation.load.above": "Por encima del rango óptimo",
        "explanation.load.optimal": "Dentro del rango óptimo",
        "explanation.load.range": "Tu rango: %1$@–%2$@",
        "explanation.load.detail": "La carga aguda estima el esfuerzo de los entrenamientos recientes. Garmin da más peso a las sesiones recientes y compara el resultado con un rango basado en tu forma e historial. El número por sí solo no indica si el entrenamiento es productivo.",
        "explanation.load.ratio.detail": "El ratio compara la carga aguda reciente con la carga crónica a más largo plazo. Garmin proporciona esta categoría por separado del estado de entrenamiento.",
        "explanation.load.garminStatus": "Estado Garmin: %@",
        "explanation.load.noStatusDetail": "El estado de entrenamiento también considera la evolución de la forma y la recuperación. Una carga baja no implica por sí sola desentrenamiento. Garmin no ha proporcionado un estado reconocido para esta lectura.",
        "explanation.hrv.compare": "Compara con tu referencia",
        "explanation.hrv.balanced": "VFC semanal equilibrada",
        "explanation.hrv.unbalanced": "VFC semanal desequilibrada",
        "explanation.hrv.low": "VFC semanal baja",
        "explanation.hrv.poor": "Estado de VFC deficiente",
        "explanation.hrv.insufficient": "Faltan datos recientes de VFC",
        "explanation.hrv.weekly": "Media de 7 días: %1$@ %2$@",
        "explanation.hrv.baseline": "Tu referencia: %1$@–%2$@ %3$@",
        "explanation.hrv.detail": "El valor es la variación media de los intervalos entre latidos de la noche registrada. Garmin compara la media de 7 días con tu referencia, establecida con unas tres semanas de sueño. «%@» indica, en cambio, una VFC muy por debajo del rango para tu edad. Una noche no es el estado semanal; más alto no siempre es mejor.",
        "explanation.readiness.prime": "Predisposición óptima",
        "explanation.readiness.high": "Predisposición alta",
        "explanation.readiness.moderate": "Predisposición moderada",
        "explanation.readiness.low": "Predisposición baja",
        "explanation.readiness.poor": "Predisposición muy baja",
        "explanation.readiness.detail": "Garmin combina sueño, recuperación, VFC, carga aguda y estrés reciente. Escala: 1–24 muy baja, 25–49 baja, 50–74 moderada, 75–94 alta, 95–100 óptima. Un valor bajo sugiere priorizar la recuperación; uno alto indica más capacidad para una sesión exigente.",
        "explanation.sleep.excellent": "Sueño excelente",
        "explanation.sleep.good": "Buen sueño",
        "explanation.sleep.fair": "Sueño aceptable",
        "explanation.sleep.poor": "Sueño deficiente",
        "explanation.sleep.detail": "Resumen de la calidad del sueño y la recuperación según duración, fases e inquietud. Escala Garmin: menos de 60 deficiente, 60–79 aceptable, 80–89 bueno, 90–100 excelente. La duración no determina por sí sola la puntuación.",
        "explanation.stress.resting": "Rango de reposo",
        "explanation.stress.low": "Estrés bajo",
        "explanation.stress.medium": "Estrés medio",
        "explanation.stress.high": "Estrés alto",
        "explanation.stress.detail": "Estrés fisiológico medio del día según Garmin, no una lectura instantánea de emociones. La escala usa la variabilidad cardíaca: 0–25 reposo, 26–50 bajo, 51–75 medio, 76–100 alto. La media puede ocultar picos breves y periodos de descanso.",
        "explanation.battery.veryLow": "Reserva de energía muy baja",
        "explanation.battery.low": "Reserva de energía baja",
        "explanation.battery.moderate": "Reserva de energía moderada",
        "explanation.battery.high": "Reserva de energía alta",
        "explanation.battery.detail": "Garmin estima la energía disponible a partir del estrés, la variabilidad cardíaca, el sueño y la actividad. El descanso puede recargarla; el estrés y la actividad pueden consumirla. Es una estimación de energía, no un porcentaje de forma física.",
        "explanation.recovery.complete": "Cuenta de recuperación terminada",
        "explanation.recovery.remaining": "Hasta el próximo esfuerzo intenso",
        "explanation.recovery.detail": "Garmin estima el tiempo hasta estar listo para otro entrenamiento intenso. No exige inactividad total. El sueño, el estrés y la actividad posterior pueden cambiar la estimación. Se muestra la última lectura de Garmin.",
        "explanation.vo2.status": "Estimación de capacidad aeróbica",
        "explanation.vo2.detail": "Consumo máximo estimado de oxígeno por kilogramo y minuto. Las categorías Garmin dependen de la edad y el sexo; la app no recibe suficiente información del perfil para asignar una. Compara tu evolución en condiciones similares, no un único valor.",
        "explanation.restingHR.status": "Sigue tu propia evolución",
        "explanation.restingHR.detail": "Frecuencia cardíaca diaria en reposo según Garmin. Compara varios días con tu nivel habitual. La forma, el sueño, el estrés y la recuperación influyen; más bajo no siempre es mejor.",
        "explanation.oxygen.status": "Estimación media de oxígeno",
        "explanation.oxygen.detail": "Saturación de oxígeno en sangre estimada por el reloj. Las condiciones de medición y la altitud influyen. Una media diaria no permite evaluar la salud ni mostrar cambios nocturnos breves.",
        "explanation.respiration.status": "Media durante el sueño",
        "explanation.respiration.detail": "Respiraciones medias por minuto durante el sueño. Compara tus noches y la tendencia a largo plazo; no es tu frecuencia respiratoria actual.",
        "explanation.sleepDuration.status": "Tiempo total de sueño",
        "explanation.sleepDuration.detail": "Tiempo que Garmin clasificó como sueño en la noche registrada: ligero, profundo y REM. Ten en cuenta también la puntuación del sueño y cuánto has descansado.",
        "explanation.sleepStage.awake": "Vigilia en el periodo de sueño",
        "explanation.sleepStage.status": "Parte de la noche registrada",
        "explanation.sleepStage.detail": "Garmin estima las fases del sueño con sensores. Su duración varía cada noche; un valor aislado no tiene un umbral universal bueno o malo. Considéralo junto al sueño total, la puntuación y varias noches.",
        "explanation.steps.status": "Actividad diaria al caminar",
        "explanation.steps.reached": "Objetivo diario alcanzado",
        "explanation.steps.progress": "Hacia tu objetivo diario",
        "explanation.steps.goalDetail": "Pasos comparados con tu objetivo diario personal de Garmin. El objetivo es una meta, no una medida universal de forma física.",
        "explanation.steps.goal": "Objetivo: %@",
        "explanation.steps.detail": "Pasos registrados este día. Para valorar el progreso se necesita un objetivo personal de pasos.",
        "explanation.stepsTarget.status": "Tu objetivo diario de Garmin",
        "explanation.stepsTarget.detail": "Objetivo de pasos fijado manualmente o ajustado por Garmin. Es personal y puede cambiar cada día.",
        "explanation.intensity.status": "Minutos de actividad ponderados",
        "explanation.intensity.detail": "Garmin cuenta los minutos moderados y duplica los intensos. El total diario puede superar la duración del entrenamiento; no es tu total semanal.",
        "explanation.calories.status": "Energía en reposo + actividad",
        "explanation.calories.detail": "Gasto total estimado de energía del día, incluido el metabolismo en reposo y la actividad. Es gasto, no ingesta de alimentos ni déficit calórico.",
        "explanation.activeCalories.status": "Energía por actividad",
        "explanation.activeCalories.detail": "Gasto estimado por actividad por encima de las necesidades en reposo. Ya está incluido en las calorías totales; no se deben sumar ambos.",
        "explanation.distance.status": "Distancia recorrida en el día",
        "explanation.distance.detail": "Distancia del resumen diario de Garmin. Es el total de actividad del día, no necesariamente la distancia de tu último entrenamiento.",
        "explanation.floors.status": "Pisos subidos",
        "explanation.floors.detail": "Estimación Garmin de los pisos subidos durante el día. Refleja ascensos, no los tramos descendidos.",
        "explanation.weight.status": "Última medición registrada",
        "explanation.weight.detail": "Última medición de peso disponible para este registro. Los cambios aislados pueden depender del agua corporal y la hora de medición. El peso solo no determina la forma ni la salud.",
        "explanation.hydration.status": "Líquidos registrados",
        "explanation.hydration.detail": "Líquidos anotados en Garmin Connect. Refleja tus entradas, no una medición de hidratación por sensor ni tu necesidad diaria personal.",
        "explanation.training.DETRAINING.title": "Desentrenamiento",
        "explanation.training.DETRAINING.detail": "Garmin detecta pérdida de forma tras una reducción prolongada del entrenamiento.",
        "explanation.training.RECOVERY.title": "Recuperación",
        "explanation.training.RECOVERY.detail": "Un entrenamiento más ligero permite recuperarse de esfuerzos exigentes.",
        "explanation.training.MAINTAINING.title": "Mantenimiento",
        "explanation.training.MAINTAINING.detail": "El entrenamiento actual mantiene la forma sin una mejora clara.",
        "explanation.training.PRODUCTIVE.title": "Productivo",
        "explanation.training.PRODUCTIVE.detail": "Garmin detecta una mejora de la forma con el entrenamiento actual.",
        "explanation.training.PEAKING.title": "Pico de forma",
        "explanation.training.PEAKING.detail": "La carga reducida ha favorecido la recuperación y un pico de rendimiento breve.",
        "explanation.training.OVERREACHING.title": "Sobreesfuerzo",
        "explanation.training.OVERREACHING.detail": "Garmin clasifica tu carga de entrenamiento como muy alta y contraproducente.",
        "explanation.training.UNPRODUCTIVE.title": "No productivo",
        "explanation.training.UNPRODUCTIVE.detail": "La forma empeora pese a una carga suficiente; también influyen sueño, alimentación y estrés.",
        "explanation.training.STRAINED.title": "Sobrecarga",
        "explanation.training.STRAINED.detail": "Garmin detecta un desequilibrio entre entrenamiento y recuperación.",
        "explanation.training.NO_STATUS.title": "Sin estado",
        "explanation.training.NO_STATUS.detail": "Garmin aún no tiene suficientes datos de entrenamiento aptos para evaluar el estado.",
        "explanation.training.PAUSED.title": "En pausa",
        "explanation.training.PAUSED.detail": "La evaluación del estado de entrenamiento está pausada en Garmin.",
        "explanation.help": "Qué significa esta medida",
        "explanation.source": "Más información en Garmin",
        "explanation.forecast": "Estimación lineal local a partir de las últimas lecturas Garmin. %@",
        "explanation.labeledDetail": "%1$@: %2$@",
    ]
}
