// ja translations shared by the app and WidgetKit.
enum LocalizationJA {
    static let strings: [String: String] = [
        "widget.summary.minimum": "少なくとも1つの項目を選択してください。",
        "widget.summary.hint": "選択した項目のうち、データがあるものだけを表示します。表示数はウィジェットのサイズによって変わります。",
        "widget.summary.primary": "優先するメイン項目",
        "widget.summary.choose": "測定項目を選択",
        "settings.widgets": "ウィジェット",
        "settings.widgetsSubtitle": "デスクトップで使える5種類のウィジェット。",
        "widget.type": "ウィジェットの種類",
        "widget.appearance": "ウィジェットの外観",
        "widget.appearance.colorful": "カラー",
        "widget.appearance.light": "ライト",
        "widget.appearance.dark": "ダーク",
        "widget.appearanceHint": "5種類すべてのウィジェットに適用されます。",
        "widget.automaticHint": "利用可能な測定値が自動的に選ばれます。",
        "widget.guide.fixedTypes": "ウィジェットの種類とサイズを選び、デスクトップに追加します。",
        "widget.slot.day": "一日",
        "widget.slot.day.description": "Body Battery、歩数、ストレス、日々の活動。",
        "onboarding.title": "GarminのデータをMacに",
        "onboarding.privacy": "測定値はこのMacに保存されます",
        "onboarding.detail": "Garminアカウントを接続すると、アプリとデスクトップウィジェットに測定値が表示されます。",
        "data.available": "最新の測定値",
        "data.nightEnding": "睡眠終了日",
        "data.measured": "測定日時",
        "data.received": "受信日時",
        "metric.short.spo2": "SpO₂・日平均",
        "data.waiting": "ウォッチのデータを待っています",
        "data.waitingNew": "新しい測定値を待っています",
        "data.unchanged": "測定値に変更はありません",
        "data.checkFailed": "Garminデータを更新できませんでした",
        "data.unchangedHint": "新しい測定値が表示されませんか？スマートフォンのGarmin Connectを開き、ウォッチを同期してください。同期後、自動で取得します。",
        "data.retainedAllHint": "前回の測定値を日付とともに表示しています。新しい測定値を取得するには、スマートフォンのGarmin Connectでウォッチを同期してください。",
        "data.previous": "前回のデータ",
        "data.retainedHint": "一部の測定値はまだ届いていません。前回の値と日付を保持しています。スマートフォンのGarmin Connectでウォッチを同期してください。",
        "data.waitingHint": "スマートフォンのGarmin Connectでウォッチを同期してください。測定値は自動で表示されます。",
        "widget.notice.connection": "Garminを再接続",
        "widget.notice.unavailable": "更新できませんでした",
        "widget.notice.waiting": "新しいデータを待機中",
        "widget.waiting": "データを待機中",
        "widget.waitingHint": "スマートフォンのGarmin Connectでウォッチを同期してください。測定値は自動で表示されます。",
        "widget.previous": "前回のデータ",
        "widget.slot.overview.description": "選んだ測定項目を1つのウィジェットに。",
        "widget.slot.sport.description": "トレーニングレディネス、リカバリー、負荷、VO₂ max。",
        "widget.slot.sleep.description": "睡眠時間、睡眠スコア、夜間のHRV。",
        "widget.slot.training.description": "完了したアクティビティと予定されたワークアウトのカレンダー。",
        "widget.preview.easyRun": "イージーラン",
        "widget.preview.intervals": "インターバルラン",
        "profile.availableMetrics": "利用可能な測定値を使用",
        "profile.availableMetricsHint": "測定値のない項目を省き、関連する指標でウィジェットを補います。選択した項目だけを表示するにはオフにしてください。",
        "profile.content": "表示内容",
        "content.metrics": "指標",
        "content.training": "トレーニングカレンダー",
        "content.mixed": "両方",
        "profile.previewMetricsOnly": "このプレビューには指標が表示されます。ワークアウトカードは「概要」にも表示されます。",
        "status.signInRequired": "サインインが必要です",
        "connection.retryAfter": "再試行可能な時刻",
        "connection.reconnectDetail": "Garminのウインドウでサインインを完了すると、更新が再開します。",
        "widget.guide.staticProfile": "ウィジェットの種類とサイズを選び、デスクトップに追加します。",
        "widget.guide.unavailable": "アプリで測定値とウィジェットのプレビューを確認できます。",
        "widget.sharingDataUnavailable": "ウィジェットのデータはまだ利用できません。測定値はアプリで確認できます。",
        "widget.slot.overview": "サマリー",
        "widget.slot.sport": "スポーツ",
        "widget.slot.sleep": "睡眠",
        "widget.slot.training": "トレーニングカレンダー",
        "widget.slot.firstProfile": "最初のプロファイル",
        "widget.slot.unassigned": "プロファイルを選択…",
        "profile.templates": "テンプレートから作成",
        "profile.custom": "カスタムプロファイル",
        "profile.template.life": "日常",
        "profile.template.sport": "スポーツ",
        "profile.template.sleep": "睡眠",
        "profile.previewSize": "ウィジェットのサイズ",
        "profile.preview.small": "小",
        "profile.preview.medium": "中",
        "profile.preview.large": "大",
        "profile.previewCount": "%d / %d項目を表示。選択した指標はすべて「概要」で確認できます。",
        "widget.galleryTitle": "Garminサマリー",
        "widget.galleryDescription": "健康、睡眠、活動、トレーニングを5種類のウィジェットで確認できます。",
        "widget.galleryStaticDescription": "ウィジェットの種類とサイズを選びます。利用可能な測定値が自動的に表示されます。",
        "connection.webTitle": "Garminを接続",
        "connection.webSubtitle": "一度接続すると、測定値は自動で更新されます。",
        "connection.webIntro": "Garmin Connectにサインイン",
        "connection.webDetail": "Garminの安全なウインドウが開きます。サインインと、必要に応じてGarminの確認手続きを完了してください。接続情報はこのMacに保存されます。",
        "connection.webSignIn": "Garminでサインイン",
        "connection.webPrivacy": "測定値とGarminサイトのセッションはこのMacに保存されます。パスワードはGarminに直接送信されます。独自のサーバーやアクセス解析は使用しません。",
        "connection.automaticHint": "Macのスリープ解除後も含め、データはバックグラウンドで更新されます。自動更新にはGarmin Deskを起動したままにしてください。",
        "connection.reconnect": "Garminを再接続",
        "connection.nextSync": "次回の更新可能時刻",
        "error.partial": "一部の測定値を更新できませんでした。保存済みのデータは引き続き表示されます。",
        "diagnostic.title": "接続の詳細",
        "diagnostic.stage": "段階",
        "diagnostic.apiCode": "Garminコード",
        "diagnostic.requests": "受信した応答数",
        "menu.edit": "編集",
        "menu.cut": "カット",
        "menu.copy": "コピー",
        "menu.paste": "ペースト",
        "menu.selectAll": "すべてを選択",
        "app.subtitle": "一日の様子をひと目で",
        "app.device": "Garmin fēnix 8",
        "dashboard.title": "概要",
        "dashboard.profile": "プロファイル",
        "dashboard.moreMetrics": "大きいウィジェットには、より多くの指標を表示できます",
        "dashboard.configure": "ウィジェットの設定",
        "widget.setup": "デスクトップウィジェットを設定",
        "widget.customize": "ウィジェットの設定",
        "widget.guide.add": "デスクトップを右クリックして「ウィジェットを編集」を選択し、ギャラリーでGarminDeskを探します。",
        "widget.guide.profile": "ウィジェットの種類とサイズを選び、デスクトップに追加します。",
        "widget.guide.refresh": "Garmin Deskが測定値を取得し、デスクトップウィジェットの更新タイミングはmacOSが決めます。",
        "widget.sharingUnavailable": "このバージョンではデスクトップウィジェットを利用できません。測定値はアプリで確認できます。",
        "widget.openApp": "GarminDeskを開く",
        "widget.openAppHint": "アプリでGarminアカウントに接続してください。",
        "widget.profileMissing": "プロファイルは削除されました",
        "widget.profileMissingHint": "このウィジェットの設定で別のプロファイルを選択してください。",
        "widget.demo": "デモ",
        "widget.connect": "アプリでGarminを接続",
        "dashboard.empty": "設定で表示したい指標を選択してください。",
        "dashboard.connect": "Garminを接続",
        "action.settings": "設定",
        "action.sync": "更新",
        "action.quit": "Garmin Deskを終了",
        "action.cancel": "キャンセル",
        "action.save": "保存",
        "action.delete": "削除",
        "action.duplicate": "複製",
        "action.add": "プロファイルを追加",
        "action.up": "上に移動",
        "action.down": "下に移動",
        "action.show": "表示",
        "action.hide": "非表示",
        "action.done": "完了",
        "action.retry": "再試行",
        "data.demo": "デモデータ",
        "data.updated": "確認日時",
        "data.stale": "データが古い可能性があります",
        "data.day": "データの日付",
        "data.partial": "一部の測定値を利用できません",
        "data.emptyDay": "この日の測定値はまだGarminにありません。Garmin Connectでウォッチを同期すると更新されます。",
        "data.empty": "測定値はまだありません",
        "data.demoDetail": "サンプル値です。実際の測定値を表示するには、アカウントを接続してください。",
        "data.local": "このMacに保存済み",
        "data.source": "最新のGarmin Connect同期",
        "data.syncing": "Garmin Connectを確認中…",
        "status.connected": "Garminに接続済み",
        "status.notConnected": "Garminは未接続",
        "status.connecting": "接続中…",
        "settings.title": "設定",
        "settings.profiles": "ウィジェットのプロファイル",
        "settings.connection": "Garminアカウント",
        "settings.general": "一般",
        "settings.profilesSubtitle": "一日の場面に合わせた表示を作成できます。",
        "settings.generalSubtitle": "Macに合わせてGarmin Deskを設定できます。",
        "profile.name": "プロファイル名",
        "profile.primary": "メインの指標",
        "profile.metrics": "指標",
        "profile.metricsHint": "表示する指標を選択します。メインの指標は常に最初に表示されます。",
        "profile.appearance": "外観",
        "profile.style": "スタイル",
        "profile.density": "表示密度",
        "profile.preview": "プレビュー",
        "profile.added": "新しいプロファイル",
        "profile.new": "新しいプロファイル",
        "profile.default": "今日の記録",
        "profile.copy": "コピー",
        "profile.untitled": "名称未設定のプロファイル",
        "profile.deleteTitle": "このプロファイルを削除しますか？",
        "profile.deleteMessage": "プロファイルを削除します。GarminのデータはこのMacに保持されます。",
        "profile.oneRequired": "プロファイルは最低1つ必要です。",
        "profile.enabled": "選択済み",
        "profile.available": "選択できる指標",
        "profile.count": "項目",
        "profile.mainBadge": "メイン",
        "style.calm": "落ち着いた色",
        "style.sport": "スポーツ",
        "style.monochrome": "モノクロ",
        "density.comfortable": "ゆったり",
        "density.compact": "コンパクト",
        "connection.title": "Garminアカウント",
        "connection.subtitle": "MacからGarmin Connectに直接接続します。",
        "connection.localTitle": "データは手元に",
        "connection.localDetail": "測定値はこのMacにキャッシュされます。セッション認証情報はmacOSキーチェーンに保存されます。独自のサーバーはありません。",
        "connection.email": "メールアドレス",
        "connection.password": "パスワード",
        "connection.china": "Garmin Chinaを使用",
        "connection.signIn": "アカウントを接続",
        "connection.disconnect": "接続を解除してローカルデータを消去",
        "connection.disconnectTitle": "Garminの接続を解除しますか？",
        "connection.disconnectMessage": "保存されたGarminセッションと測定値のキャッシュをこのMacから削除します。設定は保持されます。",
        "connection.demo": "デモデータで試す",
        "connection.demoHint": "デモの値には必ずラベルが付きます。",
        "connection.syncHint": "Garmin Connectでウォッチを同期すると、新しい測定値をここで確認できます。",
        "connection.secureHint": "パスワードはサインインにのみ使用され、このアプリには保存されません。",
        "connection.mfaTitle": "確認コード",
        "connection.mfaHint": "Garminから求められたコードを入力して接続を完了してください。",
        "connection.mfaCode": "コード",
        "connection.verify": "確認",
        "connection.cancelLogin": "サインインをキャンセル",
        "general.language": "言語",
        "general.appearance": "外観",
        "general.refresh": "更新間隔",
        "general.system": "システムに従う",
        "general.light": "ライト",
        "general.dark": "ダーク",
        "general.minutes5": "5分ごと",
        "general.minutes15": "15分ごと",
        "general.minutes30": "30分ごと",
        "general.minutes60": "1時間ごと",
        "general.refreshHint": "Garmin Connectにある最新の測定値を取得します。",
        "general.localNotice": "設定はこのMacに自動保存されます。",
        "general.launchAtLogin": "ログイン時にGarmin Deskを開く",
        "general.backgroundHint": "ウインドウを閉じても自動更新は続きます。アプリを終了するには「Garmin Deskを終了」または⌘Qを選んでください。",
        "menu.about": "Garmin Deskについて",
        "menu.hideApp": "Garmin Deskを非表示",
        "menu.hideOthers": "ほかを非表示",
        "menu.showAll": "すべてを表示",
        "menu.file": "ファイル",
        "menu.closeWindow": "ウインドウを閉じる",
        "menu.window": "ウインドウ",
        "menu.mainWindow": "Garmin Desk",
        "menu.minimize": "しまう",
        "menu.zoom": "拡大／縮小",
        "category.health": "健康と回復",
        "category.sleep": "睡眠",
        "category.activity": "日々のアクティビティ",
        "category.training": "トレーニング",
        "category.body": "体と水分補給",
        "metric.steps": "歩数",
        "metric.stepGoal": "目標歩数",
        "metric.distance": "距離",
        "metric.calories": "総消費カロリー",
        "metric.activeCalories": "活動消費カロリー",
        "metric.floors": "上昇階数",
        "metric.intensityMinutes": "運動量（分）",
        "metric.restingHeartRate": "安静時心拍数",
        "metric.heartRate": "最新の心拍数",
        "metric.stress": "一日の平均ストレス",
        "metric.bodyBattery": "Body Battery",
        "metric.sleepDuration": "睡眠時間",
        "metric.sleepScore": "睡眠スコア",
        "metric.deepSleep": "深い睡眠",
        "metric.remSleep": "レム睡眠",
        "metric.lightSleep": "浅い睡眠",
        "metric.awakeSleep": "覚醒時間",
        "metric.hrv": "夜間HRV",
        "metric.spo2": "一日の平均SpO₂",
        "metric.respiration": "睡眠中の平均呼吸数",
        "metric.trainingReadiness": "トレーニングレディネス",
        "metric.recoveryTime": "リカバリータイム",
        "metric.vo2Max": "ランニングVO₂ max",
        "metric.trainingLoad": "短期的負荷",
        "metric.weight": "体重",
        "metric.hydration": "水分補給",
        "metric.short.sleepDuration": "睡眠",
        "metric.short.stress": "ストレス・日平均",
        "metric.short.restingHeartRate": "安静時心拍",
        "metric.short.trainingReadiness": "レディネス",
        "metric.short.hrv": "HRV・夜間",
        "metric.short.respiration": "呼吸数・睡眠",
        "metric.short.intensityMinutes": "運動量（分）",
        "metric.short.activeCalories": "活動カロリー",
        "metric.short.recoveryTime": "回復",
        "metric.short.trainingLoad": "短期的負荷",
        "metric.short.vo2Max": "ランVO₂ max",
        "metric.short.calories": "総カロリー",
        "unit.minutes": "分",
        "unit.hours": "時間",
        "unit.km": "km",
        "unit.kg": "kg",
        "unit.ml": "ml",
        "unit.bpm": "拍/分",
        "unit.kcal": "kcal",
        "unit.ms": "ms",
        "unit.breaths": "回/分",
        "unit.vo2": "ml/kg/分",
        "error.auth": "サインインできませんでした。入力内容を確認して、もう一度お試しください。",
        "error.rate_limit": "Garminが一時的にリクエストを制限しています。しばらくしてからお試しください。",
        "error.session_unsupported": "保存されたセッションを復元できません。Garminアカウントを再接続してください。",
        "error.access_denied": "要求したデータへのアクセスがGarminに拒否されました。",
        "error.security_challenge": "Garminのセキュリティ確認により接続がブロックされました。しばらくしてからお試しください。",
        "error.network": "Garminに接続できませんでした。インターネット接続を確認してください。",
        "error.dependency": "Garmin接続コンポーネントを利用できません。最新版のGarmin Deskを再インストールしてください。",
        "error.unknown": "リクエストを完了できませんでした。もう一度お試しください。",
        "error.timeout": "Garminから時間内に応答がありませんでした。もう一度お試しください。",
        "error.keychain": "macOSキーチェーンにアクセスできませんでした。ロックが解除されているか確認してください。",
        "error.protocol": "Garminから読み取れないデータが返されました。しばらくしてからお試しください。",
        "error.storage": "このMacにデータを保存できませんでした。空き容量とアクセス権を確認してください。",
        "error.login_item": "macOSの「システム設定」→「一般」→「ログイン項目」でGarmin Deskの自動起動を許可してください。",
        "training.title": "トレーニング",
        "training.last": "前回の完了記録",
        "training.next": "次の予定",
        "training.completed": "完了",
        "training.planned": "予定済み",
        "training.recent": "最近のアクティビティ",
        "training.upcoming": "今後のワークアウト",
        "training.workout": "ワークアウト",
        "training.dateUnknown": "日付は未指定",
        "training.timeUnknown": "時刻は未指定",
        "training.localTime": "記録された現地時刻",
        "training.durationUnknown": "所要時間は未指定",
        "training.pastUnavailable": "履歴はまだ利用できません",
        "training.pastUnavailableHint": "この項目はまだGarminから正常に取得できていません。",
        "training.pastEmpty": "最新の応答にアクティビティはありません",
        "training.pastCoverage": "最近の最大20件・全履歴ではありません",
        "training.futureUnavailable": "予定はまだ利用できません",
        "training.futureUnavailableHint": "カレンダーが利用できなくても、ワークアウトがないとは限りません。",
        "training.futureEmpty": "取得した範囲にワークアウトはありません",
        "training.calendar": "公開済みのGarminカレンダー",
        "training.adaptive": "確認済みの適応型カレンダー",
        "training.partial": "カレンダーの一部を利用できません",
        "training.expiredCoverage": "確認済みの期間が終了しました",
        "training.refreshCalendar": "更新して新しい期間を確認してください。",
        "training.updated": "更新日時",
        "training.updatedUnknown": "更新日時は不明",
        "training.cached": "保存済みデータ",
        "training.refreshFailed": "この項目を更新できませんでした",
        "training.rateLimit": "Garminがリクエストを一時制限中",
        "training.signIn": "更新するにはGarmin Connectにサインイン",
        "training.hour": "時間",
        "training.minute": "分",
        "training.second": "秒",
        "training.km": "km",
        "training.sport.running": "ランニング",
        "training.sport.trail_running": "トレイルラン",
        "training.sport.treadmill_running": "トレッドミルラン",
        "training.sport.track_running": "トラックラン",
        "training.sport.cycling": "サイクリング",
        "training.sport.mountain_biking": "オフロードサイクリング",
        "training.sport.indoor_cycling": "屋内サイクリング",
        "training.sport.swimming": "スイム",
        "training.sport.open_water_swimming": "オープンウォータースイム",
        "training.sport.walking": "ウォーキング",
        "training.sport.hiking": "ハイキング",
        "training.sport.strength_training": "筋力トレーニング",
        "training.sport.cardio_training": "有酸素運動",
        "training.sport.elliptical": "エリプティカル",
        "training.sport.stair_climbing": "階段昇降",
        "training.sport.yoga": "ヨガ",
        "training.sport.pilates": "ピラティス",
        "training.sport.rowing": "ローイング",
        "training.sport.tennis": "テニス",
        "training.sport.golf": "ゴルフ",
        "training.sport.alpine_skiing": "アルペンスキー",
        "training.sport.cross_country_skiing": "クロスカントリースキー",
        "training.sport.snowboarding": "スノーボード",
        "training.sport.triathlon": "マルチスポーツ",
        "training.noPublishedThrough": "%@までの公開済みワークアウトはありません",
        "training.checkedThrough": "%@まで確認済み",
    ]
}
