import Foundation

/// Metric explanations in nl. Garmin payload codes are never translated here.
enum LocalizationExplanationNL {
    static let strings: [String: String] = [
        "explanation.load.rangeUnavailable": "Persoonlijk bereik ontbreekt",
        "explanation.load.ratio.low": "Lage belastingsverhouding",
        "explanation.load.ratio.optimal": "Optimale belastingsverhouding",
        "explanation.load.ratio.high": "Hoge belastingsverhouding",
        "explanation.load.ratio.veryHigh": "Zeer hoge belastingsverhouding",
        "explanation.load.ratio.value": "Acuut / chronisch: %@",
        "explanation.load.below": "Onder het optimale bereik",
        "explanation.load.above": "Boven het optimale bereik",
        "explanation.load.optimal": "Binnen het optimale bereik",
        "explanation.load.range": "Jouw bereik: %1$@–%2$@",
        "explanation.load.detail": "Acute belasting schat de inspanning van recente trainingen. Garmin weegt recentere sessies zwaarder en vergelijkt het resultaat met een bereik op basis van je conditie en trainingsgeschiedenis. Het getal alleen zegt niet of je training productief is.",
        "explanation.load.ratio.detail": "De verhouding vergelijkt recente acute belasting met chronische belasting over een langere periode. Garmin geeft deze categorie los van de trainingsstatus.",
        "explanation.load.garminStatus": "Garmin-status: %@",
        "explanation.load.noStatusDetail": "De trainingsstatus houdt ook rekening met conditieverloop en herstel. Lage belasting alleen betekent geen conditieverlies. Garmin heeft voor deze meting geen herkende trainingsstatus aangeleverd.",
        "explanation.hrv.compare": "Vergelijk met je eigen basisbereik",
        "explanation.hrv.balanced": "Gebalanceerde wekelijkse HRV",
        "explanation.hrv.unbalanced": "Ongebalanceerde wekelijkse HRV",
        "explanation.hrv.low": "Lage wekelijkse HRV",
        "explanation.hrv.poor": "Slechte HRV-status",
        "explanation.hrv.insufficient": "Te weinig recente HRV-gegevens",
        "explanation.hrv.weekly": "7-daags gemiddelde: %1$@ %2$@",
        "explanation.hrv.baseline": "Jouw basisbereik: %1$@–%2$@ %3$@",
        "explanation.hrv.detail": "De waarde is de gemiddelde variatie van hartslagintervallen in de vastgelegde nacht. Garmin vergelijkt het 7-daags gemiddelde met je basisbereik uit ongeveer drie weken slaapgegevens. ‘%@’ verwijst juist naar HRV ver onder de leeftijdsgebonden referentie. Eén nacht is niet de weekstatus; hoger is niet altijd beter.",
        "explanation.readiness.prime": "Optimale trainingsbereidheid",
        "explanation.readiness.high": "Hoge trainingsbereidheid",
        "explanation.readiness.moderate": "Matige trainingsbereidheid",
        "explanation.readiness.low": "Lage trainingsbereidheid",
        "explanation.readiness.poor": "Zeer lage trainingsbereidheid",
        "explanation.readiness.detail": "Garmin combineert slaap, hersteltijd, HRV, acute belasting en recente stress. Schaal: 1–24 zeer laag, 25–49 laag, 50–74 matig, 75–94 hoog, 95–100 optimaal. Een lage score wijst op meer herstelbehoefte; een hoge op meer ruimte voor een zware training.",
        "explanation.sleep.excellent": "Uitstekende slaap",
        "explanation.sleep.good": "Goede slaap",
        "explanation.sleep.fair": "Redelijke slaap",
        "explanation.sleep.poor": "Slechte slaap",
        "explanation.sleep.detail": "Beoordeling van slaapkwaliteit en herstel op basis van duur, slaapfasen en onrust. Garmin-schaal: onder 60 slecht, 60–79 redelijk, 80–89 goed, 90–100 uitstekend. De duur alleen bepaalt de score niet.",
        "explanation.stress.resting": "Rustbereik",
        "explanation.stress.low": "Lage stress",
        "explanation.stress.medium": "Gemiddelde stress",
        "explanation.stress.high": "Hoge stress",
        "explanation.stress.detail": "Gemiddelde lichamelijke stress van de dag volgens Garmin, geen directe meting van emoties. De schaal gebruikt hartslagvariabiliteit: 0–25 rust, 26–50 laag, 51–75 gemiddeld, 76–100 hoog. Een daggemiddelde kan korte pieken en rustperioden verbergen.",
        "explanation.battery.veryLow": "Zeer lage energiereserve",
        "explanation.battery.low": "Lage energiereserve",
        "explanation.battery.moderate": "Gemiddelde energiereserve",
        "explanation.battery.high": "Hoge energiereserve",
        "explanation.battery.detail": "Garmin schat beschikbare energie uit stress, hartslagvariabiliteit, slaap en activiteit. Rust kan die aanvullen; stress en activiteit kunnen die verbruiken. Dit is een energieschatting, geen percentage van je conditie.",
        "explanation.recovery.complete": "Hersteltijd verstreken",
        "explanation.recovery.remaining": "Tot de volgende zware training",
        "explanation.recovery.detail": "Garmin schat de tijd tot je weer klaar bent voor een zware training. Dit vereist geen volledige inactiviteit. Slaap, stress en volgende activiteiten kunnen de schatting veranderen. De laatst ontvangen Garmin-waarde wordt getoond.",
        "explanation.vo2.status": "Schatting van aerobe conditie",
        "explanation.vo2.detail": "Geschatte maximale zuurstofopname per kilogram per minuut. Garmin-categorieën hangen af van leeftijd en geslacht; de app ontvangt te weinig profielgegevens om er één toe te kennen. Vergelijk je verloop onder vergelijkbare omstandigheden, niet één los getal.",
        "explanation.restingHR.status": "Volg je persoonlijke verloop",
        "explanation.restingHR.detail": "Garmins dagelijkse rusthartslag. Vergelijk meerdere dagen met je gebruikelijke niveau. Conditie, slaap, stress en herstel hebben invloed; lager is niet altijd beter.",
        "explanation.oxygen.status": "Gemiddelde zuurstofschatting",
        "explanation.oxygen.detail": "Door het horloge geschatte zuurstofverzadiging van het bloed. Meetomstandigheden en hoogte beïnvloeden het resultaat. Een daggemiddelde beoordeelt geen gezondheid en toont geen korte nachtelijke veranderingen.",
        "explanation.respiration.status": "Gemiddelde tijdens de slaap",
        "explanation.respiration.detail": "Gemiddeld aantal ademhalingen per minuut tijdens de slaap. Vergelijk je nachten en het langere verloop; dit is niet je huidige ademhalingsfrequentie.",
        "explanation.sleepDuration.status": "Totale slaaptijd",
        "explanation.sleepDuration.detail": "Tijd die Garmin in de vastgelegde nacht als slaap indeelde: lichte, diepe en REM-slaap. Kijk naast de duur ook naar de slaapscore en hoe uitgerust je je voelt.",
        "explanation.sleepStage.awake": "Wakker tijdens de slaapperiode",
        "explanation.sleepStage.status": "Deel van de vastgelegde nacht",
        "explanation.sleepStage.detail": "Garmin schat slaapfasen met sensoren. De duur verschilt per nacht; één waarde heeft geen universele goede of slechte grens. Bekijk totale slaap, slaapscore en meerdere nachten samen.",
        "explanation.steps.status": "Dagelijkse loopactiviteit",
        "explanation.steps.reached": "Dagdoel bereikt",
        "explanation.steps.progress": "Op weg naar je dagdoel",
        "explanation.steps.goalDetail": "Stappen vergeleken met je persoonlijke Garmin-dagdoel. Het doel is een streefwaarde, geen universele maat voor conditie.",
        "explanation.steps.goal": "Doel: %@",
        "explanation.steps.detail": "Stappen vastgelegd voor deze dag. Voor het beoordelen van voortgang is een persoonlijk stappendoel nodig.",
        "explanation.stepsTarget.status": "Jouw Garmin-dagdoel",
        "explanation.stepsTarget.detail": "Het handmatig ingestelde of door Garmin aangepaste stappendoel. Het is persoonlijk en kan dagelijks veranderen.",
        "explanation.intensity.status": "Gewogen activiteitsminuten",
        "explanation.intensity.detail": "Garmin telt matige activiteitsminuten en telt intensieve minuten dubbel. Het dagtotaal kan langer zijn dan de training; het is niet je weektotaal.",
        "explanation.calories.status": "Rustenergie + actieve energie",
        "explanation.calories.detail": "Geschat totaal energieverbruik van de dag, inclusief ruststofwisseling en activiteit. Dit is verbruik, geen voedselinname of calorietekort.",
        "explanation.activeCalories.status": "Energie door activiteit",
        "explanation.activeCalories.detail": "Geschat energieverbruik door activiteit bovenop de rustbehoefte. Dit zit al in de totale calorieën; tel beide niet op.",
        "explanation.distance.status": "Dagelijks afgelegde afstand",
        "explanation.distance.detail": "Afstand uit Garmins dagoverzicht. Dit is de totale dagelijkse activiteit, niet noodzakelijk de afstand van je laatste training.",
        "explanation.floors.status": "Verdiepingen omhoog",
        "explanation.floors.detail": "Garmins schatting van de omhooggelopen verdiepingen van de dag. Dit gaat om stijgen, niet om afgedaalde trappen.",
        "explanation.weight.status": "Laatst vastgelegde meting",
        "explanation.weight.detail": "De nieuwste beschikbare gewichtsmeting voor deze registratie. Losse veranderingen kunnen samenhangen met vochtbalans en meettijd. Gewicht alleen bepaalt geen conditie of gezondheid.",
        "explanation.hydration.status": "Vastgelegde vochtinname",
        "explanation.hydration.detail": "Vochtinname ingevoerd in Garmin Connect. Dit zijn jouw registraties, geen sensormeting van hydratatie of je persoonlijke dagelijkse behoefte.",
        "explanation.training.DETRAINING.title": "Onttraining",
        "explanation.training.DETRAINING.detail": "Garmin ziet een afnemende conditie na langdurig minder trainen.",
        "explanation.training.RECOVERY.title": "Herstel",
        "explanation.training.RECOVERY.detail": "Lichter trainen maakt herstel van zware inspanning mogelijk.",
        "explanation.training.MAINTAINING.title": "Behoud",
        "explanation.training.MAINTAINING.detail": "De huidige training houdt de conditie op peil zonder duidelijke verbetering.",
        "explanation.training.PRODUCTIVE.title": "Productief",
        "explanation.training.PRODUCTIVE.detail": "Garmin ziet een betere conditie door de huidige training.",
        "explanation.training.PEAKING.title": "Piekvorm",
        "explanation.training.PEAKING.detail": "Lagere belasting heeft herstel en een korte prestatiepiek mogelijk gemaakt.",
        "explanation.training.OVERREACHING.title": "Overbelasting",
        "explanation.training.OVERREACHING.detail": "Garmin beoordeelt je trainingsbelasting als zeer hoog en contraproductief.",
        "explanation.training.UNPRODUCTIVE.title": "Onproductief",
        "explanation.training.UNPRODUCTIVE.detail": "De conditie neemt af ondanks voldoende belasting; slaap, voeding en stress tellen ook mee.",
        "explanation.training.STRAINED.title": "Overbelast",
        "explanation.training.STRAINED.detail": "Garmin ziet een verstoorde balans tussen training en herstel.",
        "explanation.training.NO_STATUS.title": "Geen status",
        "explanation.training.NO_STATUS.detail": "Garmin heeft nog niet genoeg geschikte trainingsgegevens verzameld.",
        "explanation.training.PAUSED.title": "Gepauzeerd",
        "explanation.training.PAUSED.detail": "De beoordeling van de trainingsstatus is in Garmin gepauzeerd.",
        "explanation.help": "Wat betekent dit?",
        "explanation.source": "Meer uitleg van Garmin",
        "explanation.forecast": "Lokale lineaire schatting uit recente Garmin-metingen. %@",
        "explanation.labeledDetail": "%1$@: %2$@",
    ]
}
