import Foundation

/// Metric explanations in fr. Garmin payload codes are never translated here.
enum LocalizationExplanationFR {
    static let strings: [String: String] = [
        "explanation.load.rangeUnavailable": "Plage personnelle indisponible",
        "explanation.load.ratio.low": "Ratio de charge faible",
        "explanation.load.ratio.optimal": "Ratio de charge optimal",
        "explanation.load.ratio.high": "Ratio de charge élevé",
        "explanation.load.ratio.veryHigh": "Ratio de charge très élevé",
        "explanation.load.ratio.value": "Aiguë / chronique : %@",
        "explanation.load.below": "Sous la plage optimale",
        "explanation.load.above": "Au-dessus de la plage optimale",
        "explanation.load.optimal": "Dans la plage optimale",
        "explanation.load.range": "Votre plage : %1$@–%2$@",
        "explanation.load.detail": "La charge aiguë estime l'effort des entraînements récents. Garmin donne plus de poids aux séances récentes et compare le résultat à une plage fondée sur votre forme et votre historique. Ce nombre seul ne dit pas si l'entraînement est productif.",
        "explanation.load.ratio.detail": "Le ratio compare la charge aiguë récente à la charge chronique à plus long terme. Garmin fournit cette catégorie séparément du statut d'entraînement.",
        "explanation.load.garminStatus": "Statut Garmin : %@",
        "explanation.load.noStatusDetail": "Le statut d'entraînement tient aussi compte de l'évolution de la forme et de la récupération. Une charge faible seule ne signifie pas un désentraînement. Aucun statut Garmin reconnu n'est disponible pour cette mesure.",
        "explanation.hrv.compare": "À comparer à votre référence",
        "explanation.hrv.balanced": "VFC hebdomadaire équilibrée",
        "explanation.hrv.unbalanced": "VFC hebdomadaire déséquilibrée",
        "explanation.hrv.low": "VFC hebdomadaire basse",
        "explanation.hrv.poor": "Statut VFC médiocre",
        "explanation.hrv.insufficient": "Données VFC récentes insuffisantes",
        "explanation.hrv.weekly": "Moyenne sur 7 jours : %1$@ %2$@",
        "explanation.hrv.baseline": "Votre référence : %1$@–%2$@ %3$@",
        "explanation.hrv.detail": "La valeur est la variation moyenne des intervalles entre battements de la nuit enregistrée. Garmin compare la moyenne sur 7 jours à votre référence, établie avec environ trois semaines de sommeil. « %@ » indique plutôt une VFC bien en dessous de la plage liée à l'âge. Une nuit n'est pas le statut hebdomadaire ; plus haut n'est pas toujours mieux.",
        "explanation.readiness.prime": "Préparation optimale",
        "explanation.readiness.high": "Préparation élevée",
        "explanation.readiness.moderate": "Préparation modérée",
        "explanation.readiness.low": "Préparation faible",
        "explanation.readiness.poor": "Préparation très faible",
        "explanation.readiness.detail": "Garmin combine sommeil, récupération, VFC, charge aiguë et stress récent. Échelle : 1–24 très faible, 25–49 faible, 50–74 modérée, 75–94 élevée, 95–100 optimale. Un score bas suggère de privilégier la récupération ; un score haut indique davantage de ressources pour une séance exigeante.",
        "explanation.sleep.excellent": "Sommeil excellent",
        "explanation.sleep.good": "Bon sommeil",
        "explanation.sleep.fair": "Sommeil passable",
        "explanation.sleep.poor": "Sommeil médiocre",
        "explanation.sleep.detail": "Résumé de la qualité du sommeil et de la récupération, selon la durée, les phases et l'agitation. Échelle Garmin : moins de 60 médiocre, 60–79 passable, 80–89 bon, 90–100 excellent. La durée seule ne détermine pas le score.",
        "explanation.stress.resting": "Plage de repos",
        "explanation.stress.low": "Stress faible",
        "explanation.stress.medium": "Stress moyen",
        "explanation.stress.high": "Stress élevé",
        "explanation.stress.detail": "Stress physiologique moyen du jour selon Garmin, pas une mesure instantanée des émotions. L'échelle utilise la variabilité cardiaque : 0–25 repos, 26–50 faible, 51–75 moyen, 76–100 élevé. La moyenne peut masquer les pics brefs et les périodes de repos.",
        "explanation.battery.veryLow": "Réserve d'énergie très faible",
        "explanation.battery.low": "Réserve d'énergie faible",
        "explanation.battery.moderate": "Réserve d'énergie modérée",
        "explanation.battery.high": "Réserve d'énergie élevée",
        "explanation.battery.detail": "Garmin estime l'énergie disponible à partir du stress, de la variabilité cardiaque, du sommeil et de l'activité. Le repos peut la recharger ; le stress et l'activité peuvent l'épuiser. C'est une estimation d'énergie, pas un pourcentage de forme physique.",
        "explanation.recovery.complete": "Compte à rebours terminé",
        "explanation.recovery.remaining": "Avant la prochaine séance intense",
        "explanation.recovery.detail": "Garmin estime le temps avant d'être prêt pour une autre séance intense. Cela n'impose pas une inactivité complète. Le sommeil, le stress et l'activité suivante peuvent modifier l'estimation. La valeur est la dernière reçue de Garmin.",
        "explanation.vo2.status": "Estimation de la forme aérobie",
        "explanation.vo2.detail": "Estimation de la consommation maximale d'oxygène par kilogramme et par minute. Les catégories Garmin dépendent de l'âge et du sexe ; l'app ne dispose pas du profil nécessaire pour en attribuer une. Comparez votre évolution dans des conditions similaires plutôt qu'un nombre isolé.",
        "explanation.restingHR.status": "Suivez votre propre évolution",
        "explanation.restingHR.detail": "Fréquence cardiaque au repos quotidienne selon Garmin. Comparez plusieurs jours à votre niveau habituel. Forme, sommeil, stress et récupération l'influencent ; plus bas ne signifie pas toujours mieux.",
        "explanation.oxygen.status": "Estimation moyenne de l'oxygène",
        "explanation.oxygen.detail": "Estimation par la montre de la saturation du sang en oxygène. Les conditions de mesure et l'altitude influencent le résultat. Une moyenne quotidienne ne permet pas d'évaluer la santé ni de voir les variations nocturnes brèves.",
        "explanation.respiration.status": "Moyenne pendant le sommeil",
        "explanation.respiration.detail": "Nombre moyen de respirations par minute pendant le sommeil. Comparez vos nuits et l'évolution à long terme ; ce n'est pas votre fréquence respiratoire actuelle.",
        "explanation.sleepDuration.status": "Durée totale du sommeil",
        "explanation.sleepDuration.detail": "Temps classé comme sommeil par Garmin pendant la nuit enregistrée : sommeil léger, profond et paradoxal. Considérez aussi le score de sommeil et votre sensation de repos.",
        "explanation.sleepStage.awake": "Éveil pendant la période de sommeil",
        "explanation.sleepStage.status": "Partie de la nuit enregistrée",
        "explanation.sleepStage.detail": "Garmin estime les phases du sommeil à partir des capteurs. Leur durée varie selon la nuit ; une valeur isolée n'a pas de seuil universel bon ou mauvais. Comparez-la au sommeil total, au score et à plusieurs nuits.",
        "explanation.steps.status": "Marche quotidienne",
        "explanation.steps.reached": "Objectif quotidien atteint",
        "explanation.steps.progress": "Vers votre objectif quotidien",
        "explanation.steps.goalDetail": "Nombre de pas comparé à votre objectif Garmin personnel. L'objectif est une cible, pas une mesure universelle de la forme.",
        "explanation.steps.goal": "Objectif : %@",
        "explanation.steps.detail": "Pas enregistrés pour ce jour. Un objectif personnel est nécessaire pour évaluer la progression.",
        "explanation.stepsTarget.status": "Votre objectif quotidien Garmin",
        "explanation.stepsTarget.detail": "Objectif de pas défini manuellement ou ajusté automatiquement par Garmin. Il est personnel et peut varier d'un jour à l'autre.",
        "explanation.intensity.status": "Minutes d'activité pondérées",
        "explanation.intensity.detail": "Garmin compte les minutes d'activité modérée et double celles d'activité intense. Le total quotidien peut dépasser la durée de la séance ; ce n'est pas le total hebdomadaire.",
        "explanation.calories.status": "Énergie au repos + activité",
        "explanation.calories.detail": "Dépense énergétique totale estimée du jour, métabolisme au repos et activité compris. Il s'agit de dépense, pas d'apport alimentaire ni de déficit calorique.",
        "explanation.activeCalories.status": "Énergie liée à l'activité",
        "explanation.activeCalories.detail": "Dépense énergétique estimée par l'activité au-delà du repos. Elle est déjà incluse dans les calories totales : il ne faut pas additionner les deux.",
        "explanation.distance.status": "Distance quotidienne parcourue",
        "explanation.distance.detail": "Distance du résumé quotidien Garmin. C'est le total d'activité de la journée, pas nécessairement la distance de votre dernière séance.",
        "explanation.floors.status": "Étages montés",
        "explanation.floors.detail": "Estimation Garmin des étages montés dans la journée. Elle représente la montée, pas les escaliers descendus.",
        "explanation.weight.status": "Dernière mesure enregistrée",
        "explanation.weight.detail": "Dernière mesure de poids disponible pour cet enregistrement. Une variation peut venir de l'équilibre hydrique ou de l'heure de mesure. Le poids seul ne détermine ni la forme ni la santé.",
        "explanation.hydration.status": "Boissons enregistrées",
        "explanation.hydration.detail": "Liquides consignés dans Garmin Connect. Ce sont vos saisies, pas une mesure de l'hydratation par capteur ni votre besoin quotidien personnel.",
        "explanation.training.DETRAINING.title": "Désentraînement",
        "explanation.training.DETRAINING.detail": "Garmin détecte une baisse de forme après une réduction prolongée de l'entraînement.",
        "explanation.training.RECOVERY.title": "Récupération",
        "explanation.training.RECOVERY.detail": "Un entraînement allégé permet de récupérer d'efforts exigeants.",
        "explanation.training.MAINTAINING.title": "Maintien",
        "explanation.training.MAINTAINING.detail": "L'entraînement actuel maintient la forme sans amélioration nette.",
        "explanation.training.PRODUCTIVE.title": "Productif",
        "explanation.training.PRODUCTIVE.detail": "Garmin détecte une amélioration de la forme avec l'entraînement actuel.",
        "explanation.training.PEAKING.title": "Pic de forme",
        "explanation.training.PEAKING.detail": "La baisse de charge a permis la récupération et un pic de performance temporaire.",
        "explanation.training.OVERREACHING.title": "Effort excessif",
        "explanation.training.OVERREACHING.detail": "Garmin classe votre charge d'entraînement comme très élevée et contre-productive.",
        "explanation.training.UNPRODUCTIVE.title": "Non productif",
        "explanation.training.UNPRODUCTIVE.detail": "La forme baisse malgré une charge suffisante ; sommeil, alimentation et stress comptent aussi.",
        "explanation.training.STRAINED.title": "Sous tension",
        "explanation.training.STRAINED.detail": "Garmin détecte un déséquilibre entre entraînement et récupération.",
        "explanation.training.NO_STATUS.title": "Aucun statut",
        "explanation.training.NO_STATUS.detail": "Garmin n'a pas encore assez de données d'entraînement admissibles.",
        "explanation.training.PAUSED.title": "En pause",
        "explanation.training.PAUSED.detail": "L'évaluation du statut d'entraînement est suspendue dans Garmin.",
        "explanation.help": "Que signifie cette mesure ?",
        "explanation.source": "En savoir plus avec Garmin",
        "explanation.forecast": "Estimation linéaire locale à partir des dernières mesures Garmin. %@",
        "explanation.labeledDetail": "%1$@ : %2$@",
    ]
}
