// Full application and widget catalog. Keep keys aligned with the English catalog.
enum LocalizationIT {
    static let strings: [String: String] = [
        "widget.summary.minimum": "Mantieni almeno una misurazione selezionata.",
        "widget.summary.hint": "Vengono mostrate solo le misurazioni selezionate con dati disponibili. Il loro numero dipende dalle dimensioni del widget.",
        "widget.summary.primary": "Misurazione principale preferita",
        "widget.summary.choose": "Scegli le misurazioni",
        "settings.widgets": "Widget",
        "settings.widgetsSubtitle": "Cinque widget pronti per la tua scrivania.",
        "widget.type": "Tipo di widget",
        "widget.appearance": "Aspetto dei widget",
        "widget.appearance.colorful": "Colorato",
        "widget.appearance.light": "Chiaro",
        "widget.appearance.dark": "Scuro",
        "widget.appearanceHint": "Un unico aspetto per tutti e cinque i widget della scrivania.",
        "widget.automaticHint": "Le misurazioni disponibili vengono selezionate automaticamente.",
        "widget.guide.fixedTypes": "Scegli il tipo e la dimensione del widget, poi aggiungilo alla scrivania.",
        "widget.slot.day": "Giornata",
        "widget.slot.day.description": "Body Battery, passi, stress e attività quotidiana.",
        "onboarding.title": "I tuoi dati Garmin sul Mac",
        "onboarding.privacy": "Le misurazioni vengono salvate su questo Mac",
        "onboarding.detail": "Collega il tuo account Garmin per vedere le misurazioni qui e nei widget sulla scrivania.",
        "data.available": "Ultime misurazioni",
        "data.nightEnding": "Notte terminata il",
        "data.measured": "Misurato",
        "data.received": "Ricevuto",
        "metric.short.spo2": "SpO₂ · media giorn.",
        "data.waiting": "In attesa dei dati dell’orologio",
        "data.waitingNew": "In attesa di nuove misurazioni",
        "data.unchanged": "Nessuna variazione nelle misurazioni",
        "data.checkFailed": "Impossibile aggiornare i dati Garmin",
        "data.unchangedHint": "Ti aspettavi misurazioni più recenti? Apri Garmin Connect sul telefono e sincronizza l’orologio. Le riceveremo automaticamente.",
        "data.retainedAllHint": "Qui sotto trovi le ultime misurazioni con le relative date. Apri Garmin Connect sul telefono e sincronizza l’orologio per ottenere dati più recenti.",
        "data.previous": "Ultimi dati disponibili",
        "data.retainedHint": "Alcune misurazioni non sono ancora arrivate. Abbiamo mantenuto gli ultimi valori con le relative date. Sincronizza l’orologio in Garmin Connect sul telefono.",
        "data.waitingHint": "Apri Garmin Connect sul telefono e sincronizza l’orologio. Le misurazioni appariranno qui automaticamente.",
        "widget.notice.connection": "Ricollega Garmin",
        "widget.notice.unavailable": "Aggiornamento non riuscito",
        "widget.notice.waiting": "In attesa di nuovi dati",
        "widget.waiting": "In attesa di dati",
        "widget.waitingHint": "Sincronizza l’orologio in Garmin Connect sul telefono. Le misurazioni appariranno qui automaticamente.",
        "widget.previous": "Ultimi dati disponibili",
        "widget.slot.overview.description": "Le misurazioni che scegli in un unico widget.",
        "widget.slot.sport.description": "Preparazione all’allenamento, recupero, carico e VO₂ max.",
        "widget.slot.sleep.description": "Durata e punteggio del sonno, HRV notturna.",
        "widget.slot.training.description": "Un calendario delle attività completate e degli allenamenti programmati.",
        "widget.preview.easyRun": "Corsa leggera",
        "widget.preview.intervals": "Corsa a intervalli",
        "profile.availableMetrics": "Usa le misurazioni disponibili",
        "profile.availableMetricsHint": "Salta le misurazioni mancanti e completa il widget con metriche correlate. Disattiva per mantenere esattamente la tua selezione.",
        "profile.content": "Contenuto",
        "content.metrics": "Metriche",
        "content.training": "Calendario degli allenamenti",
        "content.mixed": "Entrambi",
        "profile.previewMetricsOnly": "Questa anteprima mostra le metriche. Le schede degli allenamenti appaiono anche nella sezione Panoramica.",
        "status.signInRequired": "Accesso richiesto",
        "connection.retryAfter": "Riprova dopo",
        "connection.reconnectDetail": "Apri la finestra Garmin e completa l’accesso per riprendere gli aggiornamenti.",
        "widget.guide.staticProfile": "Scegli il tipo e la dimensione del widget, poi aggiungilo alla scrivania.",
        "widget.guide.unavailable": "Visualizza le misurazioni e le anteprime dei widget nell’app.",
        "widget.sharingDataUnavailable": "I dati dei widget non sono ancora disponibili. Puoi comunque visualizzare le misurazioni nell’app.",
        "widget.slot.overview": "Riepilogo",
        "widget.slot.sport": "Sport",
        "widget.slot.sleep": "Sonno",
        "widget.slot.training": "Calendario allenamenti",
        "widget.slot.firstProfile": "Primo profilo",
        "widget.slot.unassigned": "Scegli un profilo…",
        "profile.templates": "Inizia da un modello",
        "profile.custom": "Profilo personalizzato",
        "profile.template.life": "Vita quotidiana",
        "profile.template.sport": "Sport",
        "profile.template.sleep": "Sonno",
        "profile.previewSize": "Dimensioni del widget",
        "profile.preview.small": "Piccolo",
        "profile.preview.medium": "Medio",
        "profile.preview.large": "Grande",
        "profile.previewCount": "Mostra %d metriche su %d. Tutte le metriche selezionate sono disponibili nella sezione Panoramica.",
        "widget.galleryTitle": "Riepilogo Garmin",
        "widget.galleryDescription": "Salute, sonno, attività e allenamento in cinque widget pronti all’uso.",
        "widget.galleryStaticDescription": "Scegli il tipo e la dimensione del widget. Le misurazioni disponibili appaiono automaticamente.",
        "connection.webTitle": "Collega Garmin",
        "connection.webSubtitle": "Basta collegarsi una volta. Le misurazioni si aggiornano automaticamente.",
        "connection.webIntro": "Accedi a Garmin Connect",
        "connection.webDetail": "Si aprirà una finestra sicura di Garmin. Completa l’accesso e le eventuali verifiche richieste da Garmin. L’app manterrà poi questa connessione sul Mac.",
        "connection.webSignIn": "Accedi con Garmin",
        "connection.webPrivacy": "Le misurazioni e la sessione del sito Garmin restano su questo Mac. La password viene inviata direttamente a Garmin. Non ci sono server separati né analisi dell’utilizzo.",
        "connection.automaticHint": "I dati si aggiornano in background, anche quando il Mac esce dallo stop. Lascia Garmin Desk in esecuzione per gli aggiornamenti automatici.",
        "connection.reconnect": "Ricollega Garmin",
        "connection.nextSync": "Prossimo aggiornamento dopo",
        "error.partial": "Impossibile aggiornare alcune misurazioni. I dati salvati restano disponibili.",
        "diagnostic.title": "Dettagli della connessione",
        "diagnostic.stage": "Fase",
        "diagnostic.apiCode": "Codice Garmin",
        "diagnostic.requests": "Risposte ricevute",
        "menu.edit": "Modifica",
        "menu.cut": "Taglia",
        "menu.copy": "Copia",
        "menu.paste": "Incolla",
        "menu.selectAll": "Seleziona tutto",
        "app.subtitle": "La tua giornata a colpo d’occhio",
        "app.device": "Garmin fēnix 8",
        "dashboard.title": "Panoramica",
        "dashboard.profile": "Profilo",
        "dashboard.moreMetrics": "I widget più grandi possono mostrare più metriche",
        "dashboard.configure": "Impostazioni dei widget",
        "widget.setup": "Configura i widget sulla scrivania",
        "widget.customize": "Impostazioni dei widget",
        "widget.guide.add": "Fai clic con il tasto destro sulla scrivania e scegli Modifica widget. Trova GarminDesk nella galleria.",
        "widget.guide.profile": "Scegli il tipo e la dimensione del widget, poi aggiungilo alla scrivania.",
        "widget.guide.refresh": "Garmin Desk recupera le misurazioni. macOS decide quando aggiornare il widget sulla scrivania.",
        "widget.sharingUnavailable": "I widget della scrivania non sono disponibili in questa versione. Puoi comunque visualizzare le misurazioni nell’app.",
        "widget.openApp": "Apri GarminDesk",
        "widget.openAppHint": "Collega il tuo account Garmin nell’app.",
        "widget.profileMissing": "Profilo eliminato",
        "widget.profileMissingHint": "Scegli un altro profilo nelle impostazioni del widget.",
        "widget.demo": "DEMO",
        "widget.connect": "Collega Garmin nell’app",
        "dashboard.empty": "Scegli nelle impostazioni le metriche da visualizzare.",
        "dashboard.connect": "Collega Garmin",
        "action.settings": "Impostazioni",
        "action.sync": "Aggiorna",
        "action.quit": "Esci da Garmin Desk",
        "action.cancel": "Annulla",
        "action.save": "Salva",
        "action.delete": "Elimina",
        "action.duplicate": "Duplica",
        "action.add": "Aggiungi profilo",
        "action.up": "Sposta su",
        "action.down": "Sposta giù",
        "action.show": "Mostra",
        "action.hide": "Nascondi",
        "action.done": "Fine",
        "action.retry": "Riprova",
        "data.demo": "Dati dimostrativi",
        "data.updated": "Controllato",
        "data.stale": "I dati potrebbero non essere aggiornati",
        "data.day": "Dati del",
        "data.partial": "Alcune misurazioni non sono disponibili",
        "data.emptyDay": "Garmin non ha ancora misurazioni per questa data. Sincronizza l’orologio con Garmin Connect per aggiornarle.",
        "data.empty": "Nessuna misurazione disponibile",
        "data.demoDetail": "Valori di esempio. Collega il tuo account per vedere le tue misurazioni.",
        "data.local": "Salvato su questo Mac",
        "data.source": "Ultima sincronizzazione Garmin Connect",
        "data.syncing": "Controllo di Garmin Connect…",
        "status.connected": "Garmin collegato",
        "status.notConnected": "Garmin non collegato",
        "status.connecting": "Connessione…",
        "settings.title": "Impostazioni",
        "settings.profiles": "Profili dei widget",
        "settings.connection": "Account Garmin",
        "settings.general": "Generali",
        "settings.profilesSubtitle": "Crea una vista per ogni momento della giornata.",
        "settings.generalSubtitle": "Adatta Garmin Desk al tuo Mac.",
        "profile.name": "Nome del profilo",
        "profile.primary": "Metrica principale",
        "profile.metrics": "Metriche",
        "profile.metricsHint": "Scegli cosa visualizzare. La metrica principale appare sempre per prima.",
        "profile.appearance": "Aspetto",
        "profile.style": "Stile",
        "profile.density": "Densità",
        "profile.preview": "Anteprima",
        "profile.added": "Nuovo profilo",
        "profile.new": "Nuovo profilo",
        "profile.default": "La mia giornata",
        "profile.copy": "Copia",
        "profile.untitled": "Profilo senza titolo",
        "profile.deleteTitle": "Eliminare questo profilo?",
        "profile.deleteMessage": "Il profilo verrà rimosso. I dati Garmin resteranno su questo Mac.",
        "profile.oneRequired": "Mantieni almeno un profilo.",
        "profile.enabled": "Incluse",
        "profile.available": "Metriche disponibili",
        "profile.count": "metriche",
        "profile.mainBadge": "Principale",
        "style.calm": "Calmo",
        "style.sport": "Sportivo",
        "style.monochrome": "Monocromatico",
        "density.comfortable": "Comoda",
        "density.compact": "Compatta",
        "connection.title": "Il tuo account Garmin",
        "connection.subtitle": "Il Mac si collega direttamente a Garmin Connect.",
        "connection.localTitle": "I tuoi dati restano con te",
        "connection.localDetail": "Le misurazioni vengono memorizzate nella cache del Mac. Le credenziali di sessione sono salvate nel Portachiavi di macOS. L’app non ha server separati.",
        "connection.email": "Email",
        "connection.password": "Password",
        "connection.china": "Usa Garmin Cina",
        "connection.signIn": "Collega account",
        "connection.disconnect": "Scollega ed elimina i dati locali",
        "connection.disconnectTitle": "Scollegare Garmin?",
        "connection.disconnectMessage": "La sessione Garmin salvata e le misurazioni nella cache verranno eliminate da questo Mac. Le preferenze saranno conservate.",
        "connection.demo": "Esplora con dati dimostrativi",
        "connection.demoHint": "I valori dimostrativi sono sempre contrassegnati.",
        "connection.syncHint": "Sincronizza l’orologio con Garmin Connect per rendere disponibili qui le nuove misurazioni.",
        "connection.secureHint": "La password viene usata solo per accedere e non viene salvata dall’app.",
        "connection.mfaTitle": "Codice di verifica",
        "connection.mfaHint": "Inserisci il codice richiesto da Garmin per completare la connessione.",
        "connection.mfaCode": "Codice",
        "connection.verify": "Verifica",
        "connection.cancelLogin": "Annulla accesso",
        "general.language": "Lingua",
        "general.appearance": "Aspetto",
        "general.refresh": "Intervallo di aggiornamento",
        "general.system": "Segui il sistema",
        "general.light": "Chiaro",
        "general.dark": "Scuro",
        "general.minutes5": "Ogni 5 minuti",
        "general.minutes15": "Ogni 15 minuti",
        "general.minutes30": "Ogni 30 minuti",
        "general.minutes60": "Ogni ora",
        "general.refreshHint": "Gli aggiornamenti usano le ultime misurazioni disponibili in Garmin Connect.",
        "general.localNotice": "Le preferenze vengono salvate automaticamente su questo Mac.",
        "general.launchAtLogin": "Apri Garmin Desk al login",
        "general.backgroundHint": "Gli aggiornamenti automatici continuano quando chiudi la finestra. Scegli «Esci da Garmin Desk» o premi ⌘Q per chiudere l’app.",
        "menu.about": "Informazioni su Garmin Desk",
        "menu.hideApp": "Nascondi Garmin Desk",
        "menu.hideOthers": "Nascondi altre",
        "menu.showAll": "Mostra tutte",
        "menu.file": "File",
        "menu.closeWindow": "Chiudi finestra",
        "menu.window": "Finestra",
        "menu.mainWindow": "Garmin Desk",
        "menu.minimize": "Contrai",
        "menu.zoom": "Ridimensiona",
        "category.health": "Salute e recupero",
        "category.sleep": "Sonno",
        "category.activity": "Attività quotidiana",
        "category.training": "Allenamento",
        "category.body": "Corpo e idratazione",
        "metric.steps": "Passi",
        "metric.stepGoal": "Obiettivo passi",
        "metric.distance": "Distanza",
        "metric.calories": "Calorie totali",
        "metric.activeCalories": "Calorie attive",
        "metric.floors": "Piani saliti",
        "metric.intensityMinutes": "Minuti di intensità",
        "metric.restingHeartRate": "Frequenza cardiaca a riposo",
        "metric.heartRate": "Ultima frequenza cardiaca",
        "metric.stress": "Stress medio giornaliero",
        "metric.bodyBattery": "Body Battery",
        "metric.sleepDuration": "Durata del sonno",
        "metric.sleepScore": "Punteggio del sonno",
        "metric.deepSleep": "Sonno profondo",
        "metric.remSleep": "Sonno REM",
        "metric.lightSleep": "Sonno leggero",
        "metric.awakeSleep": "Tempo di veglia",
        "metric.hrv": "HRV notturna",
        "metric.spo2": "SpO₂ media giornaliera",
        "metric.respiration": "Respirazione media nel sonno",
        "metric.trainingReadiness": "Preparazione all’allenamento",
        "metric.recoveryTime": "Tempo di recupero",
        "metric.vo2Max": "VO₂ max di corsa",
        "metric.trainingLoad": "Carico acuto di allenamento",
        "metric.weight": "Peso",
        "metric.hydration": "Idratazione",
        "metric.short.sleepDuration": "Sonno",
        "metric.short.stress": "Stress · giorno",
        "metric.short.restingHeartRate": "FC a riposo",
        "metric.short.trainingReadiness": "Preparazione",
        "metric.short.hrv": "HRV · notte",
        "metric.short.respiration": "Respir. · sonno",
        "metric.short.intensityMinutes": "Min. di intensità",
        "metric.short.activeCalories": "Calorie attive",
        "metric.short.recoveryTime": "Recupero",
        "metric.short.trainingLoad": "Carico acuto",
        "metric.short.vo2Max": "VO₂ max corsa",
        "metric.short.calories": "Calorie totali",
        "unit.minutes": "min",
        "unit.hours": "h",
        "unit.km": "km",
        "unit.kg": "kg",
        "unit.ml": "ml",
        "unit.bpm": "bpm",
        "unit.kcal": "kcal",
        "unit.ms": "ms",
        "unit.breaths": "resp/min",
        "unit.vo2": "ml/kg/min",
        "error.auth": "Accesso non riuscito. Controlla i dati e riprova.",
        "error.rate_limit": "Garmin ha limitato temporaneamente le richieste. Riprova più tardi.",
        "error.session_unsupported": "L’app non può ripristinare la sessione salvata. Ricollega il tuo account Garmin.",
        "error.access_denied": "Garmin ha negato l’accesso ai dati richiesti.",
        "error.security_challenge": "Un controllo di sicurezza Garmin ha bloccato la connessione. Riprova più tardi.",
        "error.network": "Impossibile contattare Garmin. Controlla la connessione internet.",
        "error.dependency": "Il componente di connessione Garmin non è disponibile. Reinstalla l’ultima versione di Garmin Desk.",
        "error.unknown": "Impossibile completare la richiesta. Riprova.",
        "error.timeout": "Garmin ha impiegato troppo tempo a rispondere. Riprova.",
        "error.keychain": "Impossibile accedere al Portachiavi di macOS. Verifica che sia sbloccato.",
        "error.protocol": "Garmin ha restituito dati che l’app non riesce a leggere. Riprova più tardi.",
        "error.storage": "Impossibile salvare i dati su questo Mac. Controlla lo spazio disponibile e i permessi.",
        "error.login_item": "Consenti a Garmin Desk di aprirsi al login in Impostazioni di macOS → Generali → Elementi login.",
        "training.title": "Allenamento",
        "training.last": "Ultimo completato",
        "training.next": "Prossimo in programma",
        "training.completed": "Completato",
        "training.planned": "Programmato",
        "training.recent": "Attività recenti",
        "training.upcoming": "Prossimi allenamenti",
        "training.workout": "Allenamento",
        "training.dateUnknown": "Data non specificata",
        "training.timeUnknown": "Ora non specificata",
        "training.localTime": "ora locale registrata",
        "training.durationUnknown": "Durata non specificata",
        "training.pastUnavailable": "Cronologia non ancora disponibile",
        "training.pastUnavailableHint": "Non è stato ancora possibile recuperare questa sezione da Garmin.",
        "training.pastEmpty": "Nessuna attività nell’ultima risposta",
        "training.pastCoverage": "Fino a 20 attività recenti · cronologia non completa",
        "training.futureUnavailable": "Programma non ancora disponibile",
        "training.futureUnavailableHint": "Un calendario non disponibile non significa che non ci siano allenamenti.",
        "training.futureEmpty": "Nessun allenamento nella parte recuperata",
        "training.calendar": "Calendario Garmin pubblicato",
        "training.adaptive": "Calendario adattivo verificato",
        "training.partial": "Parte del calendario non è disponibile",
        "training.expiredCoverage": "Il periodo verificato è terminato",
        "training.refreshCalendar": "Aggiorna per verificare un nuovo periodo.",
        "training.updated": "Aggiornato",
        "training.updatedUnknown": "Ora di aggiornamento sconosciuta",
        "training.cached": "Dati salvati",
        "training.refreshFailed": "Impossibile aggiornare questa sezione",
        "training.rateLimit": "Garmin sta limitando temporaneamente le richieste",
        "training.signIn": "Accedi a Garmin Connect per aggiornare",
        "training.hour": "h",
        "training.minute": "min",
        "training.second": "s",
        "training.km": "km",
        "training.sport.running": "Corsa",
        "training.sport.trail_running": "Trail running",
        "training.sport.treadmill_running": "Corsa su tapis roulant",
        "training.sport.track_running": "Corsa su pista",
        "training.sport.cycling": "Ciclismo",
        "training.sport.mountain_biking": "Mountain bike",
        "training.sport.indoor_cycling": "Ciclismo indoor",
        "training.sport.swimming": "Nuoto",
        "training.sport.open_water_swimming": "Nuoto in acque libere",
        "training.sport.walking": "Camminata",
        "training.sport.hiking": "Escursionismo",
        "training.sport.strength_training": "Allenamento di forza",
        "training.sport.cardio_training": "Cardio",
        "training.sport.elliptical": "Ellittica",
        "training.sport.stair_climbing": "Salita scale",
        "training.sport.yoga": "Yoga",
        "training.sport.pilates": "Pilates",
        "training.sport.rowing": "Canottaggio",
        "training.sport.tennis": "Tennis",
        "training.sport.golf": "Golf",
        "training.sport.alpine_skiing": "Sci alpino",
        "training.sport.cross_country_skiing": "Sci di fondo",
        "training.sport.snowboarding": "Snowboard",
        "training.sport.triathlon": "Multisport",
        "training.noPublishedThrough": "Nessun allenamento pubblicato fino al %@",
        "training.checkedThrough": "verificato fino al %@",
    ]
}
