import Foundation

/// Metric explanations in it. Garmin payload codes are never translated here.
enum LocalizationExplanationIT {
    static let strings: [String: String] = [
        "explanation.load.rangeUnavailable": "Intervallo personale non disponibile",
        "explanation.load.ratio.low": "Rapporto di carico basso",
        "explanation.load.ratio.optimal": "Rapporto di carico ottimale",
        "explanation.load.ratio.high": "Rapporto di carico alto",
        "explanation.load.ratio.veryHigh": "Rapporto di carico molto alto",
        "explanation.load.ratio.value": "Acuto / cronico: %@",
        "explanation.load.below": "Sotto l'intervallo ottimale",
        "explanation.load.above": "Sopra l'intervallo ottimale",
        "explanation.load.optimal": "Nell'intervallo ottimale",
        "explanation.load.range": "Il tuo intervallo: %1$@–%2$@",
        "explanation.load.detail": "Il carico acuto stima lo sforzo degli allenamenti recenti. Garmin dà più peso alle sedute recenti e confronta il risultato con un intervallo basato su forma e cronologia. Il numero da solo non indica se l'allenamento è produttivo.",
        "explanation.load.ratio.detail": "Il rapporto confronta il carico acuto recente con il carico cronico a lungo termine. Garmin fornisce questa categoria separatamente dallo stato di allenamento.",
        "explanation.load.garminStatus": "Stato Garmin: %@",
        "explanation.load.noStatusDetail": "Lo stato di allenamento considera anche l'andamento della forma e il recupero. Un carico basso da solo non significa detraining. Garmin non ha fornito uno stato riconosciuto per questo valore.",
        "explanation.hrv.compare": "Confronta con il tuo riferimento",
        "explanation.hrv.balanced": "HRV settimanale bilanciata",
        "explanation.hrv.unbalanced": "HRV settimanale non bilanciata",
        "explanation.hrv.low": "HRV settimanale bassa",
        "explanation.hrv.poor": "Stato HRV scarso",
        "explanation.hrv.insufficient": "Dati HRV recenti insufficienti",
        "explanation.hrv.weekly": "Media di 7 giorni: %1$@ %2$@",
        "explanation.hrv.baseline": "Il tuo riferimento: %1$@–%2$@ %3$@",
        "explanation.hrv.detail": "Il valore indica la variazione media tra i battiti dell'ultima notte. Lo stato HRV Garmin confronta la media di 7 giorni con il riferimento personale, che richiede circa tre settimane di sonno. Una notte non è lo stato settimanale; più alto non è sempre meglio.",
        "explanation.readiness.prime": "Preparazione ottimale",
        "explanation.readiness.high": "Preparazione alta",
        "explanation.readiness.moderate": "Preparazione moderata",
        "explanation.readiness.low": "Preparazione bassa",
        "explanation.readiness.poor": "Preparazione molto bassa",
        "explanation.readiness.detail": "Garmin combina sonno, recupero, HRV, carico acuto e stress recente. Scala: 1–24 molto bassa, 25–49 bassa, 50–74 moderata, 75–94 alta, 95–100 ottimale. Un valore basso suggerisce più recupero; uno alto indica maggiori risorse per una seduta impegnativa.",
        "explanation.sleep.excellent": "Sonno eccellente",
        "explanation.sleep.good": "Buon sonno",
        "explanation.sleep.fair": "Sonno discreto",
        "explanation.sleep.poor": "Sonno scarso",
        "explanation.sleep.detail": "Sintesi della qualità del sonno e del recupero, basata su durata, fasi e irrequietezza. Scala Garmin: meno di 60 scarso, 60–79 discreto, 80–89 buono, 90–100 eccellente. La sola durata non determina il punteggio.",
        "explanation.stress.resting": "Intervallo di riposo",
        "explanation.stress.low": "Stress basso",
        "explanation.stress.medium": "Stress medio",
        "explanation.stress.high": "Stress alto",
        "explanation.stress.detail": "Stress fisiologico medio del giorno secondo Garmin, non una lettura istantanea delle emozioni. La scala usa la variabilità cardiaca: 0–25 riposo, 26–50 basso, 51–75 medio, 76–100 alto. La media può nascondere brevi picchi e periodi di riposo.",
        "explanation.battery.veryLow": "Riserva di energia molto bassa",
        "explanation.battery.low": "Riserva di energia bassa",
        "explanation.battery.moderate": "Riserva di energia moderata",
        "explanation.battery.high": "Riserva di energia alta",
        "explanation.battery.detail": "Garmin stima l'energia disponibile da stress, variabilità cardiaca, sonno e attività. Il riposo può ricaricarla; stress e attività possono consumarla. È una stima dell'energia, non una percentuale della forma fisica.",
        "explanation.recovery.complete": "Conto alla rovescia terminato",
        "explanation.recovery.remaining": "Fino al prossimo allenamento intenso",
        "explanation.recovery.detail": "Garmin stima il tempo prima di un altro allenamento intenso. Non richiede inattività completa. Sonno, stress e attività successive possono modificare la stima. Il valore è l'ultima lettura ricevuta da Garmin.",
        "explanation.vo2.status": "Stima della capacità aerobica",
        "explanation.vo2.detail": "Stima del consumo massimo di ossigeno per chilogrammo al minuto. Le categorie Garmin dipendono da età e sesso; l'app non riceve dati sufficienti per assegnarne una. Confronta l'andamento in condizioni simili, non un singolo numero.",
        "explanation.restingHR.status": "Segui il tuo andamento personale",
        "explanation.restingHR.detail": "Frequenza cardiaca giornaliera a riposo secondo Garmin. Confronta più giorni con il tuo livello abituale. Forma, sonno, stress e recupero influiscono; più basso non è sempre meglio.",
        "explanation.oxygen.status": "Stima media dell'ossigeno",
        "explanation.oxygen.detail": "Saturazione dell'ossigeno nel sangue stimata dall'orologio. Condizioni di misura e altitudine influiscono sul risultato. Una media giornaliera non valuta la salute né mostra brevi cambiamenti notturni.",
        "explanation.respiration.status": "Media durante il sonno",
        "explanation.respiration.detail": "Respiri medi al minuto durante il sonno. Confronta le tue notti e l'andamento a lungo termine; non è la frequenza respiratoria attuale.",
        "explanation.sleepDuration.status": "Tempo totale di sonno",
        "explanation.sleepDuration.detail": "Tempo classificato da Garmin come sonno nella notte registrata: leggero, profondo e REM. Considera anche il punteggio del sonno e quanto ti senti riposato.",
        "explanation.sleepStage.awake": "Veglia nel periodo di sonno",
        "explanation.sleepStage.status": "Parte della notte registrata",
        "explanation.sleepStage.detail": "Garmin stima le fasi del sonno dai sensori. La durata varia da una notte all'altra; un valore isolato non ha una soglia universale buona o cattiva. Consideralo insieme a sonno totale, punteggio e andamento di più notti.",
        "explanation.steps.status": "Camminata giornaliera",
        "explanation.steps.reached": "Obiettivo giornaliero raggiunto",
        "explanation.steps.progress": "Verso il tuo obiettivo giornaliero",
        "explanation.steps.goalDetail": "Passi confrontati con il tuo obiettivo giornaliero Garmin. L'obiettivo è un traguardo, non una misura universale della forma fisica.",
        "explanation.steps.goal": "Obiettivo: %@",
        "explanation.steps.detail": "Passi registrati per questo giorno. Per valutare i progressi serve un obiettivo personale.",
        "explanation.stepsTarget.status": "Il tuo obiettivo Garmin giornaliero",
        "explanation.stepsTarget.detail": "Obiettivo di passi impostato manualmente o adattato da Garmin. È personale e può cambiare ogni giorno.",
        "explanation.intensity.status": "Minuti di attività ponderati",
        "explanation.intensity.detail": "Garmin conta i minuti moderati e raddoppia quelli intensi. Il totale giornaliero può superare la durata dell'allenamento; non è il totale settimanale.",
        "explanation.calories.status": "Energia a riposo + attività",
        "explanation.calories.detail": "Consumo energetico totale stimato del giorno, inclusi metabolismo a riposo e attività. È consumo, non apporto alimentare né deficit calorico.",
        "explanation.activeCalories.status": "Energia dovuta all'attività",
        "explanation.activeCalories.detail": "Consumo stimato dell'attività oltre al fabbisogno a riposo. È già incluso nelle calorie totali: i due valori non vanno sommati.",
        "explanation.distance.status": "Distanza giornaliera percorsa",
        "explanation.distance.detail": "Distanza dal riepilogo giornaliero Garmin. È il totale dell'attività del giorno, non necessariamente la distanza dell'ultimo allenamento.",
        "explanation.floors.status": "Piani saliti",
        "explanation.floors.detail": "Stima Garmin dei piani saliti durante il giorno. Indica il movimento verso l'alto, non le scale scese.",
        "explanation.weight.status": "Ultima misura registrata",
        "explanation.weight.detail": "Ultima misura del peso disponibile per questo record. Variazioni isolate possono dipendere dai liquidi corporei e dall'ora della misura. Il peso da solo non determina forma o salute.",
        "explanation.hydration.status": "Liquidi registrati",
        "explanation.hydration.detail": "Liquidi annotati in Garmin Connect. Sono le tue registrazioni, non una misura dell'idratazione da sensore né il tuo fabbisogno giornaliero personale.",
        "explanation.training.DETRAINING.title": "Detraining",
        "explanation.training.DETRAINING.detail": "Garmin rileva un calo della forma dopo una prolungata riduzione dell'allenamento.",
        "explanation.training.RECOVERY.title": "Recupero",
        "explanation.training.RECOVERY.detail": "Un allenamento più leggero consente il recupero dagli sforzi intensi.",
        "explanation.training.MAINTAINING.title": "Mantenimento",
        "explanation.training.MAINTAINING.detail": "L'allenamento attuale mantiene la forma senza un miglioramento evidente.",
        "explanation.training.PRODUCTIVE.title": "Produttivo",
        "explanation.training.PRODUCTIVE.detail": "Garmin rileva un miglioramento della forma con l'allenamento attuale.",
        "explanation.training.PEAKING.title": "Picco di forma",
        "explanation.training.PEAKING.detail": "Il carico ridotto ha favorito il recupero e un breve picco di prestazione.",
        "explanation.training.OVERREACHING.title": "Sovraccarico",
        "explanation.training.OVERREACHING.detail": "L'allenamento supera la capacità di recupero e limita i progressi.",
        "explanation.training.UNPRODUCTIVE.title": "Non produttivo",
        "explanation.training.UNPRODUCTIVE.detail": "La forma cala nonostante un carico adeguato; contano anche sonno, alimentazione e stress.",
        "explanation.training.STRAINED.title": "Affaticamento",
        "explanation.training.STRAINED.detail": "Garmin rileva uno squilibrio tra allenamento e recupero.",
        "explanation.training.NO_STATUS.title": "Nessuno stato",
        "explanation.training.NO_STATUS.detail": "Garmin non ha ancora abbastanza dati di allenamento idonei.",
        "explanation.training.PAUSED.title": "In pausa",
        "explanation.training.PAUSED.detail": "La valutazione dello stato di allenamento è sospesa in Garmin.",
        "explanation.help": "Che cosa significa",
        "explanation.source": "Scopri di più su Garmin",
        "explanation.forecast": "Stima lineare dall'ultima tendenza Garmin. %@",
        "explanation.labeledDetail": "%1$@: %2$@",
    ]
}
