// zh-Hans translations shared by the app and WidgetKit.
enum LocalizationZHHans {
    static let strings: [String: String] = [
        "widget.summary.minimum": "请至少保留一个已选指标。",
        "widget.summary.hint": "仅显示已选且有数据的指标。显示数量取决于小组件大小。",
        "widget.summary.primary": "首选主要指标",
        "widget.summary.choose": "选择指标",
        "settings.widgets": "小组件",
        "settings.widgetsSubtitle": "五种可直接使用的桌面小组件。",
        "widget.type": "小组件类型",
        "widget.appearance": "小组件外观",
        "widget.appearance.colorful": "彩色",
        "widget.appearance.light": "浅色",
        "widget.appearance.dark": "深色",
        "widget.appearanceHint": "同一外观适用于全部五种桌面小组件。",
        "widget.automaticHint": "自动选择可用的测量值。",
        "widget.guide.fixedTypes": "选择小组件类型和大小，然后添加到桌面。",
        "widget.slot.day": "一天",
        "widget.slot.day.description": "Body Battery、步数、压力和每日活动。",
        "onboarding.title": "在 Mac 上查看 Garmin 数据",
        "onboarding.privacy": "测量数据保存在这台 Mac 上",
        "onboarding.detail": "连接 Garmin 账户，即可在应用和桌面小组件中查看测量数据。",
        "data.available": "最新测量数据",
        "data.nightEnding": "睡眠结束日期",
        "data.measured": "测量时间",
        "data.received": "接收时间",
        "metric.short.spo2": "SpO₂ · 日均",
        "data.waiting": "正在等待手表数据",
        "data.waitingNew": "正在等待新的测量数据",
        "data.unchanged": "测量数据暂无变化",
        "data.checkFailed": "无法刷新 Garmin 数据",
        "data.unchangedHint": "还没看到最新数据？请在手机上打开 Garmin Connect 并同步手表，我们会自动获取新数据。",
        "data.retainedAllHint": "下方显示的是上次的测量数据及日期。请在手机的 Garmin Connect 中同步手表，以获取新数据。",
        "data.previous": "最近可用数据",
        "data.retainedHint": "部分测量数据尚未收到，已保留上次的数值和日期。请在手机的 Garmin Connect 中同步手表。",
        "data.waitingHint": "请在手机的 Garmin Connect 中同步手表，测量数据将自动显示在这里。",
        "widget.notice.connection": "重新连接 Garmin",
        "widget.notice.unavailable": "无法更新",
        "widget.notice.waiting": "正在等待新数据",
        "widget.waiting": "正在等待数据",
        "widget.waitingHint": "请在手机的 Garmin Connect 中同步手表，测量数据将自动显示在这里。",
        "widget.previous": "最近可用数据",
        "widget.slot.overview.description": "在一个小组件中查看所选指标。",
        "widget.slot.sport.description": "训练准备程度、恢复、负荷和最大摄氧量。",
        "widget.slot.sleep.description": "睡眠时长、睡眠评分和夜间HRV。",
        "widget.slot.training.description": "显示已完成活动和计划锻炼的日历。",
        "widget.preview.easyRun": "轻松跑",
        "widget.preview.intervals": "间歇跑",
        "profile.availableMetrics": "使用可用测量值",
        "profile.availableMetricsHint": "跳过缺少数据的指标，并用相关指标补充小组件。关闭后将严格保留所选项目。",
        "profile.content": "显示内容",
        "content.metrics": "指标",
        "content.training": "训练日历",
        "content.mixed": "两者",
        "profile.previewMetricsOnly": "此预览显示指标部分。训练卡片也会显示在“概览”中。",
        "status.signInRequired": "需要登录",
        "connection.retryAfter": "可重试时间",
        "connection.reconnectDetail": "请打开 Garmin 窗口并完成登录，以恢复更新。",
        "widget.guide.staticProfile": "选择小组件类型和大小，然后添加到桌面。",
        "widget.guide.unavailable": "在应用中查看测量值和小组件预览。",
        "widget.sharingDataUnavailable": "小组件数据暂不可用，你仍可在应用中查看测量数据。",
        "widget.slot.overview": "总览",
        "widget.slot.sport": "运动",
        "widget.slot.sleep": "睡眠",
        "widget.slot.training": "训练日历",
        "widget.slot.firstProfile": "第一个配置",
        "widget.slot.unassigned": "选择配置…",
        "profile.templates": "从模板开始",
        "profile.custom": "自定义配置",
        "profile.template.life": "日常",
        "profile.template.sport": "运动",
        "profile.template.sleep": "睡眠",
        "profile.previewSize": "小组件大小",
        "profile.preview.small": "小",
        "profile.preview.medium": "中",
        "profile.preview.large": "大",
        "profile.previewCount": "显示 %d/%d 项指标。所选指标均可在“概览”中查看。",
        "widget.galleryTitle": "Garmin总览",
        "widget.galleryDescription": "通过五种现成的小组件查看健康、睡眠、活动和训练。",
        "widget.galleryStaticDescription": "选择小组件类型和大小。可用测量值会自动显示。",
        "connection.webTitle": "连接 Garmin",
        "connection.webSubtitle": "连接一次，测量数据即可自动更新。",
        "connection.webIntro": "登录 Garmin Connect",
        "connection.webDetail": "即将打开安全的 Garmin 窗口。请完成登录及 Garmin 要求的验证，应用会将此连接保留在这台 Mac 上。",
        "connection.webSignIn": "通过 Garmin 登录",
        "connection.webPrivacy": "测量数据和 Garmin 网站会话保存在这台 Mac 上。密码直接发送给 Garmin，不经过独立服务器，也不进行使用情况分析。",
        "connection.automaticHint": "数据会在后台更新，包括 Mac 唤醒之后。请保持 Garmin Desk 运行以便自动更新。",
        "connection.reconnect": "重新连接 Garmin",
        "connection.nextSync": "下次可更新时间",
        "error.partial": "部分测量数据无法刷新，已保存的数据仍然可用。",
        "diagnostic.title": "连接详情",
        "diagnostic.stage": "阶段",
        "diagnostic.apiCode": "Garmin 代码",
        "diagnostic.requests": "收到的响应数",
        "menu.edit": "编辑",
        "menu.cut": "剪切",
        "menu.copy": "拷贝",
        "menu.paste": "粘贴",
        "menu.selectAll": "全选",
        "app.subtitle": "一天状态，一目了然",
        "app.device": "Garmin fēnix 8",
        "dashboard.title": "概览",
        "dashboard.profile": "配置",
        "dashboard.moreMetrics": "较大的小组件可以显示更多指标",
        "dashboard.configure": "小组件设置",
        "widget.setup": "设置桌面小组件",
        "widget.customize": "小组件设置",
        "widget.guide.add": "右键点击桌面并选择“编辑小组件”，然后在图库中找到GarminDesk。",
        "widget.guide.profile": "选择小组件类型和大小，然后添加到桌面。",
        "widget.guide.refresh": "Garmin Desk 负责获取测量数据，macOS 决定桌面小组件何时刷新。",
        "widget.sharingUnavailable": "此版本不支持桌面小组件。你仍可在应用中查看测量值。",
        "widget.openApp": "打开 GarminDesk",
        "widget.openAppHint": "请在应用中连接Garmin账户。",
        "widget.profileMissing": "配置已删除",
        "widget.profileMissingHint": "请在此小组件的设置中选择其他配置。",
        "widget.demo": "演示",
        "widget.connect": "在应用中连接 Garmin",
        "dashboard.empty": "请在设置中选择要显示的指标。",
        "dashboard.connect": "连接 Garmin",
        "action.settings": "设置",
        "action.sync": "刷新",
        "action.quit": "退出 Garmin Desk",
        "action.cancel": "取消",
        "action.save": "保存",
        "action.delete": "删除",
        "action.duplicate": "创建副本",
        "action.add": "添加配置",
        "action.up": "上移",
        "action.down": "下移",
        "action.show": "显示",
        "action.hide": "隐藏",
        "action.done": "完成",
        "action.retry": "重试",
        "data.demo": "演示数据",
        "data.updated": "检查时间",
        "data.stale": "数据可能已过时",
        "data.day": "数据日期",
        "data.partial": "部分测量数据不可用",
        "data.emptyDay": "Garmin 暂无此日期的测量数据。请通过 Garmin Connect 同步手表以更新数据。",
        "data.empty": "暂无测量数据",
        "data.demoDetail": "这是示例数值。请连接账户以查看你的测量数据。",
        "data.local": "已保存在这台 Mac 上",
        "data.source": "最近一次 Garmin Connect 同步",
        "data.syncing": "正在检查 Garmin Connect…",
        "status.connected": "已连接 Garmin",
        "status.notConnected": "未连接 Garmin",
        "status.connecting": "正在连接…",
        "settings.title": "设置",
        "settings.profiles": "小组件配置",
        "settings.connection": "Garmin 账户",
        "settings.general": "通用",
        "settings.profilesSubtitle": "为一天中的不同场景创建专属视图。",
        "settings.generalSubtitle": "让 Garmin Desk 更适合你的 Mac。",
        "profile.name": "配置名称",
        "profile.primary": "主要指标",
        "profile.metrics": "指标",
        "profile.metricsHint": "选择要显示的内容，主要指标始终排在首位。",
        "profile.appearance": "外观",
        "profile.style": "样式",
        "profile.density": "信息密度",
        "profile.preview": "预览",
        "profile.added": "新配置",
        "profile.new": "新配置",
        "profile.default": "我的一天",
        "profile.copy": "副本",
        "profile.untitled": "未命名配置",
        "profile.deleteTitle": "删除此配置？",
        "profile.deleteMessage": "此配置将被删除，Garmin 数据仍会保留在这台 Mac 上。",
        "profile.oneRequired": "请至少保留一个配置。",
        "profile.enabled": "已包含",
        "profile.available": "可用指标",
        "profile.count": "项指标",
        "profile.mainBadge": "主要",
        "style.calm": "柔和",
        "style.sport": "运动",
        "style.monochrome": "单色",
        "density.comfortable": "宽松",
        "density.compact": "紧凑",
        "connection.title": "你的 Garmin 账户",
        "connection.subtitle": "这台 Mac 直接连接 Garmin Connect。",
        "connection.localTitle": "数据留在你身边",
        "connection.localDetail": "测量数据缓存在这台 Mac 上，会话凭据保存在 macOS 钥匙串中。应用没有独立服务器。",
        "connection.email": "电子邮件",
        "connection.password": "密码",
        "connection.china": "使用 Garmin 中国服务",
        "connection.signIn": "连接账户",
        "connection.disconnect": "断开连接并清除本地数据",
        "connection.disconnectTitle": "断开 Garmin 连接？",
        "connection.disconnectMessage": "将从这台Mac移除已保存的Garmin会话和缓存测量值。偏好设置会保留。",
        "connection.demo": "使用演示数据体验",
        "connection.demoHint": "演示数值始终带有标记。",
        "connection.syncHint": "通过 Garmin Connect 同步手表，即可在这里查看新的测量数据。",
        "connection.secureHint": "密码仅用于登录，此应用不会保存密码。",
        "connection.mfaTitle": "验证码",
        "connection.mfaHint": "请输入 Garmin 要求的验证码以完成连接。",
        "connection.mfaCode": "验证码",
        "connection.verify": "验证",
        "connection.cancelLogin": "取消登录",
        "general.language": "语言",
        "general.appearance": "外观",
        "general.refresh": "刷新间隔",
        "general.system": "跟随系统",
        "general.light": "浅色",
        "general.dark": "深色",
        "general.minutes5": "每 5 分钟",
        "general.minutes15": "每 15 分钟",
        "general.minutes30": "每 30 分钟",
        "general.minutes60": "每小时",
        "general.refreshHint": "更新时会获取 Garmin Connect 中最新可用的测量数据。",
        "general.localNotice": "偏好设置会自动保存在这台Mac上。",
        "general.launchAtLogin": "登录时打开 Garmin Desk",
        "general.backgroundHint": "关闭窗口后仍会自动更新。若要停止应用，请选择“退出 Garmin Desk”或按 ⌘Q。",
        "menu.about": "关于 Garmin Desk",
        "menu.hideApp": "隐藏 Garmin Desk",
        "menu.hideOthers": "隐藏其他",
        "menu.showAll": "全部显示",
        "menu.file": "文件",
        "menu.closeWindow": "关闭窗口",
        "menu.window": "窗口",
        "menu.mainWindow": "Garmin Desk",
        "menu.minimize": "最小化",
        "menu.zoom": "缩放",
        "category.health": "健康与恢复",
        "category.sleep": "睡眠",
        "category.activity": "日常活动",
        "category.training": "训练",
        "category.body": "身体与补水",
        "metric.steps": "步数",
        "metric.stepGoal": "步数目标",
        "metric.distance": "距离",
        "metric.calories": "总热量",
        "metric.activeCalories": "活动热量",
        "metric.floors": "爬楼层数",
        "metric.intensityMinutes": "中高强度活动分钟数",
        "metric.restingHeartRate": "静息心率",
        "metric.heartRate": "最近心率",
        "metric.stress": "日均压力",
        "metric.bodyBattery": "Body Battery",
        "metric.sleepDuration": "睡眠时长",
        "metric.sleepScore": "睡眠评分",
        "metric.deepSleep": "深度睡眠",
        "metric.remSleep": "快速眼动睡眠",
        "metric.lightSleep": "浅度睡眠",
        "metric.awakeSleep": "清醒时间",
        "metric.hrv": "夜间 HRV",
        "metric.spo2": "日均 SpO₂",
        "metric.respiration": "睡眠平均呼吸频率",
        "metric.trainingReadiness": "训练准备程度",
        "metric.recoveryTime": "恢复时间",
        "metric.vo2Max": "跑步 VO₂ max",
        "metric.trainingLoad": "短期负荷",
        "metric.weight": "体重",
        "metric.hydration": "补水",
        "metric.short.sleepDuration": "睡眠",
        "metric.short.stress": "压力 · 日均",
        "metric.short.restingHeartRate": "静息心率",
        "metric.short.trainingReadiness": "准备程度",
        "metric.short.hrv": "HRV · 夜间",
        "metric.short.respiration": "呼吸 · 睡眠",
        "metric.short.intensityMinutes": "强度分钟数",
        "metric.short.activeCalories": "活动热量",
        "metric.short.recoveryTime": "恢复",
        "metric.short.trainingLoad": "短期负荷",
        "metric.short.vo2Max": "跑步 VO₂ max",
        "metric.short.calories": "总热量",
        "unit.minutes": "分钟",
        "unit.hours": "小时",
        "unit.km": "公里",
        "unit.kg": "公斤",
        "unit.ml": "毫升",
        "unit.bpm": "次/分",
        "unit.kcal": "千卡",
        "unit.ms": "毫秒",
        "unit.breaths": "次/分",
        "unit.vo2": "毫升/公斤/分",
        "error.auth": "无法登录。请检查账户信息后重试。",
        "error.rate_limit": "Garmin 暂时限制了请求，请稍后重试。",
        "error.session_unsupported": "无法恢复已保存的会话，请重新连接 Garmin 账户。",
        "error.access_denied": "Garmin 拒绝访问所请求的数据。",
        "error.security_challenge": "Garmin 安全检查阻止了连接，请稍后重试。",
        "error.network": "无法连接 Garmin，请检查互联网连接。",
        "error.dependency": "Garmin 连接组件不可用，请重新安装最新版 Garmin Desk。",
        "error.unknown": "无法完成请求，请重试。",
        "error.timeout": "Garmin 响应超时，请重试。",
        "error.keychain": "无法访问 macOS 钥匙串，请确认已解锁。",
        "error.protocol": "Garmin 返回了应用无法读取的数据，请稍后重试。",
        "error.storage": "无法在这台 Mac 上保存数据，请检查可用空间和访问权限。",
        "error.login_item": "请在 macOS“系统设置”→“通用”→“登录项”中允许 Garmin Desk 在登录时打开。",
        "training.title": "训练",
        "training.last": "上次完成",
        "training.next": "下次计划",
        "training.completed": "已完成",
        "training.planned": "已安排",
        "training.recent": "最近活动",
        "training.upcoming": "即将进行的训练",
        "training.workout": "训练",
        "training.dateUnknown": "未提供日期",
        "training.timeUnknown": "未提供时间",
        "training.localTime": "记录的当地时间",
        "training.durationUnknown": "未提供时长",
        "training.pastUnavailable": "历史记录暂不可用",
        "training.pastUnavailableHint": "尚未成功从 Garmin 获取此部分。",
        "training.pastEmpty": "最新响应中没有活动",
        "training.pastCoverage": "最近最多 20 次活动 · 非完整历史记录",
        "training.futureUnavailable": "训练日程暂不可用",
        "training.futureUnavailableHint": "日历不可用并不代表没有训练。",
        "training.futureEmpty": "已获取的范围内没有训练",
        "training.calendar": "已发布的 Garmin 日历",
        "training.adaptive": "已验证的自适应日历",
        "training.partial": "部分日历不可用",
        "training.expiredCoverage": "已检查的时段已结束",
        "training.refreshCalendar": "请刷新以检查新的时段。",
        "training.updated": "更新时间",
        "training.updatedUnknown": "更新时间未知",
        "training.cached": "已保存的数据",
        "training.refreshFailed": "无法刷新此部分",
        "training.rateLimit": "Garmin 正在暂时限制请求",
        "training.signIn": "请登录 Garmin Connect 以刷新",
        "training.hour": "小时",
        "training.minute": "分钟",
        "training.second": "秒",
        "training.km": "公里",
        "training.sport.running": "跑步",
        "training.sport.trail_running": "越野跑",
        "training.sport.treadmill_running": "跑步机跑步",
        "training.sport.track_running": "田径场跑步",
        "training.sport.cycling": "骑行",
        "training.sport.mountain_biking": "越野骑行",
        "training.sport.indoor_cycling": "室内骑行",
        "training.sport.swimming": "游泳",
        "training.sport.open_water_swimming": "公开水域游泳",
        "training.sport.walking": "步行",
        "training.sport.hiking": "徒步",
        "training.sport.strength_training": "力量训练",
        "training.sport.cardio_training": "有氧运动",
        "training.sport.elliptical": "椭圆机",
        "training.sport.stair_climbing": "爬楼梯",
        "training.sport.yoga": "瑜伽",
        "training.sport.pilates": "普拉提",
        "training.sport.rowing": "划船",
        "training.sport.tennis": "网球",
        "training.sport.golf": "高尔夫",
        "training.sport.alpine_skiing": "高山滑雪",
        "training.sport.cross_country_skiing": "越野滑雪",
        "training.sport.snowboarding": "单板滑雪",
        "training.sport.triathlon": "多项运动",
        "training.noPublishedThrough": "截至 %@ 没有已发布的训练",
        "training.checkedThrough": "已检查至 %@",
    ]
}
