// Localized interface strings. Keep keys and format placeholders aligned with English.
enum LocalizationNL {
    static let strings: [String: String] = [
        "widget.summary.minimum": "Laat minimaal één meetwaarde geselecteerd.",
        "widget.summary.hint": "Alleen geselecteerde meetwaarden met beschikbare gegevens worden getoond. Hoeveel er passen, hangt af van de widgetgrootte.",
        "widget.summary.primary": "Gewenste hoofdmeetwaarde",
        "widget.summary.choose": "Meetwaarden kiezen",
        "settings.widgets": "Widgets",
        "settings.widgetsSubtitle": "Vijf kant-en-klare widgets voor je bureaublad.",
        "widget.type": "Widgettype",
        "widget.appearance": "Widgetweergave",
        "widget.appearance.colorful": "Kleurrijk",
        "widget.appearance.light": "Licht",
        "widget.appearance.dark": "Donker",
        "widget.appearanceHint": "Eén weergave voor alle vijf bureaubladwidgets.",
        "widget.automaticHint": "Beschikbare metingen worden automatisch geselecteerd.",
        "widget.guide.fixedTypes": "Kies een widgettype en grootte en voeg de widget toe aan je bureaublad.",
        "widget.slot.day": "Dag",
        "widget.slot.day.description": "Body Battery, stappen, stress en dagelijkse activiteit.",
        "onboarding.title": "Je Garmin-gegevens, op je Mac",
        "onboarding.privacy": "Je metingen worden op deze Mac bewaard",
        "onboarding.detail": "Koppel je Garmin-account om je metingen hier en in bureaubladwidgets te bekijken.",
        "data.available": "Laatste metingen",
        "data.nightEnding": "Nacht tot",
        "data.measured": "Gemeten",
        "data.received": "Ontvangen",
        "metric.short.spo2": "SpO₂ · daggem.",
        "data.waiting": "Wachten op gegevens van je horloge",
        "data.waitingNew": "Wachten op nieuwe metingen",
        "data.unchanged": "Geen wijzigingen in je metingen",
        "data.checkFailed": "Garmin-gegevens konden niet worden vernieuwd",
        "data.unchangedHint": "Verwacht je nieuwere metingen? Open Garmin Connect op je telefoon en synchroniseer je horloge. We halen ze automatisch op.",
        "data.retainedAllHint": "Hieronder staan je laatste metingen met hun datums. Open Garmin Connect op je telefoon en synchroniseer je horloge voor nieuwere metingen.",
        "data.previous": "Laatst beschikbaar",
        "data.retainedHint": "Sommige metingen zijn nog niet ontvangen. Je laatste waarden met hun datums zijn bewaard. Synchroniseer je horloge in Garmin Connect op je telefoon.",
        "data.waitingHint": "Open Garmin Connect op je telefoon en synchroniseer je horloge. Je metingen verschijnen hier automatisch.",
        "widget.notice.connection": "Garmin opnieuw koppelen",
        "widget.notice.unavailable": "Bijwerken mislukt",
        "widget.notice.waiting": "Wachten op nieuwe gegevens",
        "widget.waiting": "Wachten op gegevens",
        "widget.waitingHint": "Synchroniseer je horloge in Garmin Connect op je telefoon. Je metingen verschijnen hier automatisch.",
        "widget.previous": "Laatst beschikbaar",
        "widget.slot.overview.description": "Je geselecteerde meetwaarden in één widget.",
        "widget.slot.sport.description": "Trainingsgereedheid, herstel, belasting en VO₂ max.",
        "widget.slot.sleep.description": "Slaapduur, slaapscore en nachtelijke HRV.",
        "widget.slot.training.description": "Een kalender met voltooide activiteiten en geplande trainingen.",
        "widget.preview.easyRun": "Rustige duurloop",
        "widget.preview.intervals": "Hardloopintervallen",
        "profile.availableMetrics": "Beschikbare metingen gebruiken",
        "profile.availableMetricsHint": "Sla ontbrekende metingen over en vul de widget aan met verwante waarden. Schakel dit uit om je exacte selectie te behouden.",
        "profile.content": "Inhoud",
        "content.metrics": "Meetgegevens",
        "content.training": "Trainingskalender",
        "content.mixed": "Beide",
        "profile.previewMetricsOnly": "Dit voorbeeld toont de meetgegevens. Je trainingskaarten verschijnen ook in het Overzicht.",
        "status.signInRequired": "Inloggen vereist",
        "connection.retryAfter": "Opnieuw proberen na",
        "connection.reconnectDetail": "Open het Garmin-venster en rond het inloggen af om updates te hervatten.",
        "widget.guide.staticProfile": "Kies een widgettype en grootte en voeg de widget toe aan je bureaublad.",
        "widget.guide.unavailable": "Bekijk je metingen en widgetvoorbeelden in de app.",
        "widget.sharingDataUnavailable": "Widgetgegevens zijn nog niet beschikbaar. Je metingen kun je wel in de app bekijken.",
        "widget.slot.overview": "Samenvatting",
        "widget.slot.sport": "Sport",
        "widget.slot.sleep": "Slaap",
        "widget.slot.training": "Trainingskalender",
        "widget.slot.firstProfile": "Eerste profiel",
        "widget.slot.unassigned": "Kies een profiel…",
        "profile.templates": "Begin met een sjabloon",
        "profile.custom": "Eigen profiel",
        "profile.template.life": "Dagelijks",
        "profile.template.sport": "Sport",
        "profile.template.sleep": "Slaap",
        "profile.previewSize": "Widgetgrootte",
        "profile.preview.small": "Klein",
        "profile.preview.medium": "Normaal",
        "profile.preview.large": "Groot",
        "profile.previewCount": "Toont %d van %d meetgegevens. Alle geselecteerde meetgegevens zijn beschikbaar in het Overzicht.",
        "widget.galleryTitle": "Garmin-samenvatting",
        "widget.galleryDescription": "Gezondheid, slaap, activiteit en training in vijf kant-en-klare widgets.",
        "widget.galleryStaticDescription": "Kies een widgettype en grootte. Beschikbare metingen verschijnen automatisch.",
        "connection.webTitle": "Garmin koppelen",
        "connection.webSubtitle": "Eenmalig koppelen. Je metingen worden automatisch vernieuwd.",
        "connection.webIntro": "Inloggen bij Garmin Connect",
        "connection.webDetail": "Er wordt een beveiligd Garmin-venster geopend. Log in en voltooi eventuele verificatie van Garmin. De app bewaart deze verbinding vervolgens op je Mac.",
        "connection.webSignIn": "Inloggen met Garmin",
        "connection.webPrivacy": "Metingen en de Garmin-websitesessie blijven op deze Mac. Je wachtwoord gaat rechtstreeks naar Garmin. Er is geen aparte server of analyse van gebruiksgegevens.",
        "connection.automaticHint": "Je gegevens worden op de achtergrond bijgewerkt, ook nadat je Mac uit de sluimerstand komt. Laat Garmin Desk draaien voor automatische updates.",
        "connection.reconnect": "Garmin opnieuw koppelen",
        "connection.nextSync": "Volgende update na",
        "error.partial": "Sommige metingen konden niet worden vernieuwd. Opgeslagen gegevens blijven beschikbaar.",
        "diagnostic.title": "Verbindingsdetails",
        "diagnostic.stage": "Fase",
        "diagnostic.apiCode": "Garmin-code",
        "diagnostic.requests": "Ontvangen antwoorden",
        "menu.edit": "Wijzig",
        "menu.cut": "Knip",
        "menu.copy": "Kopieer",
        "menu.paste": "Plak",
        "menu.selectAll": "Selecteer alles",
        "app.subtitle": "Je dag in één oogopslag",
        "app.device": "Garmin fēnix 8",
        "dashboard.title": "Overzicht",
        "dashboard.profile": "Profiel",
        "dashboard.moreMetrics": "Grotere widgets kunnen meer meetgegevens tonen",
        "dashboard.configure": "Widgetinstellingen",
        "widget.setup": "Bureaubladwidgets instellen",
        "widget.customize": "Widgetinstellingen",
        "widget.guide.add": "Klik met de rechtermuisknop op het bureaublad en kies 'Wijzig widgets'. Zoek GarminDesk in de galerij.",
        "widget.guide.profile": "Kies een widgettype en grootte en voeg de widget toe aan je bureaublad.",
        "widget.guide.refresh": "Garmin Desk haalt je metingen op. macOS bepaalt wanneer de bureaubladwidget wordt vernieuwd.",
        "widget.sharingUnavailable": "Bureaubladwidgets zijn niet beschikbaar in deze versie. Je kunt je metingen wel in de app bekijken.",
        "widget.openApp": "Open GarminDesk",
        "widget.openAppHint": "Koppel je Garmin-account in de app.",
        "widget.profileMissing": "Profiel verwijderd",
        "widget.profileMissingHint": "Kies een ander profiel in de instellingen van deze widget.",
        "widget.demo": "DEMO",
        "widget.connect": "Koppel Garmin in de app",
        "dashboard.empty": "Kies in de instellingen welke meetgegevens je wilt zien.",
        "dashboard.connect": "Garmin koppelen",
        "action.settings": "Instellingen",
        "action.sync": "Vernieuw",
        "action.quit": "Stop Garmin Desk",
        "action.cancel": "Annuleer",
        "action.save": "Bewaar",
        "action.delete": "Verwijder",
        "action.duplicate": "Dupliceer",
        "action.add": "Voeg profiel toe",
        "action.up": "Omhoog",
        "action.down": "Omlaag",
        "action.show": "Toon",
        "action.hide": "Verberg",
        "action.done": "Gereed",
        "action.retry": "Probeer opnieuw",
        "data.demo": "Demogegevens",
        "data.updated": "Gecontroleerd",
        "data.stale": "Gegevens zijn mogelijk verouderd",
        "data.day": "Gegevens voor",
        "data.partial": "Sommige metingen zijn niet beschikbaar",
        "data.emptyDay": "Garmin heeft nog geen metingen voor deze datum. Synchroniseer je horloge met Garmin Connect om ze bij te werken.",
        "data.empty": "Nog geen meting",
        "data.demoDetail": "Voorbeeldwaarden. Koppel je account om je eigen metingen te zien.",
        "data.local": "Bewaard op deze Mac",
        "data.source": "Laatste Garmin Connect-synchronisatie",
        "data.syncing": "Garmin Connect controleren…",
        "status.connected": "Garmin gekoppeld",
        "status.notConnected": "Garmin niet gekoppeld",
        "status.connecting": "Verbinden…",
        "settings.title": "Instellingen",
        "settings.profiles": "Widgetprofielen",
        "settings.connection": "Garmin-account",
        "settings.general": "Algemeen",
        "settings.profilesSubtitle": "Maak een weergave voor elk deel van je dag.",
        "settings.generalSubtitle": "Laat Garmin Desk bij jouw Mac passen.",
        "profile.name": "Profielnaam",
        "profile.primary": "Belangrijkste meetgegeven",
        "profile.metrics": "Meetgegevens",
        "profile.metricsHint": "Kies wat je wilt weergeven. Het belangrijkste meetgegeven staat altijd vooraan.",
        "profile.appearance": "Weergave",
        "profile.style": "Stijl",
        "profile.density": "Dichtheid",
        "profile.preview": "Voorbeeld",
        "profile.added": "Nieuw profiel",
        "profile.new": "Nieuw profiel",
        "profile.default": "Mijn dag",
        "profile.copy": "Kopie",
        "profile.untitled": "Naamloos profiel",
        "profile.deleteTitle": "Dit profiel verwijderen?",
        "profile.deleteMessage": "Het profiel wordt verwijderd. Je Garmin-gegevens blijven op deze Mac.",
        "profile.oneRequired": "Bewaar ten minste één profiel.",
        "profile.enabled": "Inbegrepen",
        "profile.available": "Beschikbare meetgegevens",
        "profile.count": "meetgegevens",
        "profile.mainBadge": "Hoofd",
        "style.calm": "Rustig",
        "style.sport": "Sport",
        "style.monochrome": "Monochroom",
        "density.comfortable": "Ruim",
        "density.compact": "Compact",
        "connection.title": "Je Garmin-account",
        "connection.subtitle": "Je Mac maakt rechtstreeks verbinding met Garmin Connect.",
        "connection.localTitle": "Je gegevens blijven bij jou",
        "connection.localDetail": "Metingen worden op deze Mac opgeslagen. Sessiegegevens worden bewaard in de macOS-sleutelhanger. De app heeft geen aparte server.",
        "connection.email": "E-mail",
        "connection.password": "Wachtwoord",
        "connection.china": "Gebruik Garmin China",
        "connection.signIn": "Koppel account",
        "connection.disconnect": "Ontkoppel en wis lokale gegevens",
        "connection.disconnectTitle": "Garmin ontkoppelen?",
        "connection.disconnectMessage": "De opgeslagen Garmin-sessie en metingen worden van deze Mac verwijderd. Je voorkeuren blijven bewaard.",
        "connection.demo": "Verken met demogegevens",
        "connection.demoHint": "Demowaarden zijn altijd gemarkeerd.",
        "connection.syncHint": "Synchroniseer je horloge met Garmin Connect om hier nieuwe metingen te zien.",
        "connection.secureHint": "Je wachtwoord wordt alleen gebruikt om in te loggen en wordt niet door deze app opgeslagen.",
        "connection.mfaTitle": "Verificatiecode",
        "connection.mfaHint": "Voer de door Garmin gevraagde code in om het koppelen af te ronden.",
        "connection.mfaCode": "Code",
        "connection.verify": "Verifieer",
        "connection.cancelLogin": "Annuleer inloggen",
        "general.language": "Taal",
        "general.appearance": "Weergave",
        "general.refresh": "Verversingsinterval",
        "general.system": "Volg systeem",
        "general.light": "Licht",
        "general.dark": "Donker",
        "general.minutes5": "Elke 5 minuten",
        "general.minutes15": "Elke 15 minuten",
        "general.minutes30": "Elke 30 minuten",
        "general.minutes60": "Elk uur",
        "general.refreshHint": "Updates gebruiken de nieuwste metingen die in Garmin Connect beschikbaar zijn.",
        "general.localNotice": "Je voorkeuren worden automatisch op deze Mac bewaard.",
        "general.launchAtLogin": "Open Garmin Desk bij inloggen",
        "general.backgroundHint": "Als je het venster sluit, blijven automatische updates actief. Kies 'Stop Garmin Desk' of druk op ⌘Q om de app te stoppen.",
        "menu.about": "Over Garmin Desk",
        "menu.hideApp": "Verberg Garmin Desk",
        "menu.hideOthers": "Verberg andere",
        "menu.showAll": "Toon alles",
        "menu.file": "Archief",
        "menu.closeWindow": "Sluit venster",
        "menu.window": "Venster",
        "menu.mainWindow": "Garmin Desk",
        "menu.minimize": "Minimaliseer",
        "menu.zoom": "Zoom",
        "category.health": "Gezondheid en herstel",
        "category.sleep": "Slaap",
        "category.activity": "Dagelijkse activiteit",
        "category.training": "Training",
        "category.body": "Lichaam en hydratatie",
        "metric.steps": "Stappen",
        "metric.stepGoal": "Stappendoel",
        "metric.distance": "Afstand",
        "metric.calories": "Totale calorieën",
        "metric.activeCalories": "Actieve calorieën",
        "metric.floors": "Verdiepingen omhoog",
        "metric.intensityMinutes": "Intensieve minuten",
        "metric.restingHeartRate": "Rusthartslag",
        "metric.heartRate": "Laatste hartslag",
        "metric.stress": "Gemiddelde dagelijkse stress",
        "metric.bodyBattery": "Body Battery",
        "metric.sleepDuration": "Slaapduur",
        "metric.sleepScore": "Slaapscore",
        "metric.deepSleep": "Diepe slaap",
        "metric.remSleep": "Remslaap",
        "metric.lightSleep": "Lichte slaap",
        "metric.awakeSleep": "Wakkere tijd",
        "metric.hrv": "Nachtelijke HRV",
        "metric.spo2": "Gemiddelde dagelijkse SpO₂",
        "metric.respiration": "Gemiddelde ademfrequentie tijdens slaap",
        "metric.trainingReadiness": "Trainingsgereedheid",
        "metric.recoveryTime": "Hersteltijd",
        "metric.vo2Max": "VO₂ max hardlopen",
        "metric.trainingLoad": "Acute trainingsbelasting",
        "metric.weight": "Gewicht",
        "metric.hydration": "Hydratatie",
        "metric.short.sleepDuration": "Slaap",
        "metric.short.stress": "Stress · dag",
        "metric.short.restingHeartRate": "Rusthartslag",
        "metric.short.trainingReadiness": "Gereedheid",
        "metric.short.hrv": "HRV · nacht",
        "metric.short.respiration": "Ademhaling · slaap",
        "metric.short.intensityMinutes": "Intensieve min.",
        "metric.short.activeCalories": "Actieve calorieën",
        "metric.short.recoveryTime": "Herstel",
        "metric.short.trainingLoad": "Acute belasting",
        "metric.short.vo2Max": "VO₂ max lopen",
        "metric.short.calories": "Totale calorieën",
        "unit.minutes": "min",
        "unit.hours": "u",
        "unit.km": "km",
        "unit.kg": "kg",
        "unit.ml": "ml",
        "unit.bpm": "sl/min",
        "unit.kcal": "kcal",
        "unit.ms": "ms",
        "unit.breaths": "ad/min",
        "unit.vo2": "ml/kg/min",
        "error.auth": "Inloggen mislukt. Controleer je gegevens en probeer het opnieuw.",
        "error.rate_limit": "Garmin heeft verzoeken tijdelijk beperkt. Probeer het later opnieuw.",
        "error.session_unsupported": "Deze app kan de opgeslagen sessie niet herstellen. Koppel je Garmin-account opnieuw.",
        "error.access_denied": "Garmin heeft toegang tot de gevraagde gegevens geweigerd.",
        "error.security_challenge": "Een beveiligingscontrole van Garmin heeft de verbinding geblokkeerd. Probeer het later opnieuw.",
        "error.network": "Garmin is niet bereikbaar. Controleer je internetverbinding.",
        "error.dependency": "Het Garmin-verbindingsonderdeel is niet beschikbaar. Installeer de nieuwste versie van Garmin Desk opnieuw.",
        "error.unknown": "Het verzoek kon niet worden voltooid. Probeer het opnieuw.",
        "error.timeout": "Garmin reageerde niet op tijd. Probeer het opnieuw.",
        "error.keychain": "Geen toegang tot de macOS-sleutelhanger. Controleer of deze ontgrendeld is.",
        "error.protocol": "Garmin stuurde gegevens die de app niet kon lezen. Probeer het later opnieuw.",
        "error.storage": "Gegevens konden niet op deze Mac worden bewaard. Controleer de vrije schijfruimte en toegangsrechten.",
        "error.login_item": "Sta toe dat Garmin Desk bij inloggen wordt geopend via Systeeminstellingen → Algemeen → Inloggen.",
        "training.title": "Training",
        "training.last": "Laatst voltooid",
        "training.next": "Volgende gepland",
        "training.completed": "Voltooid",
        "training.planned": "Gepland",
        "training.recent": "Recente activiteiten",
        "training.upcoming": "Komende trainingen",
        "training.workout": "Training",
        "training.dateUnknown": "Datum niet opgegeven",
        "training.timeUnknown": "Tijd niet opgegeven",
        "training.localTime": "vastgelegde lokale tijd",
        "training.durationUnknown": "Duur niet opgegeven",
        "training.pastUnavailable": "Geschiedenis is nog niet beschikbaar",
        "training.pastUnavailableHint": "Deze gegevens zijn nog niet succesvol opgehaald bij Garmin.",
        "training.pastEmpty": "Geen activiteiten in het laatste antwoord",
        "training.pastCoverage": "Maximaal 20 recente activiteiten · niet de volledige geschiedenis",
        "training.futureUnavailable": "Schema is nog niet beschikbaar",
        "training.futureUnavailableHint": "Een niet-beschikbare agenda betekent niet dat er geen trainingen zijn.",
        "training.futureEmpty": "Geen trainingen in het opgehaalde deel",
        "training.calendar": "Gepubliceerde Garmin-agenda",
        "training.adaptive": "Geverifieerde adaptieve agenda",
        "training.partial": "Een deel van de agenda is niet beschikbaar",
        "training.expiredCoverage": "De gecontroleerde periode is voorbij",
        "training.refreshCalendar": "Vernieuw om een nieuwe periode te controleren.",
        "training.updated": "Bijgewerkt",
        "training.updatedUnknown": "Tijd van update onbekend",
        "training.cached": "Opgeslagen gegevens",
        "training.refreshFailed": "Deze gegevens konden niet worden vernieuwd",
        "training.rateLimit": "Garmin beperkt verzoeken tijdelijk",
        "training.signIn": "Log in bij Garmin Connect om te vernieuwen",
        "training.hour": "u",
        "training.minute": "min",
        "training.second": "s",
        "training.km": "km",
        "training.sport.running": "Hardlopen",
        "training.sport.trail_running": "Trailrunning",
        "training.sport.treadmill_running": "Hardlopen op loopband",
        "training.sport.track_running": "Baanlopen",
        "training.sport.cycling": "Fietsen",
        "training.sport.mountain_biking": "Mountainbiken",
        "training.sport.indoor_cycling": "Binnen fietsen",
        "training.sport.swimming": "Zwemmen",
        "training.sport.open_water_swimming": "Openwaterzwemmen",
        "training.sport.walking": "Wandelen",
        "training.sport.hiking": "Hiken",
        "training.sport.strength_training": "Krachttraining",
        "training.sport.cardio_training": "Cardio",
        "training.sport.elliptical": "Crosstrainer",
        "training.sport.stair_climbing": "Traplopen",
        "training.sport.yoga": "Yoga",
        "training.sport.pilates": "Pilates",
        "training.sport.rowing": "Roeien",
        "training.sport.tennis": "Tennis",
        "training.sport.golf": "Golf",
        "training.sport.alpine_skiing": "Alpineskiën",
        "training.sport.cross_country_skiing": "Langlaufen",
        "training.sport.snowboarding": "Snowboarden",
        "training.sport.triathlon": "Multisport",
        "training.noPublishedThrough": "Geen gepubliceerde trainingen tot en met %@",
        "training.checkedThrough": "gecontroleerd tot en met %@",
    ]
}
