import Foundation

/// Metric explanations in ru. Garmin payload codes are never translated here.
enum LocalizationExplanationRU {
    static let strings: [String: String] = [
        "explanation.load.rangeUnavailable": "Нет личного диапазона",
        "explanation.load.ratio.low": "Низкое соотношение нагрузок",
        "explanation.load.ratio.optimal": "Оптимальное соотношение нагрузок",
        "explanation.load.ratio.high": "Высокое соотношение нагрузок",
        "explanation.load.ratio.veryHigh": "Очень высокое соотношение нагрузок",
        "explanation.load.ratio.value": "Острая / хроническая: %@",
        "explanation.load.below": "Ниже оптимального диапазона",
        "explanation.load.above": "Выше оптимального диапазона",
        "explanation.load.optimal": "В оптимальном диапазоне",
        "explanation.load.range": "Ваш диапазон: %1$@–%2$@",
        "explanation.load.detail": "Острая нагрузка оценивает воздействие недавних тренировок на организм. Garmin придаёт больший вес свежим занятиям и сравнивает результат с диапазоном, рассчитанным по вашей форме и истории тренировок. Само число не показывает, насколько продуктивны тренировки.",
        "explanation.load.ratio.detail": "Соотношение сравнивает недавнюю острую нагрузку с долгосрочной хронической. Garmin передаёт его категорию отдельно от тренировочного статуса.",
        "explanation.load.garminStatus": "Статус Garmin: %@",
        "explanation.load.noStatusDetail": "Тренировочный статус учитывает также динамику формы и восстановление. Низкая нагрузка сама по себе не означает детренированность. Для этого значения Garmin не передал распознанный тренировочный статус.",
        "explanation.hrv.compare": "Сравнивайте со своей нормой",
        "explanation.hrv.balanced": "HRV за неделю в балансе",
        "explanation.hrv.unbalanced": "HRV за неделю вне баланса",
        "explanation.hrv.low": "Низкая HRV за неделю",
        "explanation.hrv.poor": "Низкий статус HRV",
        "explanation.hrv.insufficient": "Недостаточно свежих данных HRV",
        "explanation.hrv.weekly": "Среднее за 7 дней: %1$@ %2$@",
        "explanation.hrv.baseline": "Ваша норма: %1$@–%2$@ %3$@",
        "explanation.hrv.detail": "Число на карточке — средняя вариабельность интервалов между ударами сердца за последнюю ночь. Статус HRV Garmin сравнивает среднее за 7 дней с вашей личной нормой, для которой нужно около трёх недель данных сна. Значение за ночь и недельный статус — разные показатели; больше не всегда лучше.",
        "explanation.readiness.prime": "Отличная готовность",
        "explanation.readiness.high": "Высокая готовность",
        "explanation.readiness.moderate": "Умеренная готовность",
        "explanation.readiness.low": "Низкая готовность",
        "explanation.readiness.poor": "Очень низкая готовность",
        "explanation.readiness.detail": "Garmin объединяет данные сна, времени восстановления, HRV, острой нагрузки и недавнего стресса. Шкала: 1–24 — очень низкая, 25–49 — низкая, 50–74 — умеренная, 75–94 — высокая, 95–100 — отличная готовность. При низком балле стоит уделить внимание восстановлению; высокий указывает на больший ресурс для сложной тренировки.",
        "explanation.sleep.excellent": "Отличный сон",
        "explanation.sleep.good": "Хороший сон",
        "explanation.sleep.fair": "Удовлетворительный сон",
        "explanation.sleep.poor": "Низкое качество сна",
        "explanation.sleep.detail": "Сводная оценка качества сна и восстановления с учётом длительности, стадий и беспокойства во сне. Шкала Garmin: ниже 60 — низкое качество, 60–79 — удовлетворительно, 80–89 — хорошо, 90–100 — отлично. Одной длительности сна для оценки недостаточно.",
        "explanation.stress.resting": "Диапазон покоя",
        "explanation.stress.low": "Низкий стресс",
        "explanation.stress.medium": "Средний стресс",
        "explanation.stress.high": "Высокий стресс",
        "explanation.stress.detail": "Это средний физиологический стресс за день по данным Garmin, а не текущая оценка эмоций. Шкала 0–100 основана на вариабельности пульса: 0–25 — покой, 26–50 — низкий, 51–75 — средний, 76–100 — высокий стресс. Среднее за день может скрывать короткие пики и периоды отдыха.",
        "explanation.battery.veryLow": "Очень малый запас энергии",
        "explanation.battery.low": "Малый запас энергии",
        "explanation.battery.moderate": "Средний запас энергии",
        "explanation.battery.high": "Большой запас энергии",
        "explanation.battery.detail": "Garmin оценивает запас энергии по стрессу, вариабельности пульса, сну и активности. Отдых может восполнять запас, стресс и активность — расходовать. Это оценка энергии, а не процент физической формы.",
        "explanation.recovery.complete": "Отсчёт восстановления завершён",
        "explanation.recovery.remaining": "До следующей тяжёлой тренировки",
        "explanation.recovery.detail": "Garmin оценивает время до готовности к следующей тяжёлой тренировке. Это не требование полного покоя. Сон, стресс и последующая активность могут изменить оценку. Здесь показано последнее полученное значение Garmin.",
        "explanation.vo2.status": "Оценка аэробной формы",
        "explanation.vo2.detail": "Оценка максимального потребления кислорода на килограмм массы в минуту. Категории Garmin зависят от возраста и пола; приложение не получает достаточно данных профиля, чтобы выбрать категорию. Полезнее сравнивать свою динамику в похожих условиях, чем оценивать одно число.",
        "explanation.restingHR.status": "Ориентир — ваша динамика",
        "explanation.restingHR.detail": "Пульс в покое за день по данным Garmin. Сравнивайте несколько дней со своим привычным уровнем. Форма, сон, стресс и восстановление влияют на пульс; меньше не всегда лучше.",
        "explanation.oxygen.status": "Средняя оценка насыщения O₂",
        "explanation.oxygen.detail": "Оценка насыщения крови кислородом по датчику часов. На результат влияют условия измерения и высота. Одно среднее за день не позволяет оценить здоровье или увидеть короткие изменения за ночь.",
        "explanation.respiration.status": "Среднее во сне",
        "explanation.respiration.detail": "Средняя частота дыхания за время сна. Сравнивайте свои ночи и длительную динамику; это не текущая частота дыхания.",
        "explanation.sleepDuration.status": "Общее время сна",
        "explanation.sleepDuration.detail": "Время, которое Garmin определил как сон за эту ночь: лёгкий, глубокий и REM-сон. Вместе с длительностью учитывайте балл сна и ощущение отдыха.",
        "explanation.sleepStage.awake": "Бодрствование в период сна",
        "explanation.sleepStage.status": "Часть записанной ночи",
        "explanation.sleepStage.detail": "Garmin оценивает стадии сна по данным датчиков. Их длительность меняется от ночи к ночи: у отдельного значения нет универсального порога «хорошо/плохо». Смотрите также на общую длительность, балл сна и динамику за несколько ночей.",
        "explanation.steps.status": "Шаги за день",
        "explanation.steps.reached": "Цель на день достигнута",
        "explanation.steps.progress": "Прогресс к дневной цели",
        "explanation.steps.goalDetail": "Число шагов относительно вашей дневной цели Garmin. Цель — ориентир активности, а не универсальная оценка формы.",
        "explanation.steps.goal": "Цель: %@",
        "explanation.steps.detail": "Шаги, записанные за этот день. Для оценки прогресса нужна личная цель по шагам.",
        "explanation.stepsTarget.status": "Ваша дневная цель Garmin",
        "explanation.stepsTarget.detail": "Цель по шагам, заданная вручную или автоматически Garmin. Она индивидуальна и может меняться день ото дня.",
        "explanation.intensity.status": "Минуты с учётом интенсивности",
        "explanation.intensity.detail": "Garmin учитывает минуты умеренной активности, а минуты высокой интенсивности засчитывает вдвойне. Число за день может превышать длительность тренировки; это не недельный итог.",
        "explanation.calories.status": "Покой + активность",
        "explanation.calories.detail": "Оценка общего расхода энергии за день, включая обмен в покое и активность. Это расход, а не калории из еды или дефицит калорий.",
        "explanation.activeCalories.status": "Расход от активности",
        "explanation.activeCalories.detail": "Оценка расхода энергии из-за активности сверх потребностей в покое. Уже входит в общие калории: складывать два показателя не нужно.",
        "explanation.distance.status": "Дистанция за день",
        "explanation.distance.detail": "Дистанция из дневной сводки Garmin. Это итог активности за день, который не обязательно совпадает с дистанцией последней тренировки.",
        "explanation.floors.status": "Поднятые этажи",
        "explanation.floors.detail": "Оценка Garmin числа этажей, на которые вы поднялись за день. Показатель отражает подъём, а не спуск.",
        "explanation.weight.status": "Последнее записанное измерение",
        "explanation.weight.detail": "Последнее доступное измерение массы тела для этой записи. Отдельные изменения могут зависеть от воды и времени измерения. Сам вес не определяет форму или здоровье.",
        "explanation.hydration.status": "Записанная выпитая жидкость",
        "explanation.hydration.detail": "Объём жидкости, записанный в Garmin Connect. Это ваши записи, а не измерение гидратации датчиком или индивидуальная суточная потребность.",
        "explanation.training.DETRAINING.title": "Детренированность",
        "explanation.training.DETRAINING.detail": "Garmin видит снижение формы после длительного уменьшения тренировок.",
        "explanation.training.RECOVERY.title": "Восстановление",
        "explanation.training.RECOVERY.detail": "Сниженная нагрузка даёт организму восстановиться после тяжёлой работы.",
        "explanation.training.MAINTAINING.title": "Поддержание",
        "explanation.training.MAINTAINING.detail": "Текущие тренировки сохраняют форму без заметного роста.",
        "explanation.training.PRODUCTIVE.title": "Продуктивность",
        "explanation.training.PRODUCTIVE.detail": "Garmin видит улучшение формы при текущих тренировках.",
        "explanation.training.PEAKING.title": "Пик формы",
        "explanation.training.PEAKING.detail": "Снижение нагрузки помогло восстановиться и выйти на кратковременный пик формы.",
        "explanation.training.OVERREACHING.title": "Чрезмерная нагрузка",
        "explanation.training.OVERREACHING.detail": "Нагрузка превышает возможности восстановления и мешает прогрессу.",
        "explanation.training.UNPRODUCTIVE.title": "Непродуктивность",
        "explanation.training.UNPRODUCTIVE.detail": "Несмотря на достаточную нагрузку, Garmin видит снижение формы; важны сон, питание и стресс.",
        "explanation.training.STRAINED.title": "Напряжение",
        "explanation.training.STRAINED.detail": "Garmin видит дисбаланс нагрузки и восстановления.",
        "explanation.training.NO_STATUS.title": "Недостаточно данных",
        "explanation.training.NO_STATUS.detail": "Garmin пока не накопил достаточно подходящих тренировок для статуса.",
        "explanation.training.PAUSED.title": "Статус приостановлен",
        "explanation.training.PAUSED.detail": "Расчёт тренировочного статуса приостановлен в Garmin.",
        "explanation.help": "Что означает показатель",
        "explanation.source": "Подробнее у Garmin",
        "explanation.forecast": "Линейная оценка по последнему тренду Garmin. %@",
        "explanation.labeledDetail": "%1$@: %2$@",
    ]
}
