// Full application and widget catalog. Keep keys aligned with the English catalog.
enum LocalizationFR {
    static let strings: [String: String] = [
        "widget.summary.minimum": "Gardez au moins une mesure sélectionnée.",
        "widget.summary.hint": "Seules les mesures sélectionnées avec des données disponibles sont affichées. Leur nombre dépend de la taille du widget.",
        "widget.summary.primary": "Mesure principale préférée",
        "widget.summary.choose": "Choisir les mesures",
        "settings.widgets": "Widgets",
        "settings.widgetsSubtitle": "Cinq widgets prêts à l’emploi pour votre bureau.",
        "widget.type": "Type de widget",
        "widget.appearance": "Apparence des widgets",
        "widget.appearance.colorful": "Colorée",
        "widget.appearance.light": "Claire",
        "widget.appearance.dark": "Sombre",
        "widget.appearanceHint": "Une apparence commune aux cinq widgets du bureau.",
        "widget.automaticHint": "Les mesures disponibles sont sélectionnées automatiquement.",
        "widget.guide.fixedTypes": "Choisissez un type et une taille de widget, puis ajoutez-le au bureau.",
        "widget.slot.day": "Journée",
        "widget.slot.day.description": "Body Battery, pas, stress et activité quotidienne.",
        "onboarding.title": "Vos données Garmin sur votre Mac",
        "onboarding.privacy": "Vos mesures sont stockées sur ce Mac",
        "onboarding.detail": "Connectez votre compte Garmin pour voir vos mesures ici et dans les widgets du bureau.",
        "data.available": "Dernières mesures",
        "data.nightEnding": "Nuit se terminant le",
        "data.measured": "Mesuré",
        "data.received": "Reçu",
        "metric.short.spo2": "SpO₂ · moy. du jour",
        "data.waiting": "En attente des données de votre montre",
        "data.waitingNew": "En attente de nouvelles mesures",
        "data.unchanged": "Vos mesures n’ont pas changé",
        "data.checkFailed": "Impossible d’actualiser les données Garmin",
        "data.unchangedHint": "Vous attendez des mesures plus récentes ? Ouvrez Garmin Connect sur votre téléphone et synchronisez votre montre. Elles seront récupérées automatiquement.",
        "data.retainedAllHint": "Vos dernières mesures et leurs dates figurent ci-dessous. Ouvrez Garmin Connect sur votre téléphone et synchronisez votre montre pour obtenir des mesures plus récentes.",
        "data.previous": "Dernières disponibles",
        "data.retainedHint": "Certaines mesures ne sont pas encore arrivées. Vos dernières valeurs et leurs dates ont été conservées. Synchronisez votre montre dans Garmin Connect sur votre téléphone.",
        "data.waitingHint": "Ouvrez Garmin Connect sur votre téléphone et synchronisez votre montre. Vos mesures apparaîtront ici automatiquement.",
        "widget.notice.connection": "Reconnecter Garmin",
        "widget.notice.unavailable": "Actualisation impossible",
        "widget.notice.waiting": "En attente de nouvelles données",
        "widget.waiting": "En attente de données",
        "widget.waitingHint": "Synchronisez votre montre dans Garmin Connect sur votre téléphone. Vos mesures apparaîtront ici automatiquement.",
        "widget.previous": "Dernières disponibles",
        "widget.slot.overview.description": "Vos mesures sélectionnées dans un seul widget.",
        "widget.slot.sport.description": "Préparation à l’entraînement, récupération, charge et VO₂ max.",
        "widget.slot.sleep.description": "Durée du sommeil, score de sommeil et VFC nocturne.",
        "widget.slot.training.description": "Un calendrier des activités terminées et des séances programmées.",
        "widget.preview.easyRun": "Course facile",
        "widget.preview.intervals": "Course fractionnée",
        "profile.availableMetrics": "Utiliser les mesures disponibles",
        "profile.availableMetricsHint": "Ignorer les mesures manquantes et compléter le widget avec des mesures associées. Désactivez pour conserver exactement votre sélection.",
        "profile.content": "Contenu",
        "content.metrics": "Mesures",
        "content.training": "Calendrier d’entraînement",
        "content.mixed": "Les deux",
        "profile.previewMetricsOnly": "Cet aperçu affiche les mesures. Vos cartes d’entraînement apparaissent aussi dans la vue d’ensemble.",
        "status.signInRequired": "Connexion requise",
        "connection.retryAfter": "Réessayer après",
        "connection.reconnectDetail": "Ouvrez la fenêtre Garmin et terminez la connexion pour reprendre les actualisations.",
        "widget.guide.staticProfile": "Choisissez un type et une taille de widget, puis ajoutez-le au bureau.",
        "widget.guide.unavailable": "Consultez vos mesures et les aperçus des widgets dans l’app.",
        "widget.sharingDataUnavailable": "Les données des widgets ne sont pas encore disponibles. Vous pouvez consulter vos mesures dans l’app.",
        "widget.slot.overview": "Résumé",
        "widget.slot.sport": "Sport",
        "widget.slot.sleep": "Sommeil",
        "widget.slot.training": "Calendrier d’entraînement",
        "widget.slot.firstProfile": "Premier profil",
        "widget.slot.unassigned": "Choisir un profil…",
        "profile.templates": "Commencer avec un modèle",
        "profile.custom": "Profil personnalisé",
        "profile.template.life": "Vie quotidienne",
        "profile.template.sport": "Sport",
        "profile.template.sleep": "Sommeil",
        "profile.previewSize": "Taille du widget",
        "profile.preview.small": "Petit",
        "profile.preview.medium": "Moyen",
        "profile.preview.large": "Grand",
        "profile.previewCount": "Affiche %d mesures sur %d. Toutes les mesures sélectionnées sont disponibles dans la vue d’ensemble.",
        "widget.galleryTitle": "Résumé Garmin",
        "widget.galleryDescription": "Santé, sommeil, activité et entraînement dans cinq widgets prêts à l’emploi.",
        "widget.galleryStaticDescription": "Choisissez un type et une taille de widget. Les mesures disponibles s’affichent automatiquement.",
        "connection.webTitle": "Connecter Garmin",
        "connection.webSubtitle": "Connectez-vous une fois. Vos mesures s’actualisent automatiquement.",
        "connection.webIntro": "Se connecter à Garmin Connect",
        "connection.webDetail": "Une fenêtre Garmin sécurisée s’ouvrira. Terminez la connexion et les vérifications demandées par Garmin. L’app conservera ensuite cette connexion sur votre Mac.",
        "connection.webSignIn": "Se connecter avec Garmin",
        "connection.webPrivacy": "Les mesures et la session du site Garmin restent sur ce Mac. Votre mot de passe est transmis directement à Garmin. Il n’y a ni serveur distinct ni analyse d’utilisation.",
        "connection.automaticHint": "Vos données s’actualisent en arrière-plan, y compris au réveil du Mac. Laissez Garmin Desk ouvert pour les actualisations automatiques.",
        "connection.reconnect": "Reconnecter Garmin",
        "connection.nextSync": "Prochaine actualisation après",
        "error.partial": "Certaines mesures n’ont pas pu être actualisées. Les données enregistrées restent disponibles.",
        "diagnostic.title": "Détails de connexion",
        "diagnostic.stage": "Étape",
        "diagnostic.apiCode": "Code Garmin",
        "diagnostic.requests": "Réponses reçues",
        "menu.edit": "Édition",
        "menu.cut": "Couper",
        "menu.copy": "Copier",
        "menu.paste": "Coller",
        "menu.selectAll": "Tout sélectionner",
        "app.subtitle": "Votre journée en un coup d’œil",
        "app.device": "Garmin fēnix 8",
        "dashboard.title": "Vue d’ensemble",
        "dashboard.profile": "Profil",
        "dashboard.moreMetrics": "Les widgets plus grands peuvent afficher plus de mesures",
        "dashboard.configure": "Réglages des widgets",
        "widget.setup": "Configurer les widgets du bureau",
        "widget.customize": "Réglages des widgets",
        "widget.guide.add": "Faites un clic droit sur le bureau et choisissez Modifier les widgets. Trouvez GarminDesk dans la galerie.",
        "widget.guide.profile": "Choisissez un type et une taille de widget, puis ajoutez-le au bureau.",
        "widget.guide.refresh": "Garmin Desk récupère vos mesures. macOS détermine quand le widget du bureau s’actualise.",
        "widget.sharingUnavailable": "Les widgets de bureau ne sont pas disponibles dans cette version. Vos mesures restent consultables dans l’app.",
        "widget.openApp": "Ouvrir GarminDesk",
        "widget.openAppHint": "Connectez votre compte Garmin dans l’app.",
        "widget.profileMissing": "Profil supprimé",
        "widget.profileMissingHint": "Choisissez un autre profil dans les réglages de ce widget.",
        "widget.demo": "DÉMO",
        "widget.connect": "Connectez Garmin dans l’app",
        "dashboard.empty": "Choisissez les mesures à afficher dans les réglages.",
        "dashboard.connect": "Connecter Garmin",
        "action.settings": "Réglages",
        "action.sync": "Actualiser",
        "action.quit": "Quitter Garmin Desk",
        "action.cancel": "Annuler",
        "action.save": "Enregistrer",
        "action.delete": "Supprimer",
        "action.duplicate": "Dupliquer",
        "action.add": "Ajouter un profil",
        "action.up": "Monter",
        "action.down": "Descendre",
        "action.show": "Afficher",
        "action.hide": "Masquer",
        "action.done": "Terminé",
        "action.retry": "Réessayer",
        "data.demo": "Données de démonstration",
        "data.updated": "Vérifié",
        "data.stale": "Les données peuvent être obsolètes",
        "data.day": "Données du",
        "data.partial": "Certaines mesures sont indisponibles",
        "data.emptyDay": "Garmin n’a pas encore de mesures pour cette date. Synchronisez votre montre avec Garmin Connect pour les actualiser.",
        "data.empty": "Aucune mesure pour le moment",
        "data.demoDetail": "Valeurs d’exemple. Connectez votre compte pour voir vos mesures.",
        "data.local": "Stocké sur ce Mac",
        "data.source": "Dernière synchronisation Garmin Connect",
        "data.syncing": "Vérification de Garmin Connect…",
        "status.connected": "Garmin connecté",
        "status.notConnected": "Garmin non connecté",
        "status.connecting": "Connexion en cours…",
        "settings.title": "Réglages",
        "settings.profiles": "Profils de widgets",
        "settings.connection": "Compte Garmin",
        "settings.general": "Général",
        "settings.profilesSubtitle": "Créez une vue pour chaque moment de votre journée.",
        "settings.generalSubtitle": "Adaptez Garmin Desk à votre Mac.",
        "profile.name": "Nom du profil",
        "profile.primary": "Mesure principale",
        "profile.metrics": "Mesures",
        "profile.metricsHint": "Choisissez les éléments à afficher. La mesure principale apparaît toujours en premier.",
        "profile.appearance": "Apparence",
        "profile.style": "Style",
        "profile.density": "Densité",
        "profile.preview": "Aperçu",
        "profile.added": "Nouveau profil",
        "profile.new": "Nouveau profil",
        "profile.default": "Ma journée",
        "profile.copy": "Copie",
        "profile.untitled": "Profil sans titre",
        "profile.deleteTitle": "Supprimer ce profil ?",
        "profile.deleteMessage": "Le profil sera supprimé. Vos données Garmin resteront sur ce Mac.",
        "profile.oneRequired": "Conservez au moins un profil.",
        "profile.enabled": "Inclus",
        "profile.available": "Mesures disponibles",
        "profile.count": "mesures",
        "profile.mainBadge": "Principale",
        "style.calm": "Calme",
        "style.sport": "Sport",
        "style.monochrome": "Monochrome",
        "density.comfortable": "Aérée",
        "density.compact": "Compacte",
        "connection.title": "Votre compte Garmin",
        "connection.subtitle": "Votre Mac se connecte directement à Garmin Connect.",
        "connection.localTitle": "Vos données restent avec vous",
        "connection.localDetail": "Les mesures sont mises en cache sur ce Mac. Les identifiants de session sont conservés dans le trousseau macOS. L’app n’a pas de serveur distinct.",
        "connection.email": "E-mail",
        "connection.password": "Mot de passe",
        "connection.china": "Utiliser Garmin Chine",
        "connection.signIn": "Connecter le compte",
        "connection.disconnect": "Déconnecter et effacer les données locales",
        "connection.disconnectTitle": "Déconnecter Garmin ?",
        "connection.disconnectMessage": "La session Garmin enregistrée et les mesures en cache seront supprimées de ce Mac. Vos préférences sont conservées.",
        "connection.demo": "Explorer avec des données de démonstration",
        "connection.demoHint": "Les valeurs de démonstration sont toujours signalées.",
        "connection.syncHint": "Synchronisez votre montre avec Garmin Connect pour rendre de nouvelles mesures disponibles ici.",
        "connection.secureHint": "Votre mot de passe sert uniquement à la connexion et n’est pas enregistré par cette app.",
        "connection.mfaTitle": "Code de vérification",
        "connection.mfaHint": "Saisissez le code demandé par Garmin pour terminer la connexion.",
        "connection.mfaCode": "Code",
        "connection.verify": "Vérifier",
        "connection.cancelLogin": "Annuler la connexion",
        "general.language": "Langue",
        "general.appearance": "Apparence",
        "general.refresh": "Intervalle d’actualisation",
        "general.system": "Selon le système",
        "general.light": "Clair",
        "general.dark": "Sombre",
        "general.minutes5": "Toutes les 5 minutes",
        "general.minutes15": "Toutes les 15 minutes",
        "general.minutes30": "Toutes les 30 minutes",
        "general.minutes60": "Toutes les heures",
        "general.refreshHint": "Les actualisations utilisent les dernières mesures disponibles dans Garmin Connect.",
        "general.localNotice": "Vos préférences sont enregistrées automatiquement sur ce Mac.",
        "general.launchAtLogin": "Ouvrir Garmin Desk à l’ouverture de session",
        "general.backgroundHint": "Les actualisations automatiques continuent après la fermeture de la fenêtre. Choisissez « Quitter Garmin Desk » ou appuyez sur ⌘Q pour arrêter l’app.",
        "menu.about": "À propos de Garmin Desk",
        "menu.hideApp": "Masquer Garmin Desk",
        "menu.hideOthers": "Masquer les autres",
        "menu.showAll": "Tout afficher",
        "menu.file": "Fichier",
        "menu.closeWindow": "Fermer la fenêtre",
        "menu.window": "Fenêtre",
        "menu.mainWindow": "Garmin Desk",
        "menu.minimize": "Réduire",
        "menu.zoom": "Agrandir/réduire",
        "category.health": "Santé et récupération",
        "category.sleep": "Sommeil",
        "category.activity": "Activité quotidienne",
        "category.training": "Entraînement",
        "category.body": "Corps et hydratation",
        "metric.steps": "Pas",
        "metric.stepGoal": "Objectif de pas",
        "metric.distance": "Distance",
        "metric.calories": "Calories totales",
        "metric.activeCalories": "Calories actives",
        "metric.floors": "Étages gravis",
        "metric.intensityMinutes": "Minutes intensives",
        "metric.restingHeartRate": "Fréquence cardiaque au repos",
        "metric.heartRate": "Dernière fréquence cardiaque",
        "metric.stress": "Stress quotidien moyen",
        "metric.bodyBattery": "Body Battery",
        "metric.sleepDuration": "Durée du sommeil",
        "metric.sleepScore": "Score de sommeil",
        "metric.deepSleep": "Sommeil profond",
        "metric.remSleep": "Sommeil paradoxal",
        "metric.lightSleep": "Sommeil léger",
        "metric.awakeSleep": "Temps éveillé",
        "metric.hrv": "VFC nocturne",
        "metric.spo2": "SpO₂ quotidienne moyenne",
        "metric.respiration": "Respiration moyenne pendant le sommeil",
        "metric.trainingReadiness": "Préparation à l’entraînement",
        "metric.recoveryTime": "Temps de récupération",
        "metric.vo2Max": "VO₂ max en course",
        "metric.trainingLoad": "Charge d’entraînement aiguë",
        "metric.weight": "Poids",
        "metric.hydration": "Hydratation",
        "metric.short.sleepDuration": "Sommeil",
        "metric.short.stress": "Stress · journée",
        "metric.short.restingHeartRate": "FC au repos",
        "metric.short.trainingReadiness": "Préparation",
        "metric.short.hrv": "VFC · nuit",
        "metric.short.respiration": "Respir. · sommeil",
        "metric.short.intensityMinutes": "Min. intensives",
        "metric.short.activeCalories": "Calories actives",
        "metric.short.recoveryTime": "Récupération",
        "metric.short.trainingLoad": "Charge aiguë",
        "metric.short.vo2Max": "VO₂ max course",
        "metric.short.calories": "Calories totales",
        "unit.minutes": "min",
        "unit.hours": "h",
        "unit.km": "km",
        "unit.kg": "kg",
        "unit.ml": "ml",
        "unit.bpm": "bpm",
        "unit.kcal": "kcal",
        "unit.ms": "ms",
        "unit.breaths": "resp/min",
        "unit.vo2": "ml/kg/min",
        "error.auth": "Connexion impossible. Vérifiez vos identifiants et réessayez.",
        "error.rate_limit": "Garmin a temporairement limité les requêtes. Réessayez plus tard.",
        "error.session_unsupported": "Cette app ne peut pas restaurer la session enregistrée. Reconnectez votre compte Garmin.",
        "error.access_denied": "Garmin a refusé l’accès aux données demandées.",
        "error.security_challenge": "Une vérification de sécurité Garmin a bloqué la connexion. Réessayez plus tard.",
        "error.network": "Impossible de joindre Garmin. Vérifiez votre connexion Internet.",
        "error.dependency": "Le composant de connexion Garmin est indisponible. Réinstallez la dernière version de Garmin Desk.",
        "error.unknown": "Impossible de terminer la requête. Réessayez.",
        "error.timeout": "Garmin a mis trop de temps à répondre. Réessayez.",
        "error.keychain": "Impossible d’accéder au trousseau macOS. Vérifiez qu’il est déverrouillé.",
        "error.protocol": "Garmin a renvoyé des données que l’app n’a pas pu lire. Réessayez plus tard.",
        "error.storage": "Impossible d’enregistrer les données sur ce Mac. Vérifiez l’espace disque disponible et les autorisations.",
        "error.login_item": "Autorisez Garmin Desk à s’ouvrir à la connexion dans Réglages macOS → Général → Ouverture.",
        "training.title": "Entraînement",
        "training.last": "Dernier terminé",
        "training.next": "Prochain prévu",
        "training.completed": "Terminé",
        "training.planned": "Programmé",
        "training.recent": "Activités récentes",
        "training.upcoming": "Entraînements à venir",
        "training.workout": "Entraînement",
        "training.dateUnknown": "Date non précisée",
        "training.timeUnknown": "Heure non précisée",
        "training.localTime": "heure locale enregistrée",
        "training.durationUnknown": "Durée non précisée",
        "training.pastUnavailable": "L’historique n’est pas encore disponible",
        "training.pastUnavailableHint": "Cette section n’a pas encore pu être récupérée auprès de Garmin.",
        "training.pastEmpty": "Aucune activité dans la dernière réponse",
        "training.pastCoverage": "Jusqu’à 20 activités récentes · historique incomplet",
        "training.futureUnavailable": "Le programme n’est pas encore disponible",
        "training.futureUnavailableHint": "Un calendrier indisponible ne signifie pas qu’aucun entraînement n’est prévu.",
        "training.futureEmpty": "Aucun entraînement dans la partie récupérée",
        "training.calendar": "Calendrier Garmin publié",
        "training.adaptive": "Calendrier adaptatif vérifié",
        "training.partial": "Une partie du calendrier est indisponible",
        "training.expiredCoverage": "La période vérifiée est terminée",
        "training.refreshCalendar": "Actualisez pour vérifier une nouvelle période.",
        "training.updated": "Mis à jour",
        "training.updatedUnknown": "Heure d’actualisation inconnue",
        "training.cached": "Données enregistrées",
        "training.refreshFailed": "Cette section n’a pas pu être actualisée",
        "training.rateLimit": "Garmin limite temporairement les requêtes",
        "training.signIn": "Connectez-vous à Garmin Connect pour actualiser",
        "training.hour": "h",
        "training.minute": "min",
        "training.second": "s",
        "training.km": "km",
        "training.sport.running": "Course à pied",
        "training.sport.trail_running": "Trail",
        "training.sport.treadmill_running": "Course sur tapis",
        "training.sport.track_running": "Course sur piste",
        "training.sport.cycling": "Cyclisme",
        "training.sport.mountain_biking": "VTT",
        "training.sport.indoor_cycling": "Vélo d’intérieur",
        "training.sport.swimming": "Natation",
        "training.sport.open_water_swimming": "Natation en eau libre",
        "training.sport.walking": "Marche",
        "training.sport.hiking": "Randonnée",
        "training.sport.strength_training": "Musculation",
        "training.sport.cardio_training": "Cardio",
        "training.sport.elliptical": "Vélo elliptique",
        "training.sport.stair_climbing": "Montée d’escaliers",
        "training.sport.yoga": "Yoga",
        "training.sport.pilates": "Pilates",
        "training.sport.rowing": "Aviron",
        "training.sport.tennis": "Tennis",
        "training.sport.golf": "Golf",
        "training.sport.alpine_skiing": "Ski alpin",
        "training.sport.cross_country_skiing": "Ski de fond",
        "training.sport.snowboarding": "Snowboard",
        "training.sport.triathlon": "Multisport",
        "training.noPublishedThrough": "Aucun entraînement publié jusqu’au %@",
        "training.checkedThrough": "vérifié jusqu’au %@",
    ]
}
