import Foundation

/// Metric explanations in ko. Garmin payload codes are never translated here.
enum LocalizationExplanationKO {
    static let strings: [String: String] = [
        "explanation.load.rangeUnavailable": "개인 범위 정보 없음",
        "explanation.load.ratio.low": "낮은 부하 비율",
        "explanation.load.ratio.optimal": "최적 부하 비율",
        "explanation.load.ratio.high": "높은 부하 비율",
        "explanation.load.ratio.veryHigh": "매우 높은 부하 비율",
        "explanation.load.ratio.value": "단기 / 장기: %@",
        "explanation.load.below": "최적 범위 미만",
        "explanation.load.above": "최적 범위 초과",
        "explanation.load.optimal": "최적 범위 내",
        "explanation.load.range": "개인 범위: %1$@–%2$@",
        "explanation.load.detail": "단기 부하는 최근 훈련이 몸에 주는 부담을 추정합니다. Garmin은 최근 세션에 더 큰 가중치를 두고 체력과 훈련 이력에 따른 범위와 비교합니다. 숫자만으로 훈련의 생산성을 알 수는 없습니다.",
        "explanation.load.ratio.detail": "부하 비율은 최근의 단기 부하를 장기 부하와 비교합니다. Garmin은 이 분류를 훈련 상태와 별도로 제공합니다.",
        "explanation.load.garminStatus": "Garmin 상태: %@",
        "explanation.load.noStatusDetail": "훈련 상태는 체력 변화와 회복도 고려합니다. 낮은 부하만으로 훈련 부족에 따른 체력 저하를 뜻하지는 않습니다. 이 측정값에는 인식 가능한 Garmin 훈련 상태가 없습니다.",
        "explanation.hrv.compare": "개인 기준과 비교하세요",
        "explanation.hrv.balanced": "주간 HRV 균형",
        "explanation.hrv.unbalanced": "주간 HRV 불균형",
        "explanation.hrv.low": "낮은 주간 HRV",
        "explanation.hrv.poor": "저조한 HRV 상태",
        "explanation.hrv.insufficient": "최근 HRV 데이터 부족",
        "explanation.hrv.weekly": "7일 평균: %1$@ %2$@",
        "explanation.hrv.baseline": "개인 기준 범위: %1$@–%2$@ %3$@",
        "explanation.hrv.detail": "표시값은 기록된 밤의 심장 박동 간격 변화의 평균입니다. Garmin은 7일 평균을 약 3주간의 수면 데이터로 만든 개인 기준과 비교합니다. 반면 ‘%@’는 연령별 기준 범위보다 훨씬 낮은 HRV를 나타냅니다. 한밤의 값과 주간 상태는 다르며 높다고 항상 좋은 것은 아닙니다.",
        "explanation.readiness.prime": "최상의 훈련 준비도",
        "explanation.readiness.high": "높은 훈련 준비도",
        "explanation.readiness.moderate": "보통 훈련 준비도",
        "explanation.readiness.low": "낮은 훈련 준비도",
        "explanation.readiness.poor": "매우 낮은 훈련 준비도",
        "explanation.readiness.detail": "Garmin은 수면, 회복 시간, HRV, 단기 부하, 최근 스트레스를 종합합니다. 1–24는 매우 낮음, 25–49는 낮음, 50–74는 보통, 75–94는 높음, 95–100은 최상입니다. 낮은 점수는 회복 우선을, 높은 점수는 강도 높은 훈련을 위한 더 큰 여력을 나타냅니다.",
        "explanation.sleep.excellent": "매우 좋은 수면",
        "explanation.sleep.good": "좋은 수면",
        "explanation.sleep.fair": "보통 수면",
        "explanation.sleep.poor": "낮은 수면의 질",
        "explanation.sleep.detail": "시간, 수면 단계, 뒤척임을 포함해 수면의 질과 회복을 평가합니다. Garmin 기준으로 60 미만은 낮음, 60–79는 보통, 80–89는 좋음, 90–100은 매우 좋음입니다. 시간만으로 점수가 결정되지는 않습니다.",
        "explanation.stress.resting": "휴식 범위",
        "explanation.stress.low": "낮은 스트레스",
        "explanation.stress.medium": "보통 스트레스",
        "explanation.stress.high": "높은 스트레스",
        "explanation.stress.detail": "Garmin이 제공하는 하루 평균 신체적 스트레스이며 현재 감정 측정값이 아닙니다. 심박 변이도를 이용한 척도에서 0–25는 휴식, 26–50은 낮음, 51–75는 보통, 76–100은 높음입니다. 일평균은 짧은 상승이나 휴식 구간을 가릴 수 있습니다.",
        "explanation.battery.veryLow": "매우 적은 에너지 잔량",
        "explanation.battery.low": "적은 에너지 잔량",
        "explanation.battery.moderate": "보통 에너지 잔량",
        "explanation.battery.high": "많은 에너지 잔량",
        "explanation.battery.detail": "Garmin은 스트레스, 심박 변이도, 수면, 활동으로 가용 에너지를 추정합니다. 휴식은 충전을, 스트레스와 활동은 소모를 일으킬 수 있습니다. 에너지 추정치이며 체력을 나타내는 백분율이 아닙니다.",
        "explanation.recovery.complete": "회복 카운트다운 완료",
        "explanation.recovery.remaining": "다음 고강도 훈련까지",
        "explanation.recovery.detail": "Garmin은 다음 고강도 훈련을 준비하는 데 필요한 시간을 추정합니다. 완전한 비활동을 요구하지는 않습니다. 수면, 스트레스, 이후 활동으로 추정치가 변할 수 있습니다. 마지막으로 수신한 Garmin 값입니다.",
        "explanation.vo2.status": "유산소 체력 추정",
        "explanation.vo2.detail": "체중 1kg당 1분 동안의 최대 산소 소비량 추정치입니다. Garmin의 체력 분류는 나이와 성별에 따라 달라지지만 앱에는 분류에 충분한 프로필 정보가 없습니다. 한 번의 값보다 비슷한 조건에서의 추이를 비교하세요.",
        "explanation.restingHR.status": "개인 추이를 살펴보세요",
        "explanation.restingHR.detail": "Garmin의 일일 안정 시 심박수입니다. 여러 날을 평소 수준과 비교하세요. 체력, 수면, 스트레스, 회복이 영향을 주며 낮다고 항상 좋은 것은 아닙니다.",
        "explanation.oxygen.status": "평균 산소포화도 추정",
        "explanation.oxygen.detail": "시계가 추정한 혈중 산소포화도입니다. 측정 조건과 고도가 영향을 줍니다. 일평균 하나로 건강을 평가하거나 밤중의 짧은 변화를 알 수는 없습니다.",
        "explanation.respiration.status": "수면 중 평균",
        "explanation.respiration.detail": "수면 중 분당 평균 호흡수입니다. 여러 밤과 장기 추이를 비교하세요. 현재 호흡수는 아닙니다.",
        "explanation.sleepDuration.status": "총 수면 시간",
        "explanation.sleepDuration.detail": "기록된 밤에 Garmin이 수면으로 분류한 시간으로, 얕은 수면, 깊은 수면, 렘수면을 합한 값입니다. 시간과 함께 수면 점수와 개운함도 살펴보세요.",
        "explanation.sleepStage.awake": "수면 시간대의 깨어 있음",
        "explanation.sleepStage.status": "기록된 밤의 일부",
        "explanation.sleepStage.detail": "Garmin은 센서로 수면 단계를 추정합니다. 단계별 시간은 밤마다 달라지므로 개별 값에 보편적인 좋고 나쁨의 기준은 없습니다. 총 수면, 수면 점수, 여러 밤의 패턴과 함께 보세요.",
        "explanation.steps.status": "일일 걷기 활동",
        "explanation.steps.reached": "일일 목표 달성",
        "explanation.steps.progress": "일일 목표 진행 상황",
        "explanation.steps.goalDetail": "개인의 Garmin 일일 목표와 비교한 걸음 수입니다. 목표는 지향점이며 보편적인 체력 척도는 아닙니다.",
        "explanation.steps.goal": "목표: %@",
        "explanation.steps.detail": "해당 날짜에 기록한 걸음 수입니다. 진행 상황을 평가하려면 개인 걸음 목표가 필요합니다.",
        "explanation.stepsTarget.status": "Garmin 개인 일일 목표",
        "explanation.stepsTarget.detail": "직접 설정하거나 Garmin이 자동 조정한 걸음 목표입니다. 개인마다 다르며 매일 달라질 수 있습니다.",
        "explanation.intensity.status": "강도를 반영한 활동 시간",
        "explanation.intensity.detail": "Garmin은 중강도 활동 시간을 그대로, 고강도 활동 시간을 두 배로 계산합니다. 하루 합계가 실제 훈련 시간보다 길 수 있으며 주간 합계는 아닙니다.",
        "explanation.calories.status": "휴식 + 활동 에너지",
        "explanation.calories.detail": "안정 시 대사와 활동을 포함한 하루 총 에너지 소비량 추정치입니다. 섭취량이나 칼로리 부족량이 아닙니다.",
        "explanation.activeCalories.status": "활동으로 소비한 에너지",
        "explanation.activeCalories.detail": "안정 시 필요량을 초과해 활동으로 소비한 에너지 추정치입니다. 총 칼로리에 이미 포함되므로 두 값을 더하지 마세요.",
        "explanation.distance.status": "일일 이동 거리",
        "explanation.distance.detail": "Garmin 일일 요약의 거리입니다. 하루 활동 합계이며 마지막 훈련 거리와 반드시 같지는 않습니다.",
        "explanation.floors.status": "오른 층수",
        "explanation.floors.detail": "Garmin이 추정한 하루 동안 올라간 층수입니다. 위로 이동한 양이며 내려간 계단 수가 아닙니다.",
        "explanation.weight.status": "최근 기록된 측정값",
        "explanation.weight.detail": "이 기록에서 이용 가능한 가장 최근 체중 측정값입니다. 일시적인 변화는 체내 수분과 측정 시각의 영향일 수 있습니다. 체중만으로 체력이나 건강이 결정되지는 않습니다.",
        "explanation.hydration.status": "기록한 수분 섭취량",
        "explanation.hydration.detail": "Garmin Connect에 입력한 수분 섭취량입니다. 사용자의 기록이며 센서로 측정한 수분 상태나 개인의 일일 필요량은 아닙니다.",
        "explanation.training.DETRAINING.title": "훈련 부족",
        "explanation.training.DETRAINING.detail": "Garmin이 장기간의 훈련 감소 후 체력 저하를 감지했습니다.",
        "explanation.training.RECOVERY.title": "회복",
        "explanation.training.RECOVERY.detail": "가벼운 훈련으로 높은 강도의 운동에서 회복하고 있습니다.",
        "explanation.training.MAINTAINING.title": "유지",
        "explanation.training.MAINTAINING.detail": "현재 훈련은 뚜렷한 향상 없이 체력을 유지합니다.",
        "explanation.training.PRODUCTIVE.title": "생산적",
        "explanation.training.PRODUCTIVE.detail": "Garmin이 현재 훈련에 따른 체력 향상을 감지했습니다.",
        "explanation.training.PEAKING.title": "최고 상태",
        "explanation.training.PEAKING.detail": "줄어든 부하가 회복과 단기적인 최고 성과에 도움이 되었습니다.",
        "explanation.training.OVERREACHING.title": "과도한 훈련",
        "explanation.training.OVERREACHING.detail": "Garmin은 훈련 부하가 매우 높아 역효과를 낸다고 평가합니다.",
        "explanation.training.UNPRODUCTIVE.title": "비생산적",
        "explanation.training.UNPRODUCTIVE.detail": "적절한 부하에도 체력이 떨어지고 있습니다. 수면, 영양, 스트레스도 영향을 줍니다.",
        "explanation.training.STRAINED.title": "부담 누적",
        "explanation.training.STRAINED.detail": "Garmin이 훈련과 회복 사이의 불균형을 감지했습니다.",
        "explanation.training.NO_STATUS.title": "상태 없음",
        "explanation.training.NO_STATUS.detail": "Garmin에 상태 평가에 적합한 훈련 데이터가 아직 충분하지 않습니다.",
        "explanation.training.PAUSED.title": "일시 중지",
        "explanation.training.PAUSED.detail": "Garmin의 훈련 상태 평가가 일시 중지되어 있습니다.",
        "explanation.help": "이 지표의 의미",
        "explanation.source": "Garmin에서 자세히 보기",
        "explanation.forecast": "최근 Garmin 측정값으로 앱에서 계산한 선형 추정입니다. %@",
        "explanation.labeledDetail": "%1$@: %2$@",
    ]
}
