import Foundation

/// Metric explanations in de. Garmin payload codes are never translated here.
enum LocalizationExplanationDE {
    static let strings: [String: String] = [
        "explanation.load.rangeUnavailable": "Persönlicher Bereich fehlt",
        "explanation.load.ratio.low": "Niedriges Belastungsverhältnis",
        "explanation.load.ratio.optimal": "Optimales Belastungsverhältnis",
        "explanation.load.ratio.high": "Hohes Belastungsverhältnis",
        "explanation.load.ratio.veryHigh": "Sehr hohes Belastungsverhältnis",
        "explanation.load.ratio.value": "Akut / chronisch: %@",
        "explanation.load.below": "Unter dem optimalen Bereich",
        "explanation.load.above": "Über dem optimalen Bereich",
        "explanation.load.optimal": "Im optimalen Bereich",
        "explanation.load.range": "Dein Bereich: %1$@–%2$@",
        "explanation.load.detail": "Die akute Belastung schätzt die Beanspruchung durch kürzliches Training. Garmin gewichtet neuere Einheiten stärker und vergleicht den Wert mit einem Bereich aus Fitness und Trainingsverlauf. Die Zahl allein zeigt nicht, ob dein Training produktiv ist.",
        "explanation.load.ratio.detail": "Das Belastungsverhältnis vergleicht die kurzfristige akute mit der längerfristigen chronischen Belastung. Garmin liefert diese Kategorie getrennt vom Trainingszustand.",
        "explanation.load.garminStatus": "Garmin-Status: %@",
        "explanation.load.noStatusDetail": "Der Trainingszustand berücksichtigt auch Fitnessentwicklung und Erholung. Niedrige Belastung allein bedeutet keinen Formverlust. Für diesen Wert liegt kein erkannter Garmin-Trainingszustand vor.",
        "explanation.hrv.compare": "Mit deinem Basisbereich vergleichen",
        "explanation.hrv.balanced": "Wöchentliche HFV ausgewogen",
        "explanation.hrv.unbalanced": "Wöchentliche HFV unausgewogen",
        "explanation.hrv.low": "Niedrige wöchentliche HFV",
        "explanation.hrv.poor": "Schlechter HFV-Status",
        "explanation.hrv.insufficient": "Zu wenige aktuelle HFV-Daten",
        "explanation.hrv.weekly": "7-Tage-Durchschnitt: %1$@ %2$@",
        "explanation.hrv.baseline": "Dein Basisbereich: %1$@–%2$@ %3$@",
        "explanation.hrv.detail": "Der Wert zeigt die durchschnittliche Schwankung der Herzschlagintervalle in der letzten Nacht. Der Garmin-HFV-Status vergleicht den 7-Tage-Durchschnitt mit deinem Basisbereich, für den etwa drei Wochen Schlafdaten nötig sind. Eine Nacht ist nicht der Wochenstatus; höher ist nicht immer besser.",
        "explanation.readiness.prime": "Optimale Trainingsbereitschaft",
        "explanation.readiness.high": "Hohe Trainingsbereitschaft",
        "explanation.readiness.moderate": "Mäßige Trainingsbereitschaft",
        "explanation.readiness.low": "Niedrige Trainingsbereitschaft",
        "explanation.readiness.poor": "Sehr niedrige Trainingsbereitschaft",
        "explanation.readiness.detail": "Garmin kombiniert Schlaf, Erholungszeit, HFV, akute Belastung und vergangenen Stress. Skala: 1–24 sehr niedrig, 25–49 niedrig, 50–74 mäßig, 75–94 hoch, 95–100 optimal. Niedrige Werte sprechen für mehr Erholung; hohe für mehr Kapazität für anstrengendes Training.",
        "explanation.sleep.excellent": "Ausgezeichneter Schlaf",
        "explanation.sleep.good": "Guter Schlaf",
        "explanation.sleep.fair": "Ordentlicher Schlaf",
        "explanation.sleep.poor": "Schlechter Schlaf",
        "explanation.sleep.detail": "Bewertung von Schlafqualität und Erholung anhand von Dauer, Schlafphasen und Unruhe. Garmin-Skala: unter 60 schlecht, 60–79 ordentlich, 80–89 gut, 90–100 ausgezeichnet. Die Dauer allein bestimmt den Wert nicht.",
        "explanation.stress.resting": "Ruhebereich",
        "explanation.stress.low": "Niedriger Stress",
        "explanation.stress.medium": "Mittlerer Stress",
        "explanation.stress.high": "Hoher Stress",
        "explanation.stress.detail": "Der durchschnittliche körperliche Stress dieses Tages laut Garmin, keine aktuelle Gefühlsmessung. Die Skala basiert auf der Herzfrequenzvariabilität: 0–25 Ruhe, 26–50 niedrig, 51–75 mittel, 76–100 hoch. Der Tagesdurchschnitt kann kurze Spitzen und Ruhephasen verdecken.",
        "explanation.battery.veryLow": "Sehr geringe Energiereserve",
        "explanation.battery.low": "Geringe Energiereserve",
        "explanation.battery.moderate": "Mittlere Energiereserve",
        "explanation.battery.high": "Hohe Energiereserve",
        "explanation.battery.detail": "Garmin schätzt deine verfügbare Energie anhand von Stress, Herzfrequenzvariabilität, Schlaf und Aktivität. Ruhe kann sie auffüllen, Stress und Aktivität können sie verbrauchen. Das ist eine Energieschätzung, kein Prozentsatz deiner Fitness.",
        "explanation.recovery.complete": "Erholungszeit abgelaufen",
        "explanation.recovery.remaining": "Bis zum nächsten harten Training",
        "explanation.recovery.detail": "Garmin schätzt die Zeit bis zum nächsten anstrengenden Training. Das bedeutet keine vollständige Inaktivität. Schlaf, Stress und weitere Aktivität können die Schätzung verändern. Angezeigt wird der zuletzt empfangene Garmin-Wert.",
        "explanation.vo2.status": "Geschätzte aerobe Fitness",
        "explanation.vo2.detail": "Geschätzte maximale Sauerstoffaufnahme pro Kilogramm und Minute. Garmins Fitnesskategorien hängen von Alter und Geschlecht ab; der App fehlen Profildaten für die Einordnung. Vergleiche deinen Verlauf unter ähnlichen Bedingungen statt eines Einzelwerts.",
        "explanation.restingHR.status": "Deinen eigenen Verlauf betrachten",
        "explanation.restingHR.detail": "Garmins täglicher Ruhepuls. Vergleiche mehrere Tage mit deinem üblichen Niveau. Fitness, Schlaf, Stress und Erholung beeinflussen ihn; niedriger ist nicht immer besser.",
        "explanation.oxygen.status": "Mittlere Sauerstoffschätzung",
        "explanation.oxygen.detail": "Von der Uhr geschätzte Sauerstoffsättigung im Blut. Messbedingungen und Höhe beeinflussen das Ergebnis. Ein Tagesdurchschnitt bewertet weder die Gesundheit noch kurze nächtliche Veränderungen.",
        "explanation.respiration.status": "Durchschnitt im Schlaf",
        "explanation.respiration.detail": "Durchschnittliche Atemzüge pro Minute im Schlaf. Vergleiche deine Nächte und den längerfristigen Verlauf; das ist nicht deine aktuelle Atemfrequenz.",
        "explanation.sleepDuration.status": "Gesamte Schlafzeit",
        "explanation.sleepDuration.detail": "Die von Garmin in der erfassten Nacht als Schlaf eingestufte Zeit: Leicht-, Tief- und REM-Schlaf. Betrachte neben der Dauer auch den Schlafscore und wie erholt du dich fühlst.",
        "explanation.sleepStage.awake": "Wach während der Schlafperiode",
        "explanation.sleepStage.status": "Teil der erfassten Nacht",
        "explanation.sleepStage.detail": "Garmin schätzt Schlafphasen aus Sensordaten. Ihre Dauer schwankt zwischen Nächten; es gibt keinen universellen guten oder schlechten Einzelwert. Betrachte Gesamtschlaf, Schlafscore und den Verlauf mehrerer Nächte zusammen.",
        "explanation.steps.status": "Tägliche Gehaktivität",
        "explanation.steps.reached": "Tagesziel erreicht",
        "explanation.steps.progress": "Fortschritt zum Tagesziel",
        "explanation.steps.goalDetail": "Schritte im Vergleich zu deinem eigenen Garmin-Tagesziel. Das Ziel ist ein Richtwert, kein universeller Fitnessmaßstab.",
        "explanation.steps.goal": "Ziel: %@",
        "explanation.steps.detail": "Für diesen Tag erfasste Schritte. Zur Bewertung des Fortschritts wird ein persönliches Schrittziel benötigt.",
        "explanation.stepsTarget.status": "Dein Garmin-Tagesziel",
        "explanation.stepsTarget.detail": "Das manuell festgelegte oder von Garmin automatisch angepasste Schrittziel. Es ist persönlich und kann sich täglich ändern.",
        "explanation.intensity.status": "Gewichtete Aktivitätsminuten",
        "explanation.intensity.detail": "Garmin zählt Minuten mäßiger Aktivität einfach und intensive Minuten doppelt. Der Tageswert kann die Trainingsdauer übersteigen; er ist nicht die Wochensumme.",
        "explanation.calories.status": "Ruhe- und Aktivitätsenergie",
        "explanation.calories.detail": "Geschätzter Energieverbrauch des Tages einschließlich Ruheumsatz und Aktivität. Das ist Verbrauch, keine Nahrungsaufnahme und kein Kaloriendefizit.",
        "explanation.activeCalories.status": "Energie durch Aktivität",
        "explanation.activeCalories.detail": "Geschätzter Energieverbrauch durch Aktivität über den Ruhebedarf hinaus. Er ist bereits in den Gesamtkalorien enthalten; beide Werte nicht addieren.",
        "explanation.distance.status": "Tägliche Bewegungsdistanz",
        "explanation.distance.detail": "Distanz aus Garmins Tagesübersicht. Sie umfasst die tägliche Aktivität und entspricht nicht unbedingt der Strecke des letzten Trainings.",
        "explanation.floors.status": "Hochgestiegene Stockwerke",
        "explanation.floors.detail": "Garmins Schätzung der am Tag hochgestiegenen Stockwerke. Sie erfasst Aufwärtsbewegung, nicht heruntergegangene Treppen.",
        "explanation.weight.status": "Letzte erfasste Messung",
        "explanation.weight.detail": "Die zuletzt verfügbare Gewichtsmessung für diesen Datensatz. Einzelne Änderungen können vom Flüssigkeitshaushalt und Messzeitpunkt abhängen. Gewicht allein bestimmt weder Fitness noch Gesundheit.",
        "explanation.hydration.status": "Erfasste Trinkmenge",
        "explanation.hydration.detail": "In Garmin Connect protokollierte Flüssigkeitsaufnahme. Der Wert beruht auf deinen Einträgen, nicht auf einer Sensormessung der Hydration oder deinem persönlichen Tagesbedarf.",
        "explanation.training.DETRAINING.title": "Formverlust",
        "explanation.training.DETRAINING.detail": "Garmin erkennt nach länger reduziertem Training eine abnehmende Fitness.",
        "explanation.training.RECOVERY.title": "Erholung",
        "explanation.training.RECOVERY.detail": "Weniger Training ermöglicht die Erholung von hoher Belastung.",
        "explanation.training.MAINTAINING.title": "Formerhalt",
        "explanation.training.MAINTAINING.detail": "Das aktuelle Training erhält die Fitness ohne deutliche Verbesserung.",
        "explanation.training.PRODUCTIVE.title": "Formaufbau",
        "explanation.training.PRODUCTIVE.detail": "Garmin erkennt mit dem aktuellen Training eine Verbesserung der Fitness.",
        "explanation.training.PEAKING.title": "Höchstform",
        "explanation.training.PEAKING.detail": "Die verringerte Belastung hat Erholung und eine kurzfristige Leistungsspitze ermöglicht.",
        "explanation.training.OVERREACHING.title": "Überbelastung",
        "explanation.training.OVERREACHING.detail": "Die Trainingsbelastung übersteigt die Erholungskapazität und begrenzt Fortschritte.",
        "explanation.training.UNPRODUCTIVE.title": "Unproduktiv",
        "explanation.training.UNPRODUCTIVE.detail": "Die Fitness sinkt trotz ausreichender Belastung; Schlaf, Ernährung und Stress spielen ebenfalls eine Rolle.",
        "explanation.training.STRAINED.title": "Überbeansprucht",
        "explanation.training.STRAINED.detail": "Garmin erkennt ein Ungleichgewicht zwischen Training und Erholung.",
        "explanation.training.NO_STATUS.title": "Kein Status",
        "explanation.training.NO_STATUS.detail": "Garmin hat noch nicht genug geeignete Trainingsdaten gesammelt.",
        "explanation.training.PAUSED.title": "Pausiert",
        "explanation.training.PAUSED.detail": "Die Bewertung des Trainingszustands ist in Garmin pausiert.",
        "explanation.help": "Was bedeutet dieser Wert?",
        "explanation.source": "Mehr bei Garmin erfahren",
        "explanation.forecast": "Lineare Schätzung aus dem letzten Garmin-Trend. %@",
        "explanation.labeledDetail": "%1$@: %2$@",
    ]
}
