// ko translations shared by the app and WidgetKit.
enum LocalizationKO {
    static let strings: [String: String] = [
        "widget.summary.minimum": "항목을 하나 이상 선택해 두세요.",
        "widget.summary.hint": "선택한 항목 중 데이터가 있는 항목만 표시합니다. 표시되는 항목 수는 위젯 크기에 따라 달라집니다.",
        "widget.summary.primary": "우선 표시할 주요 항목",
        "widget.summary.choose": "측정 항목 선택",
        "settings.widgets": "위젯",
        "settings.widgetsSubtitle": "데스크탑에서 바로 쓰는 다섯 가지 위젯.",
        "widget.type": "위젯 종류",
        "widget.appearance": "위젯 모양",
        "widget.appearance.colorful": "컬러",
        "widget.appearance.light": "라이트",
        "widget.appearance.dark": "다크",
        "widget.appearanceHint": "다섯 가지 데스크탑 위젯에 모두 적용됩니다.",
        "widget.automaticHint": "사용 가능한 측정값이 자동으로 선택됩니다.",
        "widget.guide.fixedTypes": "위젯 종류와 크기를 선택한 다음 데스크탑에 추가하세요.",
        "widget.slot.day": "하루",
        "widget.slot.day.description": "Body Battery, 걸음 수, 스트레스와 일일 활동.",
        "onboarding.title": "Mac에서 만나는 Garmin 데이터",
        "onboarding.privacy": "측정값은 이 Mac에 저장됩니다",
        "onboarding.detail": "Garmin 계정을 연결하면 앱과 데스크탑 위젯에서 측정값을 볼 수 있습니다.",
        "data.available": "최신 측정값",
        "data.nightEnding": "수면 종료일",
        "data.measured": "측정 시각",
        "data.received": "수신 시각",
        "metric.short.spo2": "SpO₂ · 일평균",
        "data.waiting": "워치 데이터를 기다리는 중",
        "data.waitingNew": "새 측정값을 기다리는 중",
        "data.unchanged": "측정값에 변화가 없습니다",
        "data.checkFailed": "Garmin 데이터를 새로 고치지 못했습니다",
        "data.unchangedHint": "최신 측정값이 보이지 않나요? 휴대전화에서 Garmin Connect를 열고 워치를 동기화하세요. 새 데이터를 자동으로 가져옵니다.",
        "data.retainedAllHint": "마지막 측정값과 날짜가 아래에 표시됩니다. 휴대전화의 Garmin Connect에서 워치를 동기화하면 새 측정값을 가져올 수 있습니다.",
        "data.previous": "마지막 데이터",
        "data.retainedHint": "일부 측정값이 아직 도착하지 않았습니다. 이전 값과 날짜를 보관하고 있습니다. 휴대전화의 Garmin Connect에서 워치를 동기화하세요.",
        "data.waitingHint": "휴대전화의 Garmin Connect에서 워치를 동기화하세요. 측정값이 자동으로 표시됩니다.",
        "widget.notice.connection": "Garmin 다시 연결",
        "widget.notice.unavailable": "업데이트 실패",
        "widget.notice.waiting": "새 데이터 대기 중",
        "widget.waiting": "데이터 대기 중",
        "widget.waitingHint": "휴대전화의 Garmin Connect에서 워치를 동기화하세요. 측정값이 자동으로 표시됩니다.",
        "widget.previous": "마지막 데이터",
        "widget.slot.overview.description": "선택한 측정 항목을 하나의 위젯에 표시합니다.",
        "widget.slot.sport.description": "훈련 준비도, 회복, 부하와 VO₂ max.",
        "widget.slot.sleep.description": "수면 시간, 수면 점수와 야간 HRV.",
        "widget.slot.training.description": "완료한 활동과 예정된 운동을 표시하는 캘린더.",
        "widget.preview.easyRun": "가벼운 달리기",
        "widget.preview.intervals": "인터벌 달리기",
        "profile.availableMetrics": "사용 가능한 측정값 사용",
        "profile.availableMetricsHint": "측정값이 없는 항목은 건너뛰고 관련 지표로 위젯을 채웁니다. 선택한 항목을 그대로 유지하려면 끄세요.",
        "profile.content": "표시 내용",
        "content.metrics": "지표",
        "content.training": "훈련 캘린더",
        "content.mixed": "둘 다",
        "profile.previewMetricsOnly": "이 미리보기에는 지표가 표시됩니다. 운동 카드는 ‘요약’에서도 볼 수 있습니다.",
        "status.signInRequired": "로그인 필요",
        "connection.retryAfter": "다시 시도 가능한 시각",
        "connection.reconnectDetail": "Garmin 창을 열어 로그인을 완료하면 업데이트가 다시 시작됩니다.",
        "widget.guide.staticProfile": "위젯 종류와 크기를 선택한 다음 데스크탑에 추가하세요.",
        "widget.guide.unavailable": "앱에서 측정값과 위젯 미리보기를 확인하세요.",
        "widget.sharingDataUnavailable": "위젯 데이터를 아직 사용할 수 없습니다. 측정값은 앱에서 확인할 수 있습니다.",
        "widget.slot.overview": "요약",
        "widget.slot.sport": "스포츠",
        "widget.slot.sleep": "수면",
        "widget.slot.training": "훈련 캘린더",
        "widget.slot.firstProfile": "첫 번째 프로필",
        "widget.slot.unassigned": "프로필 선택…",
        "profile.templates": "템플릿으로 시작",
        "profile.custom": "사용자 설정 프로필",
        "profile.template.life": "일상",
        "profile.template.sport": "스포츠",
        "profile.template.sleep": "수면",
        "profile.previewSize": "위젯 크기",
        "profile.preview.small": "작게",
        "profile.preview.medium": "중간",
        "profile.preview.large": "크게",
        "profile.previewCount": "%d/%d개 지표 표시. 선택한 모든 지표는 ‘요약’에서 볼 수 있습니다.",
        "widget.galleryTitle": "Garmin 요약",
        "widget.galleryDescription": "건강, 수면, 활동과 훈련을 다섯 가지 위젯에서 확인하세요.",
        "widget.galleryStaticDescription": "위젯 종류와 크기를 선택하세요. 사용 가능한 측정값이 자동으로 표시됩니다.",
        "connection.webTitle": "Garmin 연결",
        "connection.webSubtitle": "한 번 연결하면 측정값이 자동으로 업데이트됩니다.",
        "connection.webIntro": "Garmin Connect에 로그인",
        "connection.webDetail": "안전한 Garmin 창이 열립니다. 로그인과 Garmin에서 요청하는 인증을 완료하세요. 연결 정보는 이 Mac에 유지됩니다.",
        "connection.webSignIn": "Garmin으로 로그인",
        "connection.webPrivacy": "측정값과 Garmin 웹사이트 세션은 이 Mac에 저장됩니다. 암호는 Garmin으로 직접 전송됩니다. 별도 서버나 사용 분석 기능은 없습니다.",
        "connection.automaticHint": "Mac이 잠자기에서 깨어난 뒤에도 데이터는 백그라운드에서 업데이트됩니다. 자동 업데이트를 사용하려면 Garmin Desk를 실행해 두세요.",
        "connection.reconnect": "Garmin 다시 연결",
        "connection.nextSync": "다음 업데이트 가능 시각",
        "error.partial": "일부 측정값을 새로 고치지 못했습니다. 저장된 데이터는 계속 볼 수 있습니다.",
        "diagnostic.title": "연결 세부사항",
        "diagnostic.stage": "단계",
        "diagnostic.apiCode": "Garmin 코드",
        "diagnostic.requests": "수신한 응답 수",
        "menu.edit": "편집",
        "menu.cut": "오려두기",
        "menu.copy": "복사하기",
        "menu.paste": "붙여넣기",
        "menu.selectAll": "모두 선택",
        "app.subtitle": "하루를 한눈에",
        "app.device": "Garmin fēnix 8",
        "dashboard.title": "요약",
        "dashboard.profile": "프로필",
        "dashboard.moreMetrics": "큰 위젯에서는 더 많은 지표를 볼 수 있습니다",
        "dashboard.configure": "위젯 설정",
        "widget.setup": "데스크탑 위젯 설정",
        "widget.customize": "위젯 설정",
        "widget.guide.add": "데스크탑을 오른쪽 클릭하고 위젯 편집을 선택하세요. 갤러리에서 GarminDesk를 찾으세요.",
        "widget.guide.profile": "위젯 종류와 크기를 선택한 다음 데스크탑에 추가하세요.",
        "widget.guide.refresh": "Garmin Desk가 측정값을 가져오며, 데스크탑 위젯의 업데이트 시점은 macOS가 결정합니다.",
        "widget.sharingUnavailable": "이 버전에서는 데스크탑 위젯을 사용할 수 없습니다. 측정값은 앱에서 계속 확인할 수 있습니다.",
        "widget.openApp": "GarminDesk 열기",
        "widget.openAppHint": "앱에서 Garmin 계정을 연결하세요.",
        "widget.profileMissing": "프로필이 삭제됨",
        "widget.profileMissingHint": "이 위젯의 설정에서 다른 프로필을 선택하세요.",
        "widget.demo": "데모",
        "widget.connect": "앱에서 Garmin 연결",
        "dashboard.empty": "설정에서 표시할 지표를 선택하세요.",
        "dashboard.connect": "Garmin 연결",
        "action.settings": "설정",
        "action.sync": "새로 고침",
        "action.quit": "Garmin Desk 종료",
        "action.cancel": "취소",
        "action.save": "저장",
        "action.delete": "삭제",
        "action.duplicate": "복제",
        "action.add": "프로필 추가",
        "action.up": "위로 이동",
        "action.down": "아래로 이동",
        "action.show": "보기",
        "action.hide": "가리기",
        "action.done": "완료",
        "action.retry": "다시 시도",
        "data.demo": "데모 데이터",
        "data.updated": "확인 시각",
        "data.stale": "데이터가 오래되었을 수 있습니다",
        "data.day": "데이터 날짜",
        "data.partial": "일부 측정값을 사용할 수 없습니다",
        "data.emptyDay": "Garmin에 해당 날짜의 측정값이 아직 없습니다. Garmin Connect에서 워치를 동기화하면 업데이트됩니다.",
        "data.empty": "측정값이 아직 없습니다",
        "data.demoDetail": "예시 값입니다. 계정을 연결하면 실제 측정값을 볼 수 있습니다.",
        "data.local": "이 Mac에 저장됨",
        "data.source": "최근 Garmin Connect 동기화",
        "data.syncing": "Garmin Connect 확인 중…",
        "status.connected": "Garmin 연결됨",
        "status.notConnected": "Garmin 연결 안 됨",
        "status.connecting": "연결 중…",
        "settings.title": "설정",
        "settings.profiles": "위젯 프로필",
        "settings.connection": "Garmin 계정",
        "settings.general": "일반",
        "settings.profilesSubtitle": "일상의 각 순간에 맞는 보기를 만드세요.",
        "settings.generalSubtitle": "Mac에 맞게 Garmin Desk를 설정하세요.",
        "profile.name": "프로필 이름",
        "profile.primary": "기본 지표",
        "profile.metrics": "지표",
        "profile.metricsHint": "표시할 항목을 선택하세요. 기본 지표는 항상 맨 앞에 표시됩니다.",
        "profile.appearance": "모양",
        "profile.style": "스타일",
        "profile.density": "정보 밀도",
        "profile.preview": "미리보기",
        "profile.added": "새 프로필",
        "profile.new": "새 프로필",
        "profile.default": "나의 하루",
        "profile.copy": "복사본",
        "profile.untitled": "이름 없는 프로필",
        "profile.deleteTitle": "이 프로필을 삭제할까요?",
        "profile.deleteMessage": "프로필이 삭제됩니다. Garmin 데이터는 이 Mac에 유지됩니다.",
        "profile.oneRequired": "프로필은 하나 이상 필요합니다.",
        "profile.enabled": "포함됨",
        "profile.available": "사용 가능한 지표",
        "profile.count": "개 지표",
        "profile.mainBadge": "기본",
        "style.calm": "차분하게",
        "style.sport": "스포츠",
        "style.monochrome": "단색",
        "density.comfortable": "여유롭게",
        "density.compact": "촘촘하게",
        "connection.title": "Garmin 계정",
        "connection.subtitle": "Mac이 Garmin Connect에 직접 연결됩니다.",
        "connection.localTitle": "데이터는 사용자 곁에",
        "connection.localDetail": "측정값은 이 Mac에 캐시됩니다. 세션 인증 정보는 macOS 키체인에 저장됩니다. 별도 서버는 사용하지 않습니다.",
        "connection.email": "이메일",
        "connection.password": "암호",
        "connection.china": "Garmin China 사용",
        "connection.signIn": "계정 연결",
        "connection.disconnect": "연결 해제 및 로컬 데이터 지우기",
        "connection.disconnectTitle": "Garmin 연결을 해제할까요?",
        "connection.disconnectMessage": "저장된 Garmin 세션과 측정값 캐시를 이 Mac에서 삭제합니다. 환경설정은 유지됩니다.",
        "connection.demo": "데모 데이터로 살펴보기",
        "connection.demoHint": "데모 값에는 항상 표시가 붙습니다.",
        "connection.syncHint": "Garmin Connect에서 워치를 동기화하면 새 측정값을 여기에서 볼 수 있습니다.",
        "connection.secureHint": "암호는 로그인에만 사용되며 이 앱에 저장되지 않습니다.",
        "connection.mfaTitle": "인증 코드",
        "connection.mfaHint": "Garmin에서 요청한 코드를 입력해 연결을 완료하세요.",
        "connection.mfaCode": "코드",
        "connection.verify": "확인",
        "connection.cancelLogin": "로그인 취소",
        "general.language": "언어",
        "general.appearance": "모양",
        "general.refresh": "새로 고침 간격",
        "general.system": "시스템 설정 따르기",
        "general.light": "라이트",
        "general.dark": "다크",
        "general.minutes5": "5분마다",
        "general.minutes15": "15분마다",
        "general.minutes30": "30분마다",
        "general.minutes60": "1시간마다",
        "general.refreshHint": "Garmin Connect에서 제공하는 최신 측정값을 가져옵니다.",
        "general.localNotice": "환경설정은 이 Mac에 자동으로 저장됩니다.",
        "general.launchAtLogin": "로그인 시 Garmin Desk 열기",
        "general.backgroundHint": "창을 닫아도 자동 업데이트는 계속됩니다. 앱을 중지하려면 ‘Garmin Desk 종료’를 선택하거나 ⌘Q를 누르세요.",
        "menu.about": "Garmin Desk에 관하여",
        "menu.hideApp": "Garmin Desk 가리기",
        "menu.hideOthers": "기타 가리기",
        "menu.showAll": "모두 보기",
        "menu.file": "파일",
        "menu.closeWindow": "윈도우 닫기",
        "menu.window": "윈도우",
        "menu.mainWindow": "Garmin Desk",
        "menu.minimize": "최소화",
        "menu.zoom": "확대/축소",
        "category.health": "건강 및 회복",
        "category.sleep": "수면",
        "category.activity": "일일 활동",
        "category.training": "훈련",
        "category.body": "신체 및 수분",
        "metric.steps": "걸음 수",
        "metric.stepGoal": "목표 걸음 수",
        "metric.distance": "거리",
        "metric.calories": "총 칼로리",
        "metric.activeCalories": "활동 칼로리",
        "metric.floors": "오른 층수",
        "metric.intensityMinutes": "중고강도 운동시간",
        "metric.restingHeartRate": "안정 시 심박수",
        "metric.heartRate": "최근 심박수",
        "metric.stress": "일평균 스트레스",
        "metric.bodyBattery": "Body Battery",
        "metric.sleepDuration": "수면 시간",
        "metric.sleepScore": "수면 점수",
        "metric.deepSleep": "깊은 수면",
        "metric.remSleep": "렘수면",
        "metric.lightSleep": "얕은 수면",
        "metric.awakeSleep": "깨어 있던 시간",
        "metric.hrv": "야간 HRV",
        "metric.spo2": "일평균 SpO₂",
        "metric.respiration": "수면 중 평균 호흡수",
        "metric.trainingReadiness": "훈련 준비도",
        "metric.recoveryTime": "회복 시간",
        "metric.vo2Max": "러닝 VO₂ max",
        "metric.trainingLoad": "단기 부하",
        "metric.weight": "체중",
        "metric.hydration": "수분 섭취",
        "metric.short.sleepDuration": "수면",
        "metric.short.stress": "스트레스 · 일평균",
        "metric.short.restingHeartRate": "안정 시 심박",
        "metric.short.trainingReadiness": "준비도",
        "metric.short.hrv": "HRV · 야간",
        "metric.short.respiration": "호흡 · 수면",
        "metric.short.intensityMinutes": "운동 강도 시간",
        "metric.short.activeCalories": "활동 칼로리",
        "metric.short.recoveryTime": "회복",
        "metric.short.trainingLoad": "단기 부하",
        "metric.short.vo2Max": "러닝 VO₂ max",
        "metric.short.calories": "총 칼로리",
        "unit.minutes": "분",
        "unit.hours": "시간",
        "unit.km": "km",
        "unit.kg": "kg",
        "unit.ml": "ml",
        "unit.bpm": "회/분",
        "unit.kcal": "kcal",
        "unit.ms": "ms",
        "unit.breaths": "회/분",
        "unit.vo2": "ml/kg/분",
        "error.auth": "로그인하지 못했습니다. 입력 내용을 확인하고 다시 시도하세요.",
        "error.rate_limit": "Garmin이 요청을 일시적으로 제한했습니다. 나중에 다시 시도하세요.",
        "error.session_unsupported": "저장된 세션을 복원할 수 없습니다. Garmin 계정을 다시 연결하세요.",
        "error.access_denied": "Garmin이 요청한 데이터에 대한 접근을 거부했습니다.",
        "error.security_challenge": "Garmin의 보안 확인으로 연결이 차단되었습니다. 나중에 다시 시도하세요.",
        "error.network": "Garmin에 연결하지 못했습니다. 인터넷 연결을 확인하세요.",
        "error.dependency": "Garmin 연결 구성요소를 사용할 수 없습니다. 최신 버전의 Garmin Desk를 다시 설치하세요.",
        "error.unknown": "요청을 완료하지 못했습니다. 다시 시도하세요.",
        "error.timeout": "Garmin이 응답하는 데 너무 오래 걸렸습니다. 다시 시도하세요.",
        "error.keychain": "macOS 키체인에 접근하지 못했습니다. 잠금이 해제되어 있는지 확인하세요.",
        "error.protocol": "Garmin이 앱에서 읽을 수 없는 데이터를 반환했습니다. 나중에 다시 시도하세요.",
        "error.storage": "이 Mac에 데이터를 저장하지 못했습니다. 여유 공간과 접근 권한을 확인하세요.",
        "error.login_item": "macOS 시스템 설정 → 일반 → 로그인 항목에서 Garmin Desk의 로그인 시 실행을 허용하세요.",
        "training.title": "훈련",
        "training.last": "최근 완료",
        "training.next": "다음 예정",
        "training.completed": "완료됨",
        "training.planned": "예정됨",
        "training.recent": "최근 활동",
        "training.upcoming": "예정된 운동",
        "training.workout": "운동",
        "training.dateUnknown": "날짜 정보 없음",
        "training.timeUnknown": "시간 정보 없음",
        "training.localTime": "기록된 현지 시각",
        "training.durationUnknown": "운동시간 정보 없음",
        "training.pastUnavailable": "기록을 아직 사용할 수 없습니다",
        "training.pastUnavailableHint": "이 항목을 Garmin에서 아직 가져오지 못했습니다.",
        "training.pastEmpty": "최근 응답에 활동이 없습니다",
        "training.pastCoverage": "최근 활동 최대 20개 · 전체 기록이 아닙니다",
        "training.futureUnavailable": "일정을 아직 사용할 수 없습니다",
        "training.futureUnavailableHint": "캘린더를 사용할 수 없다고 운동이 없는 것은 아닙니다.",
        "training.futureEmpty": "가져온 범위에 운동이 없습니다",
        "training.calendar": "공개된 Garmin 캘린더",
        "training.adaptive": "확인된 적응형 캘린더",
        "training.partial": "캘린더의 일부를 사용할 수 없습니다",
        "training.expiredCoverage": "확인된 기간이 끝났습니다",
        "training.refreshCalendar": "새 기간을 확인하려면 새로 고침하세요.",
        "training.updated": "업데이트 시각",
        "training.updatedUnknown": "업데이트 시각 알 수 없음",
        "training.cached": "저장된 데이터",
        "training.refreshFailed": "이 항목을 새로 고치지 못했습니다",
        "training.rateLimit": "Garmin이 요청을 일시적으로 제한 중입니다",
        "training.signIn": "새로 고치려면 Garmin Connect에 로그인하세요",
        "training.hour": "시간",
        "training.minute": "분",
        "training.second": "초",
        "training.km": "km",
        "training.sport.running": "러닝",
        "training.sport.trail_running": "트레일 러닝",
        "training.sport.treadmill_running": "트레드밀 러닝",
        "training.sport.track_running": "트랙 러닝",
        "training.sport.cycling": "사이클링",
        "training.sport.mountain_biking": "오프로드 사이클링",
        "training.sport.indoor_cycling": "실내 사이클링",
        "training.sport.swimming": "수영",
        "training.sport.open_water_swimming": "오픈워터 수영",
        "training.sport.walking": "걷기",
        "training.sport.hiking": "하이킹",
        "training.sport.strength_training": "근력 운동",
        "training.sport.cardio_training": "유산소 운동",
        "training.sport.elliptical": "일립티컬",
        "training.sport.stair_climbing": "계단 오르기",
        "training.sport.yoga": "요가",
        "training.sport.pilates": "필라테스",
        "training.sport.rowing": "로잉",
        "training.sport.tennis": "테니스",
        "training.sport.golf": "골프",
        "training.sport.alpine_skiing": "알파인 스키",
        "training.sport.cross_country_skiing": "크로스컨트리 스키",
        "training.sport.snowboarding": "스노보드",
        "training.sport.triathlon": "멀티스포츠",
        "training.noPublishedThrough": "%@까지 공개된 운동이 없습니다",
        "training.checkedThrough": "%@까지 확인됨",
    ]
}
