// Full application and widget catalog. Keep keys aligned with the English catalog.
enum LocalizationES {
    static let strings: [String: String] = [
        "widget.summary.minimum": "Mantén al menos una medición seleccionada.",
        "widget.summary.hint": "Solo se muestran las mediciones seleccionadas que tienen datos disponibles. Su cantidad depende del tamaño del widget.",
        "widget.summary.primary": "Medición principal preferida",
        "widget.summary.choose": "Elegir mediciones",
        "settings.widgets": "Widgets",
        "settings.widgetsSubtitle": "Cinco widgets listos para tu escritorio.",
        "widget.type": "Tipo de widget",
        "widget.appearance": "Apariencia de los widgets",
        "widget.appearance.colorful": "Colorida",
        "widget.appearance.light": "Clara",
        "widget.appearance.dark": "Oscura",
        "widget.appearanceHint": "Una apariencia para los cinco widgets del escritorio.",
        "widget.automaticHint": "Las mediciones disponibles se seleccionan automáticamente.",
        "widget.guide.fixedTypes": "Elige un tipo y un tamaño de widget y añádelo al escritorio.",
        "widget.slot.day": "Día",
        "widget.slot.day.description": "Body Battery, pasos, estrés y actividad diaria.",
        "onboarding.title": "Tus datos de Garmin en tu Mac",
        "onboarding.privacy": "Tus mediciones se guardan en este Mac",
        "onboarding.detail": "Conecta tu cuenta de Garmin para ver tus mediciones aquí y en los widgets del escritorio.",
        "data.available": "Últimas mediciones",
        "data.nightEnding": "Noche que termina el",
        "data.measured": "Medido",
        "data.received": "Recibido",
        "metric.short.spo2": "SpO₂ · media diaria",
        "data.waiting": "Esperando datos de tu reloj",
        "data.waitingNew": "Esperando nuevas mediciones",
        "data.unchanged": "No hay cambios en tus mediciones",
        "data.checkFailed": "No se pudieron actualizar los datos de Garmin",
        "data.unchangedHint": "¿Esperabas mediciones más recientes? Abre Garmin Connect en tu teléfono y sincroniza el reloj. Las recibiremos automáticamente.",
        "data.retainedAllHint": "Abajo se muestran tus últimas mediciones con sus fechas. Abre Garmin Connect en tu teléfono y sincroniza el reloj para obtener mediciones más recientes.",
        "data.previous": "Últimos disponibles",
        "data.retainedHint": "Aún no han llegado algunas mediciones. Conservamos tus últimos valores con sus fechas. Sincroniza el reloj en Garmin Connect en tu teléfono.",
        "data.waitingHint": "Abre Garmin Connect en tu teléfono y sincroniza el reloj. Tus mediciones aparecerán aquí automáticamente.",
        "widget.notice.connection": "Volver a conectar Garmin",
        "widget.notice.unavailable": "No se pudo actualizar",
        "widget.notice.waiting": "Esperando nuevos datos",
        "widget.waiting": "Esperando datos",
        "widget.waitingHint": "Sincroniza el reloj en Garmin Connect en tu teléfono. Tus mediciones aparecerán aquí automáticamente.",
        "widget.previous": "Últimos disponibles",
        "widget.slot.overview.description": "Tus mediciones seleccionadas en un solo widget.",
        "widget.slot.sport.description": "Predisposición para entrenar, recuperación, carga y VO₂ máx.",
        "widget.slot.sleep.description": "Duración del sueño, puntuación del sueño y VFC nocturna.",
        "widget.slot.training.description": "Un calendario de actividades completadas y entrenamientos programados.",
        "widget.preview.easyRun": "Carrera suave",
        "widget.preview.intervals": "Intervalos de carrera",
        "profile.availableMetrics": "Usar mediciones disponibles",
        "profile.availableMetricsHint": "Omite las mediciones que faltan y completa el widget con métricas relacionadas. Desactívalo para mantener tu selección exacta.",
        "profile.content": "Contenido",
        "content.metrics": "Métricas",
        "content.training": "Calendario de entrenamientos",
        "content.mixed": "Ambos",
        "profile.previewMetricsOnly": "Esta vista previa muestra las métricas. Las tarjetas de entrenamiento también aparecen en la sección Resumen.",
        "status.signInRequired": "Debes iniciar sesión",
        "connection.retryAfter": "Vuelve a intentarlo después de",
        "connection.reconnectDetail": "Abre la ventana de Garmin y termina de iniciar sesión para reanudar las actualizaciones.",
        "widget.guide.staticProfile": "Elige un tipo y un tamaño de widget y añádelo al escritorio.",
        "widget.guide.unavailable": "Consulta tus mediciones y las vistas previas de los widgets en la app.",
        "widget.sharingDataUnavailable": "Los datos de los widgets aún no están disponibles. Puedes seguir viendo tus mediciones en la app.",
        "widget.slot.overview": "Resumen",
        "widget.slot.sport": "Deporte",
        "widget.slot.sleep": "Sueño",
        "widget.slot.training": "Calendario de entrenamientos",
        "widget.slot.firstProfile": "Primer perfil",
        "widget.slot.unassigned": "Elegir un perfil…",
        "profile.templates": "Empezar con una plantilla",
        "profile.custom": "Perfil personalizado",
        "profile.template.life": "Vida diaria",
        "profile.template.sport": "Deporte",
        "profile.template.sleep": "Sueño",
        "profile.previewSize": "Tamaño del widget",
        "profile.preview.small": "Pequeño",
        "profile.preview.medium": "Mediano",
        "profile.preview.large": "Grande",
        "profile.previewCount": "Muestra %d de %d métricas. Todas las métricas seleccionadas están disponibles en la sección Resumen.",
        "widget.galleryTitle": "Resumen de Garmin",
        "widget.galleryDescription": "Salud, sueño, actividad y entrenamiento en cinco widgets listos para usar.",
        "widget.galleryStaticDescription": "Elige un tipo y un tamaño de widget. Las mediciones disponibles aparecen automáticamente.",
        "connection.webTitle": "Conectar Garmin",
        "connection.webSubtitle": "Conéctate una vez. Tus mediciones se actualizan automáticamente.",
        "connection.webIntro": "Iniciar sesión en Garmin Connect",
        "connection.webDetail": "Se abrirá una ventana segura de Garmin. Completa el inicio de sesión y las verificaciones que solicite Garmin. La app guardará esta conexión en tu Mac.",
        "connection.webSignIn": "Iniciar sesión con Garmin",
        "connection.webPrivacy": "Las mediciones y la sesión web de Garmin se quedan en este Mac. Tu contraseña se envía directamente a Garmin. No hay un servidor independiente ni análisis de uso.",
        "connection.automaticHint": "Tus datos se actualizan en segundo plano, incluso al activar el Mac. Mantén Garmin Desk abierto para recibir actualizaciones automáticas.",
        "connection.reconnect": "Volver a conectar Garmin",
        "connection.nextSync": "Próxima actualización después de",
        "error.partial": "No se pudieron actualizar algunas mediciones. Los datos guardados siguen disponibles.",
        "diagnostic.title": "Detalles de conexión",
        "diagnostic.stage": "Etapa",
        "diagnostic.apiCode": "Código de Garmin",
        "diagnostic.requests": "Respuestas recibidas",
        "menu.edit": "Edición",
        "menu.cut": "Cortar",
        "menu.copy": "Copiar",
        "menu.paste": "Pegar",
        "menu.selectAll": "Seleccionar todo",
        "app.subtitle": "Tu día de un vistazo",
        "app.device": "Garmin fēnix 8",
        "dashboard.title": "Resumen",
        "dashboard.profile": "Perfil",
        "dashboard.moreMetrics": "Los widgets más grandes pueden mostrar más métricas",
        "dashboard.configure": "Ajustes de los widgets",
        "widget.setup": "Configurar widgets del escritorio",
        "widget.customize": "Ajustes de los widgets",
        "widget.guide.add": "Haz clic con el botón derecho en el escritorio y elige Editar widgets. Busca GarminDesk en la galería.",
        "widget.guide.profile": "Elige un tipo y un tamaño de widget y añádelo al escritorio.",
        "widget.guide.refresh": "Garmin Desk obtiene tus mediciones. macOS decide cuándo se actualiza el widget del escritorio.",
        "widget.sharingUnavailable": "Los widgets de escritorio no están disponibles en esta versión. Puedes seguir viendo tus mediciones en la app.",
        "widget.openApp": "Abrir GarminDesk",
        "widget.openAppHint": "Conecta tu cuenta de Garmin en la app.",
        "widget.profileMissing": "Perfil eliminado",
        "widget.profileMissingHint": "Elige otro perfil en los ajustes de este widget.",
        "widget.demo": "DEMO",
        "widget.connect": "Conecta Garmin en la app",
        "dashboard.empty": "Elige las métricas que quieres ver en los ajustes.",
        "dashboard.connect": "Conectar Garmin",
        "action.settings": "Ajustes",
        "action.sync": "Actualizar",
        "action.quit": "Salir de Garmin Desk",
        "action.cancel": "Cancelar",
        "action.save": "Guardar",
        "action.delete": "Eliminar",
        "action.duplicate": "Duplicar",
        "action.add": "Añadir perfil",
        "action.up": "Subir",
        "action.down": "Bajar",
        "action.show": "Mostrar",
        "action.hide": "Ocultar",
        "action.done": "Listo",
        "action.retry": "Volver a intentar",
        "data.demo": "Datos de demostración",
        "data.updated": "Comprobado",
        "data.stale": "Los datos pueden estar desactualizados",
        "data.day": "Datos del",
        "data.partial": "Algunas mediciones no están disponibles",
        "data.emptyDay": "Garmin aún no tiene mediciones para esta fecha. Sincroniza tu reloj con Garmin Connect para actualizarlas.",
        "data.empty": "Aún no hay mediciones",
        "data.demoDetail": "Valores de ejemplo. Conecta tu cuenta para ver tus mediciones.",
        "data.local": "Guardado en este Mac",
        "data.source": "Última sincronización de Garmin Connect",
        "data.syncing": "Comprobando Garmin Connect…",
        "status.connected": "Garmin conectado",
        "status.notConnected": "Garmin no conectado",
        "status.connecting": "Conectando…",
        "settings.title": "Ajustes",
        "settings.profiles": "Perfiles de widgets",
        "settings.connection": "Cuenta de Garmin",
        "settings.general": "General",
        "settings.profilesSubtitle": "Crea una vista para cada momento de tu día.",
        "settings.generalSubtitle": "Haz que Garmin Desk se adapte a tu Mac.",
        "profile.name": "Nombre del perfil",
        "profile.primary": "Métrica principal",
        "profile.metrics": "Métricas",
        "profile.metricsHint": "Elige qué mostrar. La métrica principal siempre aparece primero.",
        "profile.appearance": "Apariencia",
        "profile.style": "Estilo",
        "profile.density": "Densidad",
        "profile.preview": "Vista previa",
        "profile.added": "Nuevo perfil",
        "profile.new": "Nuevo perfil",
        "profile.default": "Mi día",
        "profile.copy": "Copia",
        "profile.untitled": "Perfil sin título",
        "profile.deleteTitle": "¿Eliminar este perfil?",
        "profile.deleteMessage": "Se eliminará el perfil. Tus datos de Garmin permanecerán en este Mac.",
        "profile.oneRequired": "Conserva al menos un perfil.",
        "profile.enabled": "Incluidas",
        "profile.available": "Métricas disponibles",
        "profile.count": "métricas",
        "profile.mainBadge": "Principal",
        "style.calm": "Sereno",
        "style.sport": "Deportivo",
        "style.monochrome": "Monocromo",
        "density.comfortable": "Cómoda",
        "density.compact": "Compacta",
        "connection.title": "Tu cuenta de Garmin",
        "connection.subtitle": "Tu Mac se conecta directamente a Garmin Connect.",
        "connection.localTitle": "Tus datos se quedan contigo",
        "connection.localDetail": "Las mediciones se almacenan en la caché de este Mac. Las credenciales de sesión se guardan en el llavero de macOS. La app no tiene un servidor independiente.",
        "connection.email": "Correo electrónico",
        "connection.password": "Contraseña",
        "connection.china": "Usar Garmin China",
        "connection.signIn": "Conectar cuenta",
        "connection.disconnect": "Desconectar y borrar datos locales",
        "connection.disconnectTitle": "¿Desconectar Garmin?",
        "connection.disconnectMessage": "Se eliminarán de este Mac la sesión de Garmin guardada y las mediciones en caché. Tus preferencias se conservarán.",
        "connection.demo": "Explorar con datos de demostración",
        "connection.demoHint": "Los valores de demostración siempre están identificados.",
        "connection.syncHint": "Sincroniza el reloj con Garmin Connect para que las nuevas mediciones estén disponibles aquí.",
        "connection.secureHint": "Tu contraseña solo se usa para iniciar sesión y esta app no la guarda.",
        "connection.mfaTitle": "Código de verificación",
        "connection.mfaHint": "Introduce el código solicitado por Garmin para completar la conexión.",
        "connection.mfaCode": "Código",
        "connection.verify": "Verificar",
        "connection.cancelLogin": "Cancelar inicio de sesión",
        "general.language": "Idioma",
        "general.appearance": "Apariencia",
        "general.refresh": "Intervalo de actualización",
        "general.system": "Usar ajuste del sistema",
        "general.light": "Claro",
        "general.dark": "Oscuro",
        "general.minutes5": "Cada 5 minutos",
        "general.minutes15": "Cada 15 minutos",
        "general.minutes30": "Cada 30 minutos",
        "general.minutes60": "Cada hora",
        "general.refreshHint": "Las actualizaciones usan las últimas mediciones disponibles en Garmin Connect.",
        "general.localNotice": "Tus preferencias se guardan automáticamente en este Mac.",
        "general.launchAtLogin": "Abrir Garmin Desk al iniciar sesión",
        "general.backgroundHint": "Las actualizaciones automáticas continúan al cerrar la ventana. Elige «Salir de Garmin Desk» o pulsa ⌘Q para cerrar la app.",
        "menu.about": "Acerca de Garmin Desk",
        "menu.hideApp": "Ocultar Garmin Desk",
        "menu.hideOthers": "Ocultar otros",
        "menu.showAll": "Mostrar todo",
        "menu.file": "Archivo",
        "menu.closeWindow": "Cerrar ventana",
        "menu.window": "Ventana",
        "menu.mainWindow": "Garmin Desk",
        "menu.minimize": "Minimizar",
        "menu.zoom": "Zoom",
        "category.health": "Salud y recuperación",
        "category.sleep": "Sueño",
        "category.activity": "Actividad diaria",
        "category.training": "Entrenamiento",
        "category.body": "Cuerpo e hidratación",
        "metric.steps": "Pasos",
        "metric.stepGoal": "Objetivo de pasos",
        "metric.distance": "Distancia",
        "metric.calories": "Calorías totales",
        "metric.activeCalories": "Calorías activas",
        "metric.floors": "Pisos subidos",
        "metric.intensityMinutes": "Minutos de intensidad",
        "metric.restingHeartRate": "Frecuencia cardiaca en reposo",
        "metric.heartRate": "Última frecuencia cardiaca",
        "metric.stress": "Estrés medio diario",
        "metric.bodyBattery": "Body Battery",
        "metric.sleepDuration": "Duración del sueño",
        "metric.sleepScore": "Puntuación del sueño",
        "metric.deepSleep": "Sueño profundo",
        "metric.remSleep": "Sueño REM",
        "metric.lightSleep": "Sueño ligero",
        "metric.awakeSleep": "Tiempo despierto",
        "metric.hrv": "VFC nocturna",
        "metric.spo2": "SpO₂ media diaria",
        "metric.respiration": "Respiración media durante el sueño",
        "metric.trainingReadiness": "Predisposición para entrenar",
        "metric.recoveryTime": "Tiempo de recuperación",
        "metric.vo2Max": "VO₂ máx. de carrera",
        "metric.trainingLoad": "Carga aguda de entrenamiento",
        "metric.weight": "Peso",
        "metric.hydration": "Hidratación",
        "metric.short.sleepDuration": "Sueño",
        "metric.short.stress": "Estrés · día",
        "metric.short.restingHeartRate": "FC en reposo",
        "metric.short.trainingReadiness": "Predisposición",
        "metric.short.hrv": "VFC · noche",
        "metric.short.respiration": "Respir. · sueño",
        "metric.short.intensityMinutes": "Min. de intensidad",
        "metric.short.activeCalories": "Calorías activas",
        "metric.short.recoveryTime": "Recuperación",
        "metric.short.trainingLoad": "Carga aguda",
        "metric.short.vo2Max": "VO₂ máx. carrera",
        "metric.short.calories": "Calorías totales",
        "unit.minutes": "min",
        "unit.hours": "h",
        "unit.km": "km",
        "unit.kg": "kg",
        "unit.ml": "ml",
        "unit.bpm": "ppm",
        "unit.kcal": "kcal",
        "unit.ms": "ms",
        "unit.breaths": "resp/min",
        "unit.vo2": "ml/kg/min",
        "error.auth": "No se pudo iniciar sesión. Comprueba tus datos y vuelve a intentarlo.",
        "error.rate_limit": "Garmin ha limitado temporalmente las solicitudes. Vuelve a intentarlo más tarde.",
        "error.session_unsupported": "Esta app no puede restaurar la sesión guardada. Vuelve a conectar tu cuenta de Garmin.",
        "error.access_denied": "Garmin ha denegado el acceso a los datos solicitados.",
        "error.security_challenge": "Una comprobación de seguridad de Garmin ha bloqueado la conexión. Vuelve a intentarlo más tarde.",
        "error.network": "No se pudo contactar con Garmin. Comprueba tu conexión a internet.",
        "error.dependency": "El componente de conexión con Garmin no está disponible. Reinstala la última versión de Garmin Desk.",
        "error.unknown": "No se pudo completar la solicitud. Vuelve a intentarlo.",
        "error.timeout": "Garmin ha tardado demasiado en responder. Vuelve a intentarlo.",
        "error.keychain": "No se pudo acceder al llavero de macOS. Comprueba que esté desbloqueado.",
        "error.protocol": "Garmin ha devuelto datos que la app no pudo leer. Vuelve a intentarlo más tarde.",
        "error.storage": "No se pudieron guardar los datos en este Mac. Comprueba el espacio disponible y los permisos.",
        "error.login_item": "Permite que Garmin Desk se abra al iniciar sesión en Ajustes de macOS → General → Ítems de inicio.",
        "training.title": "Entrenamiento",
        "training.last": "Último completado",
        "training.next": "Próximo previsto",
        "training.completed": "Completado",
        "training.planned": "Programado",
        "training.recent": "Actividades recientes",
        "training.upcoming": "Próximos entrenamientos",
        "training.workout": "Entrenamiento",
        "training.dateUnknown": "Fecha no indicada",
        "training.timeUnknown": "Hora no indicada",
        "training.localTime": "hora local registrada",
        "training.durationUnknown": "Duración no indicada",
        "training.pastUnavailable": "El historial aún no está disponible",
        "training.pastUnavailableHint": "Esta sección aún no se ha podido obtener de Garmin.",
        "training.pastEmpty": "No hay actividades en la última respuesta",
        "training.pastCoverage": "Hasta 20 actividades recientes · historial incompleto",
        "training.futureUnavailable": "El programa aún no está disponible",
        "training.futureUnavailableHint": "Que el calendario no esté disponible no significa que no haya entrenamientos.",
        "training.futureEmpty": "No hay entrenamientos en la parte obtenida",
        "training.calendar": "Calendario publicado de Garmin",
        "training.adaptive": "Calendario adaptativo verificado",
        "training.partial": "Parte del calendario no está disponible",
        "training.expiredCoverage": "El período comprobado ha terminado",
        "training.refreshCalendar": "Actualiza para comprobar un nuevo período.",
        "training.updated": "Actualizado",
        "training.updatedUnknown": "Hora de actualización desconocida",
        "training.cached": "Datos guardados",
        "training.refreshFailed": "No se pudo actualizar esta sección",
        "training.rateLimit": "Garmin está limitando temporalmente las solicitudes",
        "training.signIn": "Inicia sesión en Garmin Connect para actualizar",
        "training.hour": "h",
        "training.minute": "min",
        "training.second": "s",
        "training.km": "km",
        "training.sport.running": "Carrera",
        "training.sport.trail_running": "Carrera de montaña",
        "training.sport.treadmill_running": "Carrera en cinta",
        "training.sport.track_running": "Carrera en pista",
        "training.sport.cycling": "Ciclismo",
        "training.sport.mountain_biking": "Ciclismo de montaña",
        "training.sport.indoor_cycling": "Ciclismo en interiores",
        "training.sport.swimming": "Natación",
        "training.sport.open_water_swimming": "Natación en aguas abiertas",
        "training.sport.walking": "Caminata",
        "training.sport.hiking": "Senderismo",
        "training.sport.strength_training": "Entrenamiento de fuerza",
        "training.sport.cardio_training": "Cardio",
        "training.sport.elliptical": "Elíptica",
        "training.sport.stair_climbing": "Subir escaleras",
        "training.sport.yoga": "Yoga",
        "training.sport.pilates": "Pilates",
        "training.sport.rowing": "Remo",
        "training.sport.tennis": "Tenis",
        "training.sport.golf": "Golf",
        "training.sport.alpine_skiing": "Esquí alpino",
        "training.sport.cross_country_skiing": "Esquí de fondo",
        "training.sport.snowboarding": "Snowboard",
        "training.sport.triathlon": "Multideporte",
        "training.noPublishedThrough": "No hay entrenamientos publicados hasta el %@",
        "training.checkedThrough": "comprobado hasta el %@",
    ]
}
