// Full application and widget catalog. Keep keys aligned with the English catalog.
enum LocalizationDE {
    static let strings: [String: String] = [
        "widget.summary.minimum": "Mindestens ein Messwert muss ausgewählt bleiben.",
        "widget.summary.hint": "Nur ausgewählte Messwerte mit verfügbaren Daten werden angezeigt. Die Widget-Größe bestimmt, wie viele Platz haben.",
        "widget.summary.primary": "Bevorzugter Hauptmesswert",
        "widget.summary.choose": "Messwerte auswählen",
        "settings.widgets": "Widgets",
        "settings.widgetsSubtitle": "Fünf fertige Widgets für deinen Schreibtisch.",
        "widget.type": "Widget-Typ",
        "widget.appearance": "Widget-Darstellung",
        "widget.appearance.colorful": "Farbig",
        "widget.appearance.light": "Hell",
        "widget.appearance.dark": "Dunkel",
        "widget.appearanceHint": "Eine Darstellung für alle fünf Desktop-Widgets.",
        "widget.automaticHint": "Verfügbare Messwerte werden automatisch ausgewählt.",
        "widget.guide.fixedTypes": "Wähle einen Widget-Typ und eine Größe und füge das Widget zum Schreibtisch hinzu.",
        "widget.slot.day": "Tag",
        "widget.slot.day.description": "Body Battery, Schritte, Stress und tägliche Aktivität.",
        "onboarding.title": "Deine Garmin-Daten auf deinem Mac",
        "onboarding.privacy": "Deine Messwerte werden auf diesem Mac gespeichert",
        "onboarding.detail": "Verbinde dein Garmin-Konto, um deine Messwerte hier und in Desktop-Widgets zu sehen.",
        "data.available": "Neueste Messwerte",
        "data.nightEnding": "Nacht bis zum",
        "data.measured": "Gemessen",
        "data.received": "Empfangen",
        "metric.short.spo2": "SpO₂ · Tagesmittel",
        "data.waiting": "Warten auf Daten deiner Uhr",
        "data.waitingNew": "Warten auf neue Messwerte",
        "data.unchanged": "Keine Änderungen bei deinen Messwerten",
        "data.checkFailed": "Garmin-Daten konnten nicht aktualisiert werden",
        "data.unchangedHint": "Du erwartest neuere Messwerte? Öffne Garmin Connect auf deinem Smartphone und synchronisiere deine Uhr. Wir übernehmen die Daten automatisch.",
        "data.retainedAllHint": "Unten siehst du deine letzten Messwerte mit Datum. Öffne Garmin Connect auf deinem Smartphone und synchronisiere deine Uhr für neuere Messwerte.",
        "data.previous": "Zuletzt verfügbar",
        "data.retainedHint": "Einige Messwerte sind noch nicht eingetroffen. Deine letzten Werte mit Datum bleiben erhalten. Synchronisiere deine Uhr in Garmin Connect auf deinem Smartphone.",
        "data.waitingHint": "Öffne Garmin Connect auf deinem Smartphone und synchronisiere deine Uhr. Deine Messwerte erscheinen hier automatisch.",
        "widget.notice.connection": "Garmin erneut verbinden",
        "widget.notice.unavailable": "Aktualisierung fehlgeschlagen",
        "widget.notice.waiting": "Warten auf neue Daten",
        "widget.waiting": "Warten auf Daten",
        "widget.waitingHint": "Synchronisiere deine Uhr in Garmin Connect auf deinem Smartphone. Deine Messwerte erscheinen hier automatisch.",
        "widget.previous": "Zuletzt verfügbar",
        "widget.slot.overview.description": "Deine ausgewählten Messwerte in einem Widget.",
        "widget.slot.sport.description": "Trainingsbereitschaft, Erholung, Belastung und VO₂ max.",
        "widget.slot.sleep.description": "Schlafdauer, Schlafbewertung und nächtliche HRV.",
        "widget.slot.training.description": "Ein Kalender mit abgeschlossenen Aktivitäten und geplanten Trainings.",
        "widget.preview.easyRun": "Lockerer Lauf",
        "widget.preview.intervals": "Laufintervalle",
        "profile.availableMetrics": "Verfügbare Messwerte verwenden",
        "profile.availableMetricsHint": "Fehlende Messwerte überspringen und das Widget mit passenden Messwerten ergänzen. Deaktiviere dies, um genau deine Auswahl beizubehalten.",
        "profile.content": "Inhalt",
        "content.metrics": "Messwerte",
        "content.training": "Trainingskalender",
        "content.mixed": "Beides",
        "profile.previewMetricsOnly": "Diese Vorschau zeigt die Messwerte. Deine Trainingskarten erscheinen ebenfalls in der Übersicht.",
        "status.signInRequired": "Anmeldung erforderlich",
        "connection.retryAfter": "Erneut versuchen nach",
        "connection.reconnectDetail": "Öffne das Garmin-Fenster und schließe die Anmeldung ab, um Aktualisierungen fortzusetzen.",
        "widget.guide.staticProfile": "Wähle einen Widget-Typ und eine Größe und füge das Widget zum Schreibtisch hinzu.",
        "widget.guide.unavailable": "Sieh dir deine Messwerte und Widget-Vorschauen in der App an.",
        "widget.sharingDataUnavailable": "Widget-Daten sind noch nicht verfügbar. Du kannst deine Messwerte weiterhin in der App ansehen.",
        "widget.slot.overview": "Zusammenfassung",
        "widget.slot.sport": "Sport",
        "widget.slot.sleep": "Schlaf",
        "widget.slot.training": "Trainingskalender",
        "widget.slot.firstProfile": "Erstes Profil",
        "widget.slot.unassigned": "Profil wählen…",
        "profile.templates": "Mit einer Vorlage beginnen",
        "profile.custom": "Eigenes Profil",
        "profile.template.life": "Alltag",
        "profile.template.sport": "Sport",
        "profile.template.sleep": "Schlaf",
        "profile.previewSize": "Widget-Größe",
        "profile.preview.small": "Klein",
        "profile.preview.medium": "Mittel",
        "profile.preview.large": "Groß",
        "profile.previewCount": "Zeigt %d von %d Messwerten. Alle ausgewählten Messwerte findest du in der Übersicht.",
        "widget.galleryTitle": "Garmin-Zusammenfassung",
        "widget.galleryDescription": "Gesundheit, Schlaf, Aktivität und Training in fünf fertigen Widgets.",
        "widget.galleryStaticDescription": "Wähle einen Widget-Typ und eine Größe. Verfügbare Messwerte erscheinen automatisch.",
        "connection.webTitle": "Garmin verbinden",
        "connection.webSubtitle": "Einmal verbinden. Deine Messwerte werden automatisch aktualisiert.",
        "connection.webIntro": "Bei Garmin Connect anmelden",
        "connection.webDetail": "Ein sicheres Garmin-Fenster wird geöffnet. Schließe die Anmeldung und alle von Garmin angeforderten Bestätigungen ab. Die App speichert diese Verbindung auf deinem Mac.",
        "connection.webSignIn": "Mit Garmin anmelden",
        "connection.webPrivacy": "Messwerte und die Garmin-Websitesitzung bleiben auf diesem Mac. Dein Passwort wird direkt an Garmin übermittelt. Es gibt keinen separaten Server und keine Nutzungsanalyse.",
        "connection.automaticHint": "Deine Daten werden im Hintergrund aktualisiert, auch nach dem Ruhezustand. Lass Garmin Desk für automatische Aktualisierungen geöffnet.",
        "connection.reconnect": "Garmin erneut verbinden",
        "connection.nextSync": "Nächste Aktualisierung nach",
        "error.partial": "Einige Messwerte konnten nicht aktualisiert werden. Gespeicherte Daten sind weiterhin verfügbar.",
        "diagnostic.title": "Verbindungsdetails",
        "diagnostic.stage": "Schritt",
        "diagnostic.apiCode": "Garmin-Code",
        "diagnostic.requests": "Erhaltene Antworten",
        "menu.edit": "Bearbeiten",
        "menu.cut": "Ausschneiden",
        "menu.copy": "Kopieren",
        "menu.paste": "Einsetzen",
        "menu.selectAll": "Alles auswählen",
        "app.subtitle": "Dein Tag auf einen Blick",
        "app.device": "Garmin fēnix 8",
        "dashboard.title": "Übersicht",
        "dashboard.profile": "Profil",
        "dashboard.moreMetrics": "Größere Widgets können mehr Messwerte anzeigen",
        "dashboard.configure": "Widget-Einstellungen",
        "widget.setup": "Desktop-Widgets einrichten",
        "widget.customize": "Widget-Einstellungen",
        "widget.guide.add": "Klicke mit der rechten Maustaste auf den Schreibtisch und wähle „Widgets bearbeiten“. Suche GarminDesk in der Galerie.",
        "widget.guide.profile": "Wähle einen Widget-Typ und eine Größe und füge das Widget zum Schreibtisch hinzu.",
        "widget.guide.refresh": "Garmin Desk ruft deine Messwerte ab. macOS entscheidet, wann das Desktop-Widget aktualisiert wird.",
        "widget.sharingUnavailable": "Desktop-Widgets sind in dieser Version nicht verfügbar. Deine Messwerte kannst du weiterhin in der App ansehen.",
        "widget.openApp": "GarminDesk öffnen",
        "widget.openAppHint": "Verbinde dein Garmin-Konto in der App.",
        "widget.profileMissing": "Profil entfernt",
        "widget.profileMissingHint": "Wähle ein anderes Profil in den Einstellungen dieses Widgets.",
        "widget.demo": "DEMO",
        "widget.connect": "Garmin in der App verbinden",
        "dashboard.empty": "Wähle in den Einstellungen die gewünschten Messwerte.",
        "dashboard.connect": "Garmin verbinden",
        "action.settings": "Einstellungen",
        "action.sync": "Aktualisieren",
        "action.quit": "Garmin Desk beenden",
        "action.cancel": "Abbrechen",
        "action.save": "Sichern",
        "action.delete": "Löschen",
        "action.duplicate": "Duplizieren",
        "action.add": "Profil hinzufügen",
        "action.up": "Nach oben",
        "action.down": "Nach unten",
        "action.show": "Einblenden",
        "action.hide": "Ausblenden",
        "action.done": "Fertig",
        "action.retry": "Erneut versuchen",
        "data.demo": "Demodaten",
        "data.updated": "Geprüft",
        "data.stale": "Daten sind möglicherweise veraltet",
        "data.day": "Daten für",
        "data.partial": "Einige Messwerte sind nicht verfügbar",
        "data.emptyDay": "Garmin hat noch keine Messwerte für dieses Datum. Synchronisiere deine Uhr mit Garmin Connect, um sie zu aktualisieren.",
        "data.empty": "Noch kein Messwert",
        "data.demoDetail": "Beispielwerte. Verbinde dein Konto, um deine Messwerte zu sehen.",
        "data.local": "Auf diesem Mac gespeichert",
        "data.source": "Letzte Garmin-Connect-Synchronisierung",
        "data.syncing": "Garmin Connect wird geprüft…",
        "status.connected": "Garmin verbunden",
        "status.notConnected": "Garmin nicht verbunden",
        "status.connecting": "Verbindung wird hergestellt…",
        "settings.title": "Einstellungen",
        "settings.profiles": "Widget-Profile",
        "settings.connection": "Garmin-Konto",
        "settings.general": "Allgemein",
        "settings.profilesSubtitle": "Erstelle eine Ansicht für jeden Teil deines Tages.",
        "settings.generalSubtitle": "Passe Garmin Desk an deinen Mac an.",
        "profile.name": "Profilname",
        "profile.primary": "Hauptmesswert",
        "profile.metrics": "Messwerte",
        "profile.metricsHint": "Wähle die angezeigten Werte. Der Hauptmesswert erscheint immer zuerst.",
        "profile.appearance": "Darstellung",
        "profile.style": "Stil",
        "profile.density": "Dichte",
        "profile.preview": "Vorschau",
        "profile.added": "Neues Profil",
        "profile.new": "Neues Profil",
        "profile.default": "Mein Tag",
        "profile.copy": "Kopie",
        "profile.untitled": "Unbenanntes Profil",
        "profile.deleteTitle": "Dieses Profil löschen?",
        "profile.deleteMessage": "Das Profil wird entfernt. Deine Garmin-Daten bleiben auf diesem Mac.",
        "profile.oneRequired": "Mindestens ein Profil muss erhalten bleiben.",
        "profile.enabled": "Enthalten",
        "profile.available": "Verfügbare Messwerte",
        "profile.count": "Messwerte",
        "profile.mainBadge": "Hauptwert",
        "style.calm": "Ruhig",
        "style.sport": "Sport",
        "style.monochrome": "Monochrom",
        "density.comfortable": "Komfortabel",
        "density.compact": "Kompakt",
        "connection.title": "Dein Garmin-Konto",
        "connection.subtitle": "Dein Mac verbindet sich direkt mit Garmin Connect.",
        "connection.localTitle": "Deine Daten bleiben bei dir",
        "connection.localDetail": "Messwerte werden auf diesem Mac zwischengespeichert. Sitzungsdaten werden im macOS-Schlüsselbund gespeichert. Die App hat keinen separaten Server.",
        "connection.email": "E-Mail",
        "connection.password": "Passwort",
        "connection.china": "Garmin China verwenden",
        "connection.signIn": "Konto verbinden",
        "connection.disconnect": "Trennen und lokale Daten löschen",
        "connection.disconnectTitle": "Garmin trennen?",
        "connection.disconnectMessage": "Die gespeicherte Garmin-Sitzung und zwischengespeicherte Messwerte werden von diesem Mac gelöscht. Deine Einstellungen bleiben erhalten.",
        "connection.demo": "Mit Demodaten erkunden",
        "connection.demoHint": "Demowerte sind immer gekennzeichnet.",
        "connection.syncHint": "Synchronisiere deine Uhr mit Garmin Connect, damit neue Messwerte hier verfügbar werden.",
        "connection.secureHint": "Dein Passwort wird nur zur Anmeldung verwendet und von dieser App nicht gespeichert.",
        "connection.mfaTitle": "Bestätigungscode",
        "connection.mfaHint": "Gib den von Garmin angeforderten Code ein, um die Verbindung abzuschließen.",
        "connection.mfaCode": "Code",
        "connection.verify": "Bestätigen",
        "connection.cancelLogin": "Anmeldung abbrechen",
        "general.language": "Sprache",
        "general.appearance": "Darstellung",
        "general.refresh": "Aktualisierungsintervall",
        "general.system": "Systemeinstellung",
        "general.light": "Hell",
        "general.dark": "Dunkel",
        "general.minutes5": "Alle 5 Minuten",
        "general.minutes15": "Alle 15 Minuten",
        "general.minutes30": "Alle 30 Minuten",
        "general.minutes60": "Stündlich",
        "general.refreshHint": "Aktualisierungen verwenden die neuesten in Garmin Connect verfügbaren Messwerte.",
        "general.localNotice": "Deine Einstellungen werden automatisch auf diesem Mac gespeichert.",
        "general.launchAtLogin": "Garmin Desk bei der Anmeldung öffnen",
        "general.backgroundHint": "Nach dem Schließen des Fensters laufen automatische Aktualisierungen weiter. Wähle „Garmin Desk beenden“ oder drücke ⌘Q, um die App zu beenden.",
        "menu.about": "Über Garmin Desk",
        "menu.hideApp": "Garmin Desk ausblenden",
        "menu.hideOthers": "Andere ausblenden",
        "menu.showAll": "Alle einblenden",
        "menu.file": "Ablage",
        "menu.closeWindow": "Fenster schließen",
        "menu.window": "Fenster",
        "menu.mainWindow": "Garmin Desk",
        "menu.minimize": "Minimieren",
        "menu.zoom": "Zoomen",
        "category.health": "Gesundheit & Erholung",
        "category.sleep": "Schlaf",
        "category.activity": "Tägliche Aktivität",
        "category.training": "Training",
        "category.body": "Körper & Flüssigkeit",
        "metric.steps": "Schritte",
        "metric.stepGoal": "Schrittziel",
        "metric.distance": "Distanz",
        "metric.calories": "Kalorien gesamt",
        "metric.activeCalories": "Aktivitätskalorien",
        "metric.floors": "Etagen hochgestiegen",
        "metric.intensityMinutes": "Intensitätsminuten",
        "metric.restingHeartRate": "Ruheherzfrequenz",
        "metric.heartRate": "Letzte Herzfrequenz",
        "metric.stress": "Mittlerer Tagesstress",
        "metric.bodyBattery": "Body Battery",
        "metric.sleepDuration": "Schlafdauer",
        "metric.sleepScore": "Schlafwert",
        "metric.deepSleep": "Tiefschlaf",
        "metric.remSleep": "REM-Schlaf",
        "metric.lightSleep": "Leichtschlaf",
        "metric.awakeSleep": "Wachzeit",
        "metric.hrv": "Nächtliche HFV",
        "metric.spo2": "Mittlere tägliche SpO₂",
        "metric.respiration": "Mittlere Atemfrequenz im Schlaf",
        "metric.trainingReadiness": "Trainingsbereitschaft",
        "metric.recoveryTime": "Erholungszeit",
        "metric.vo2Max": "VO₂max beim Laufen",
        "metric.trainingLoad": "Akute Trainingsbelastung",
        "metric.weight": "Gewicht",
        "metric.hydration": "Flüssigkeitszufuhr",
        "metric.short.sleepDuration": "Schlaf",
        "metric.short.stress": "Stress · Tag",
        "metric.short.restingHeartRate": "Ruhepuls",
        "metric.short.trainingReadiness": "Bereitschaft",
        "metric.short.hrv": "HFV · Nacht",
        "metric.short.respiration": "Atmung · Schlaf",
        "metric.short.intensityMinutes": "Intensitätsmin.",
        "metric.short.activeCalories": "Aktivitätskalorien",
        "metric.short.recoveryTime": "Erholung",
        "metric.short.trainingLoad": "Akute Belastung",
        "metric.short.vo2Max": "Lauf-VO₂max",
        "metric.short.calories": "Kalorien gesamt",
        "unit.minutes": "min",
        "unit.hours": "h",
        "unit.km": "km",
        "unit.kg": "kg",
        "unit.ml": "ml",
        "unit.bpm": "S/min",
        "unit.kcal": "kcal",
        "unit.ms": "ms",
        "unit.breaths": "A/min",
        "unit.vo2": "ml/kg/min",
        "error.auth": "Anmeldung fehlgeschlagen. Prüfe deine Angaben und versuche es erneut.",
        "error.rate_limit": "Garmin hat die Anfragen vorübergehend begrenzt. Versuche es später erneut.",
        "error.session_unsupported": "Die App kann die gespeicherte Sitzung nicht wiederherstellen. Verbinde dein Garmin-Konto erneut.",
        "error.access_denied": "Garmin hat den Zugriff auf die angeforderten Daten verweigert.",
        "error.security_challenge": "Eine Garmin-Sicherheitsprüfung hat die Verbindung blockiert. Versuche es später erneut.",
        "error.network": "Garmin ist nicht erreichbar. Prüfe deine Internetverbindung.",
        "error.dependency": "Die Garmin-Verbindungskomponente ist nicht verfügbar. Installiere die neueste Version von Garmin Desk erneut.",
        "error.unknown": "Die Anfrage konnte nicht abgeschlossen werden. Versuche es erneut.",
        "error.timeout": "Garmin hat nicht rechtzeitig geantwortet. Versuche es erneut.",
        "error.keychain": "Zugriff auf den macOS-Schlüsselbund fehlgeschlagen. Prüfe, ob er entsperrt ist.",
        "error.protocol": "Garmin hat Daten gesendet, die die App nicht lesen konnte. Versuche es später erneut.",
        "error.storage": "Daten konnten auf diesem Mac nicht gespeichert werden. Prüfe Speicherplatz und Berechtigungen.",
        "error.login_item": "Erlaube Garmin Desk das Öffnen bei der Anmeldung unter macOS-Einstellungen → Allgemein → Anmeldeobjekte.",
        "training.title": "Training",
        "training.last": "Zuletzt absolviert",
        "training.next": "Als Nächstes geplant",
        "training.completed": "Absolviert",
        "training.planned": "Geplant",
        "training.recent": "Letzte Aktivitäten",
        "training.upcoming": "Anstehende Trainings",
        "training.workout": "Training",
        "training.dateUnknown": "Datum nicht angegeben",
        "training.timeUnknown": "Uhrzeit nicht angegeben",
        "training.localTime": "aufgezeichnete Ortszeit",
        "training.durationUnknown": "Dauer nicht angegeben",
        "training.pastUnavailable": "Verlauf noch nicht verfügbar",
        "training.pastUnavailableHint": "Dieser Bereich konnte bisher nicht erfolgreich von Garmin abgerufen werden.",
        "training.pastEmpty": "Keine Aktivitäten in der letzten Antwort",
        "training.pastCoverage": "Bis zu 20 letzte Aktivitäten · kein vollständiger Verlauf",
        "training.futureUnavailable": "Trainingsplan noch nicht verfügbar",
        "training.futureUnavailableHint": "Ein nicht verfügbarer Kalender bedeutet nicht, dass keine Trainings vorhanden sind.",
        "training.futureEmpty": "Keine Trainings in den abgerufenen Daten",
        "training.calendar": "Veröffentlichter Garmin-Kalender",
        "training.adaptive": "Geprüfter adaptiver Kalender",
        "training.partial": "Ein Teil des Kalenders ist nicht verfügbar",
        "training.expiredCoverage": "Der geprüfte Zeitraum ist abgelaufen",
        "training.refreshCalendar": "Aktualisieren, um einen neuen Zeitraum zu prüfen.",
        "training.updated": "Aktualisiert",
        "training.updatedUnknown": "Aktualisierungszeit unbekannt",
        "training.cached": "Gespeicherte Daten",
        "training.refreshFailed": "Dieser Bereich konnte nicht aktualisiert werden",
        "training.rateLimit": "Garmin begrenzt Anfragen vorübergehend",
        "training.signIn": "Zum Aktualisieren bei Garmin Connect anmelden",
        "training.hour": "h",
        "training.minute": "min",
        "training.second": "s",
        "training.km": "km",
        "training.sport.running": "Laufen",
        "training.sport.trail_running": "Trailrunning",
        "training.sport.treadmill_running": "Laufband",
        "training.sport.track_running": "Bahnlauf",
        "training.sport.cycling": "Radfahren",
        "training.sport.mountain_biking": "Geländeradfahren",
        "training.sport.indoor_cycling": "Indoor-Radfahren",
        "training.sport.swimming": "Schwimmen",
        "training.sport.open_water_swimming": "Freiwasserschwimmen",
        "training.sport.walking": "Gehen",
        "training.sport.hiking": "Wandern",
        "training.sport.strength_training": "Krafttraining",
        "training.sport.cardio_training": "Cardiotraining",
        "training.sport.elliptical": "Crosstrainer",
        "training.sport.stair_climbing": "Treppensteigen",
        "training.sport.yoga": "Yoga",
        "training.sport.pilates": "Pilates",
        "training.sport.rowing": "Rudern",
        "training.sport.tennis": "Tennis",
        "training.sport.golf": "Golf",
        "training.sport.alpine_skiing": "Ski Alpin",
        "training.sport.cross_country_skiing": "Skilanglauf",
        "training.sport.snowboarding": "Snowboarden",
        "training.sport.triathlon": "Multisport",
        "training.noPublishedThrough": "Keine veröffentlichten Trainings bis %@",
        "training.checkedThrough": "geprüft bis %@",
    ]
}
